/**
 * Client-side export utilities for generating real downloadable files.
 * Pure browser APIs — no server round-trip needed.
 */

// ─── CSV ──────────────────────────────────────────────────────────────────────

export function generateCSV(headers: string[], rows: string[][], filename: string): void {
  const escape = (val: string) => {
    if (/[",\n\r]/.test(val)) return `"${val.replace(/"/g, '""')}"`;
    return val;
  };
  const headerLine = headers.map(escape).join(',');
  const dataLines = rows.map((r) => r.map(escape).join(','));
  const csv = [headerLine, ...dataLines].join('\n');
  downloadBlob(csv, `${filename}.csv`, 'text/csv;charset=utf-8;');
}

// ─── JSON ─────────────────────────────────────────────────────────────────────

export function generateJSON(data: unknown, filename: string): void {
  const json = JSON.stringify(data, null, 2);
  downloadBlob(json, `${filename}.json`, 'application/json;charset=utf-8;');
}

// ─── PDF (lightweight — HTML-to-print approach) ──────────────────────────────

export function generatePDF(htmlContent: string, filename: string): void {
  const printWindow = window.open('', '_blank', 'width=800,height=600');
  if (!printWindow) {
    // Fallback: download as HTML
    downloadBlob(htmlContent, `${filename}.html`, 'text/html;charset=utf-8;');
    return;
  }
  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${filename}</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 32px; color: #1a1a2e; }
        h1 { font-size: 22px; margin-bottom: 8px; color: #1a1a2e; }
        h2 { font-size: 16px; margin-bottom: 12px; color: #4a4a6a; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 13px; }
        th { background: #f1f5f9; text-align: left; padding: 10px 12px; border-bottom: 2px solid #e2e8f0; font-weight: 600; color: #475569; }
        td { padding: 8px 12px; border-bottom: 1px solid #f1f5f9; color: #334155; }
        tr:hover td { background: #f8fafc; }
        .meta { font-size: 12px; color: #94a3b8; margin-bottom: 16px; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 9999px; font-size: 11px; font-weight: 600; }
        .badge-green { background: #dcfce7; color: #166534; }
        .badge-amber { background: #fef3c7; color: #92400e; }
        .badge-red { background: #fee2e2; color: #991b1b; }
        .total-row td { font-weight: 700; border-top: 2px solid #e2e8f0; }
        @media print { body { padding: 16px; } }
      </style>
    </head>
    <body>${htmlContent}</body>
    </html>
  `);
  printWindow.document.close();
  // Small delay to let content render, then trigger print dialog
  setTimeout(() => {
    printWindow.print();
  }, 400);
}

// ─── Legal Package (ZIP-like — multi-file HTML bundle) ───────────────────────

export function generateLegalPackage(data: {
  projectName: string;
  dateRange: string;
  items: { type: string; label: string; count: number }[];
  complianceScore: number;
}, filename: string): void {
  const html = `
    <h1>Legal Evidence Package</h1>
    <p class="meta">Generated by Axia &bull; ${new Date().toLocaleString()} &bull; Compliance Score: ${data.complianceScore}%</p>
    <h2>Project: ${data.projectName}</h2>
    <p class="meta">Date Range: ${data.dateRange}</p>
    <table>
      <thead>
        <tr><th>Evidence Type</th><th>Label</th><th>Count</th></tr>
      </thead>
      <tbody>
        ${data.items.map((item) => `<tr><td>${item.type}</td><td>${item.label}</td><td>${item.count}</td></tr>`).join('')}
      </tbody>
      <tfoot>
        <tr class="total-row"><td colspan="2">Total Items</td><td>${data.items.reduce((s, i) => s + i.count, 0)}</td></tr>
      </tfoot>
    </table>
    <p style="margin-top:24px;font-size:12px;color:#94a3b8;">This package contains court-admissible evidence with cryptographic proof of authenticity. All timestamps are UTC and verifiable.</p>
  `;
  generatePDF(html, filename);
}

// ─── Invoice PDF ──────────────────────────────────────────────────────────────

export function generateInvoicePDF(invoice: {
  invoiceNumber: string;
  clientName: string;
  projectName: string;
  date: string;
  dueDate: string;
  paidDate?: string;
  status: string;
  platform: string;
  items: { description: string; quantity: number; rate: number; amount: number }[];
  amount: number;
  notes?: string;
}, filename: string): void {
  const statusClass =
    invoice.status === 'paid' ? 'badge-green' :
    invoice.status === 'overdue' ? 'badge-red' :
    'badge-amber';
  const statusLabel = invoice.status.charAt(0).toUpperCase() + invoice.status.slice(1);

  const html = `
    <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:24px;">
      <div>
        <h1 style="margin-bottom:4px;">Invoice ${invoice.invoiceNumber}</h1>
        <p class="meta" style="margin:0;">Platform: ${invoice.platform.charAt(0).toUpperCase() + invoice.platform.slice(1)}</p>
      </div>
      <span class="badge ${statusClass}">${statusLabel}</span>
    </div>
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:24px;">
      <div>
        <p style="font-size:11px;color:#94a3b8;margin-bottom:2px;">Client</p>
        <p style="font-size:14px;font-weight:600;">${invoice.clientName}</p>
      </div>
      <div>
        <p style="font-size:11px;color:#94a3b8;margin-bottom:2px;">Project</p>
        <p style="font-size:14px;font-weight:600;">${invoice.projectName}</p>
      </div>
      <div>
        <p style="font-size:11px;color:#94a3b8;margin-bottom:2px;">Issue Date</p>
        <p style="font-size:14px;">${invoice.date}</p>
      </div>
      <div>
        <p style="font-size:11px;color:#94a3b8;margin-bottom:2px;">Due Date</p>
        <p style="font-size:14px;">${invoice.dueDate}</p>
      </div>
      ${invoice.paidDate ? `<div><p style="font-size:11px;color:#94a3b8;margin-bottom:2px;">Paid Date</p><p style="font-size:14px;">${invoice.paidDate}</p></div>` : ''}
    </div>
    <table>
      <thead>
        <tr><th>Description</th><th style="text-align:right;">Qty</th><th style="text-align:right;">Rate</th><th style="text-align:right;">Amount</th></tr>
      </thead>
      <tbody>
        ${invoice.items.map((item) => `<tr><td>${item.description}</td><td style="text-align:right;">${item.quantity}</td><td style="text-align:right;">$${item.rate.toFixed(2)}</td><td style="text-align:right;">$${item.amount.toFixed(2)}</td></tr>`).join('')}
      </tbody>
      <tfoot>
        <tr class="total-row"><td colspan="3" style="text-align:right;">Total</td><td style="text-align:right;">$${invoice.amount.toFixed(2)}</td></tr>
      </tfoot>
    </table>
    ${invoice.notes ? `<p style="margin-top:16px;font-size:12px;color:#64748b;"><strong>Notes:</strong> ${invoice.notes}</p>` : ''}
    <p style="margin-top:24px;font-size:11px;color:#cbd5e1;">Generated by Axia &bull; ${new Date().toLocaleString()}</p>
  `;
  generatePDF(html, filename);
}

// ─── Payment Patterns CSV ────────────────────────────────────────────────────

export function exportPaymentReport(payments: {
  client: string;
  platform: string;
  amount: number;
  date: string;
  dueDate: string;
  status: string;
  daysLate: number;
  project: string;
}[]): void {
  const headers = ['Client', 'Project', 'Platform', 'Amount', 'Due Date', 'Payment Date', 'Status', 'Days Late'];
  const rows = payments.map((p) => [
    p.client,
    p.project,
    p.platform,
    `$${p.amount.toFixed(2)}`,
    p.dueDate,
    p.date,
    p.status.replace('_', ' '),
    String(p.daysLate),
  ]);
  generateCSV(headers, rows, `payment-report-${new Date().toISOString().slice(0, 10)}`);
}

// ─── Evidence Export ─────────────────────────────────────────────────────────

export function exportEvidence(
  format: 'csv' | 'json' | 'pdf' | 'legal',
  options: {
    evidenceTypes: { id: string; label: string; count: number }[];
    dateRange: string;
    project: string;
    client: string;
    complianceScore: number;
    totalItems: number;
  }
): void {
  const timestamp = new Date().toISOString().slice(0, 10);
  const baseName = `evidence-export-${timestamp}`;

  switch (format) {
    case 'csv': {
      const headers = ['Evidence Type', 'Label', 'Count'];
      const rows = options.evidenceTypes.map((t) => [t.id, t.label, String(t.count)]);
      generateCSV(headers, rows, baseName);
      break;
    }
    case 'json': {
      const payload = {
        exportDate: new Date().toISOString(),
        dateRange: options.dateRange,
        project: options.project,
        client: options.client,
        complianceScore: options.complianceScore,
        totalItems: options.totalItems,
        evidence: options.evidenceTypes,
      };
      generateJSON(payload, baseName);
      break;
    }
    case 'pdf': {
      const html = `
        <h1>Evidence Export Report</h1>
        <p class="meta">Generated by Axia &bull; ${new Date().toLocaleString()} &bull; Compliance: ${options.complianceScore}%</p>
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:20px;">
          <div><p style="font-size:11px;color:#94a3b8;">Date Range</p><p style="font-size:14px;font-weight:600;">${options.dateRange}</p></div>
          <div><p style="font-size:11px;color:#94a3b8;">Project</p><p style="font-size:14px;font-weight:600;">${options.project}</p></div>
          <div><p style="font-size:11px;color:#94a3b8;">Client</p><p style="font-size:14px;font-weight:600;">${options.client}</p></div>
          <div><p style="font-size:11px;color:#94a3b8;">Total Items</p><p style="font-size:14px;font-weight:600;">${options.totalItems}</p></div>
        </div>
        <table>
          <thead><tr><th>Evidence Type</th><th>Label</th><th>Count</th></tr></thead>
          <tbody>${options.evidenceTypes.map((t) => `<tr><td>${t.id}</td><td>${t.label}</td><td>${t.count}</td></tr>`).join('')}</tbody>
        </table>
      `;
      generatePDF(html, baseName);
      break;
    }
    case 'legal': {
      generateLegalPackage(
        {
          projectName: options.project,
          dateRange: options.dateRange,
          items: options.evidenceTypes.map((t) => ({ type: t.id, label: t.label, count: t.count })),
          complianceScore: options.complianceScore,
        },
        baseName
      );
      break;
    }
  }
}

// ─── Internal ─────────────────────────────────────────────────────────────────

function downloadBlob(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
