/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as accountSettings from "../accountSettings.js";
import type * as adminGrants from "../adminGrants.js";
import type * as adminListAll from "../adminListAll.js";
import type * as adminSeed from "../adminSeed.js";
import type * as ai_disputePrediction from "../ai/disputePrediction.js";
import type * as ai_disputePredictionNode from "../ai/disputePredictionNode.js";
import type * as audit_storeConsentAudit from "../audit/storeConsentAudit.js";
import type * as auth from "../auth.js";
import type * as auth_emailOtp from "../auth/emailOtp.js";
import type * as autoSeed from "../autoSeed.js";
import type * as billing_bulkImport from "../billing/bulkImport.js";
import type * as billing_crud from "../billing/crud.js";
import type * as billing_reminders from "../billing/reminders.js";
import type * as clientAuth from "../clientAuth.js";
import type * as clients from "../clients.js";
import type * as clients_bulkImport from "../clients/bulkImport.js";
import type * as clients_clientAuth from "../clients/clientAuth.js";
import type * as clients_clientDisputeSimulation from "../clients/clientDisputeSimulation.js";
import type * as clients_clientGapPrediction from "../clients/clientGapPrediction.js";
import type * as clients_clientPolicyProfile from "../clients/clientPolicyProfile.js";
import type * as clients_clientPortal from "../clients/clientPortal.js";
import type * as clients_clientProtection from "../clients/clientProtection.js";
import type * as clients_clientProtectionScore from "../clients/clientProtectionScore.js";
import type * as clients_clientProtectionSimple from "../clients/clientProtectionSimple.js";
import type * as clients_clientTrustScore from "../clients/clientTrustScore.js";
import type * as clients_clientWorkspace from "../clients/clientWorkspace.js";
import type * as clients_crud from "../clients/crud.js";
import type * as clients_freelancerDirectory from "../clients/freelancerDirectory.js";
import type * as clients_verificationRequests from "../clients/verificationRequests.js";
import type * as complianceAlerts from "../complianceAlerts.js";
import type * as crons from "../crons.js";
import type * as customFields_crud from "../customFields/crud.js";
import type * as customFields_validate from "../customFields/validate.js";
import type * as deals from "../deals.js";
import type * as debug from "../debug.js";
import type * as disputeReports from "../disputeReports.js";
import type * as email from "../email.js";
import type * as emails_components_BaseEmail from "../emails/components/BaseEmail.js";
import type * as emails_magicLink from "../emails/magicLink.js";
import type * as emails_resetPassword from "../emails/resetPassword.js";
import type * as emails_verifyEmail from "../emails/verifyEmail.js";
import type * as emails_verifyOTP from "../emails/verifyOTP.js";
import type * as evidence from "../evidence.js";
import type * as evidence_analytics from "../evidence/analytics.js";
import type * as evidence_extension from "../evidence/extension.js";
import type * as evidence_library from "../evidence/library.js";
import type * as extension from "../extension.js";
import type * as extensionRotate from "../extensionRotate.js";
import type * as goals_crud from "../goals/crud.js";
import type * as http from "../http.js";
import type * as invoices from "../invoices.js";
import type * as leads from "../leads.js";
import type * as legal_consent from "../legal/consent.js";
import type * as lib_auth from "../lib/auth.js";
import type * as lib_email from "../lib/email.js";
import type * as lib_emailTemplates from "../lib/emailTemplates.js";
import type * as lib_paymentProvider from "../lib/paymentProvider.js";
import type * as lib_paymentProviders_creem from "../lib/paymentProviders/creem.js";
import type * as lib_paymentProviders_mock from "../lib/paymentProviders/mock.js";
import type * as lib_paymentProviders_paddle from "../lib/paymentProviders/paddle.js";
import type * as lib_paymentProviders_razorpay from "../lib/paymentProviders/razorpay.js";
import type * as lib_paymentProviders_stripe from "../lib/paymentProviders/stripe.js";
import type * as lib_portalAuditLog from "../lib/portalAuditLog.js";
import type * as lib_portalAuth from "../lib/portalAuth.js";
import type * as lib_pureCrypto from "../lib/pureCrypto.js";
import type * as lib_scopeCreepDetector from "../lib/scopeCreepDetector.js";
import type * as lib_tiers from "../lib/tiers.js";
import type * as manualSends from "../manualSends.js";
import type * as messaging_channelMutations from "../messaging/channelMutations.js";
import type * as messaging_channels from "../messaging/channels.js";
import type * as messaging_dms from "../messaging/dms.js";
import type * as messaging_helpers from "../messaging/helpers.js";
import type * as messaging_messageMutations from "../messaging/messageMutations.js";
import type * as messaging_messages from "../messaging/messages.js";
import type * as network_premiumNetwork from "../network/premiumNetwork.js";
import type * as notifications from "../notifications.js";
import type * as ownerDashboard_actions from "../ownerDashboard/actions.js";
import type * as ownerDashboard_fetchers from "../ownerDashboard/fetchers.js";
import type * as ownerDashboard_index from "../ownerDashboard/index.js";
import type * as ownerDashboard_lib_audit from "../ownerDashboard/lib/audit.js";
import type * as ownerDashboard_lib_cache from "../ownerDashboard/lib/cache.js";
import type * as ownerDashboard_lib_guard from "../ownerDashboard/lib/guard.js";
import type * as ownerDashboard_lib_paddle from "../ownerDashboard/lib/paddle.js";
import type * as ownerDashboard_lib_posthog from "../ownerDashboard/lib/posthog.js";
import type * as ownerDashboard_lib_sentry from "../ownerDashboard/lib/sentry.js";
import type * as ownerDashboard_lib_vercel from "../ownerDashboard/lib/vercel.js";
import type * as ownerDashboard_mutations from "../ownerDashboard/mutations.js";
import type * as ownerDashboard_queries from "../ownerDashboard/queries.js";
import type * as permissions from "../permissions.js";
import type * as permissions_shareRecord from "../permissions/shareRecord.js";
import type * as permissions_shareRecords from "../permissions/shareRecords.js";
import type * as permissions_transferOwnership from "../permissions/transferOwnership.js";
import type * as pipeline_bulkImport from "../pipeline/bulkImport.js";
import type * as pipeline_crud from "../pipeline/crud.js";
import type * as platforms_complianceStorage from "../platforms/complianceStorage.js";
import type * as platforms_platformAuth from "../platforms/platformAuth.js";
import type * as platforms_platformConnections from "../platforms/platformConnections.js";
import type * as platforms_platformImport from "../platforms/platformImport.js";
import type * as platforms_upworkComplianceCheck from "../platforms/upworkComplianceCheck.js";
import type * as policies_clientPolicies from "../policies/clientPolicies.js";
import type * as portal_changeOrders from "../portal/changeOrders.js";
import type * as portal_deliverables from "../portal/deliverables.js";
import type * as portal_evidence from "../portal/evidence.js";
import type * as portal_files from "../portal/files.js";
import type * as portal_invoices from "../portal/invoices.js";
import type * as portal_messages from "../portal/messages.js";
import type * as portal_milestones from "../portal/milestones.js";
import type * as portal_payments from "../portal/payments.js";
import type * as portal_rateLimit from "../portal/rateLimit.js";
import type * as portal_self from "../portal/self.js";
import type * as portal_tokens from "../portal/tokens.js";
import type * as premium_crossPlatformVerification from "../premium/crossPlatformVerification.js";
import type * as premium_protectionAdvisor from "../premium/protectionAdvisor.js";
import type * as premium_protectionPlans from "../premium/protectionPlans.js";
import type * as premium_teamValidation from "../premium/teamValidation.js";
import type * as projects_adaptiveEvidenceSystem from "../projects/adaptiveEvidenceSystem.js";
import type * as projects_debugProjects from "../projects/debugProjects.js";
import type * as projects_milestoneAlerts from "../projects/milestoneAlerts.js";
import type * as projects_milestoneProtection from "../projects/milestoneProtection.js";
import type * as projects_milestoneProtectionTest from "../projects/milestoneProtectionTest.js";
import type * as projects_milestoneReports from "../projects/milestoneReports.js";
import type * as projects_milestoneSnapshots from "../projects/milestoneSnapshots.js";
import type * as projects_projectHealthDashboard from "../projects/projectHealthDashboard.js";
import type * as projects_projectProtection from "../projects/projectProtection.js";
import type * as projects_projectProtectionScore from "../projects/projectProtectionScore.js";
import type * as projects_projectProtectionSimple from "../projects/projectProtectionSimple.js";
import type * as projects_riskTimeline from "../projects/riskTimeline.js";
import type * as projects_scopeFormalization from "../projects/scopeFormalization.js";
import type * as proposals from "../proposals.js";
import type * as proposals_crud from "../proposals/crud.js";
import type * as protection_protectionValue from "../protection/protectionValue.js";
import type * as protection_protectionValueSimple from "../protection/protectionValueSimple.js";
import type * as scope from "../scope.js";
import type * as scope_crud from "../scope/crud.js";
import type * as security_audit from "../security/audit.js";
import type * as security_consent from "../security/consent.js";
import type * as security_crypto from "../security/crypto.js";
import type * as security_ownerAuth from "../security/ownerAuth.js";
import type * as security_rateLimit from "../security/rateLimit.js";
import type * as security_utils from "../security/utils.js";
import type * as seed from "../seed.js";
import type * as seedNew from "../seedNew.js";
import type * as seedProjects from "../seedProjects.js";
import type * as seedTeamUsers from "../seedTeamUsers.js";
import type * as sharedValidators from "../sharedValidators.js";
import type * as tables_billing from "../tables/billing.js";
import type * as tables_business from "../tables/business.js";
import type * as tables_clients from "../tables/clients.js";
import type * as tables_compliance from "../tables/compliance.js";
import type * as tables_customFields from "../tables/customFields.js";
import type * as tables_evidence from "../tables/evidence.js";
import type * as tables_features from "../tables/features.js";
import type * as tables_goals from "../tables/goals.js";
import type * as tables_leads from "../tables/leads.js";
import type * as tables_legal from "../tables/legal.js";
import type * as tables_manualSends from "../tables/manualSends.js";
import type * as tables_messaging from "../tables/messaging.js";
import type * as tables_notifications from "../tables/notifications.js";
import type * as tables_ownerDashboard from "../tables/ownerDashboard.js";
import type * as tables_pipeline from "../tables/pipeline.js";
import type * as tables_platform from "../tables/platform.js";
import type * as tables_portal from "../tables/portal.js";
import type * as tables_projects from "../tables/projects.js";
import type * as tables_proposals from "../tables/proposals.js";
import type * as tables_scope from "../tables/scope.js";
import type * as tables_security from "../tables/security.js";
import type * as tables_tags from "../tables/tags.js";
import type * as tables_teams from "../tables/teams.js";
import type * as tables_tracking from "../tables/tracking.js";
import type * as tables_users from "../tables/users.js";
import type * as tables_work from "../tables/work.js";
import type * as tables_workspaces from "../tables/workspaces.js";
import type * as tags_crud from "../tags/crud.js";
import type * as teams from "../teams.js";
import type * as teams_crud from "../teams/crud.js";
import type * as tiers_tierDetection from "../tiers/tierDetection.js";
import type * as tiers_upgradeTracking from "../tiers/upgradeTracking.js";
import type * as timeBlocks from "../timeBlocks.js";
import type * as tracking_crud from "../tracking/crud.js";
import type * as users from "../users.js";
import type * as waitlist from "../waitlist.js";
import type * as waitlistHelpers from "../waitlistHelpers.js";
import type * as wcvm_contextScanner from "../wcvm/contextScanner.js";
import type * as workSessions from "../workSessions.js";
import type * as workspaceFilter from "../workspaceFilter.js";
import type * as workspaces_crud from "../workspaces/crud.js";
import type * as workspaces_invitations from "../workspaces/invitations.js";
import type * as workspaces_members from "../workspaces/members.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  accountSettings: typeof accountSettings;
  adminGrants: typeof adminGrants;
  adminListAll: typeof adminListAll;
  adminSeed: typeof adminSeed;
  "ai/disputePrediction": typeof ai_disputePrediction;
  "ai/disputePredictionNode": typeof ai_disputePredictionNode;
  "audit/storeConsentAudit": typeof audit_storeConsentAudit;
  auth: typeof auth;
  "auth/emailOtp": typeof auth_emailOtp;
  autoSeed: typeof autoSeed;
  "billing/bulkImport": typeof billing_bulkImport;
  "billing/crud": typeof billing_crud;
  "billing/reminders": typeof billing_reminders;
  clientAuth: typeof clientAuth;
  clients: typeof clients;
  "clients/bulkImport": typeof clients_bulkImport;
  "clients/clientAuth": typeof clients_clientAuth;
  "clients/clientDisputeSimulation": typeof clients_clientDisputeSimulation;
  "clients/clientGapPrediction": typeof clients_clientGapPrediction;
  "clients/clientPolicyProfile": typeof clients_clientPolicyProfile;
  "clients/clientPortal": typeof clients_clientPortal;
  "clients/clientProtection": typeof clients_clientProtection;
  "clients/clientProtectionScore": typeof clients_clientProtectionScore;
  "clients/clientProtectionSimple": typeof clients_clientProtectionSimple;
  "clients/clientTrustScore": typeof clients_clientTrustScore;
  "clients/clientWorkspace": typeof clients_clientWorkspace;
  "clients/crud": typeof clients_crud;
  "clients/freelancerDirectory": typeof clients_freelancerDirectory;
  "clients/verificationRequests": typeof clients_verificationRequests;
  complianceAlerts: typeof complianceAlerts;
  crons: typeof crons;
  "customFields/crud": typeof customFields_crud;
  "customFields/validate": typeof customFields_validate;
  deals: typeof deals;
  debug: typeof debug;
  disputeReports: typeof disputeReports;
  email: typeof email;
  "emails/components/BaseEmail": typeof emails_components_BaseEmail;
  "emails/magicLink": typeof emails_magicLink;
  "emails/resetPassword": typeof emails_resetPassword;
  "emails/verifyEmail": typeof emails_verifyEmail;
  "emails/verifyOTP": typeof emails_verifyOTP;
  evidence: typeof evidence;
  "evidence/analytics": typeof evidence_analytics;
  "evidence/extension": typeof evidence_extension;
  "evidence/library": typeof evidence_library;
  extension: typeof extension;
  extensionRotate: typeof extensionRotate;
  "goals/crud": typeof goals_crud;
  http: typeof http;
  invoices: typeof invoices;
  leads: typeof leads;
  "legal/consent": typeof legal_consent;
  "lib/auth": typeof lib_auth;
  "lib/email": typeof lib_email;
  "lib/emailTemplates": typeof lib_emailTemplates;
  "lib/paymentProvider": typeof lib_paymentProvider;
  "lib/paymentProviders/creem": typeof lib_paymentProviders_creem;
  "lib/paymentProviders/mock": typeof lib_paymentProviders_mock;
  "lib/paymentProviders/paddle": typeof lib_paymentProviders_paddle;
  "lib/paymentProviders/razorpay": typeof lib_paymentProviders_razorpay;
  "lib/paymentProviders/stripe": typeof lib_paymentProviders_stripe;
  "lib/portalAuditLog": typeof lib_portalAuditLog;
  "lib/portalAuth": typeof lib_portalAuth;
  "lib/pureCrypto": typeof lib_pureCrypto;
  "lib/scopeCreepDetector": typeof lib_scopeCreepDetector;
  "lib/tiers": typeof lib_tiers;
  manualSends: typeof manualSends;
  "messaging/channelMutations": typeof messaging_channelMutations;
  "messaging/channels": typeof messaging_channels;
  "messaging/dms": typeof messaging_dms;
  "messaging/helpers": typeof messaging_helpers;
  "messaging/messageMutations": typeof messaging_messageMutations;
  "messaging/messages": typeof messaging_messages;
  "network/premiumNetwork": typeof network_premiumNetwork;
  notifications: typeof notifications;
  "ownerDashboard/actions": typeof ownerDashboard_actions;
  "ownerDashboard/fetchers": typeof ownerDashboard_fetchers;
  "ownerDashboard/index": typeof ownerDashboard_index;
  "ownerDashboard/lib/audit": typeof ownerDashboard_lib_audit;
  "ownerDashboard/lib/cache": typeof ownerDashboard_lib_cache;
  "ownerDashboard/lib/guard": typeof ownerDashboard_lib_guard;
  "ownerDashboard/lib/paddle": typeof ownerDashboard_lib_paddle;
  "ownerDashboard/lib/posthog": typeof ownerDashboard_lib_posthog;
  "ownerDashboard/lib/sentry": typeof ownerDashboard_lib_sentry;
  "ownerDashboard/lib/vercel": typeof ownerDashboard_lib_vercel;
  "ownerDashboard/mutations": typeof ownerDashboard_mutations;
  "ownerDashboard/queries": typeof ownerDashboard_queries;
  permissions: typeof permissions;
  "permissions/shareRecord": typeof permissions_shareRecord;
  "permissions/shareRecords": typeof permissions_shareRecords;
  "permissions/transferOwnership": typeof permissions_transferOwnership;
  "pipeline/bulkImport": typeof pipeline_bulkImport;
  "pipeline/crud": typeof pipeline_crud;
  "platforms/complianceStorage": typeof platforms_complianceStorage;
  "platforms/platformAuth": typeof platforms_platformAuth;
  "platforms/platformConnections": typeof platforms_platformConnections;
  "platforms/platformImport": typeof platforms_platformImport;
  "platforms/upworkComplianceCheck": typeof platforms_upworkComplianceCheck;
  "policies/clientPolicies": typeof policies_clientPolicies;
  "portal/changeOrders": typeof portal_changeOrders;
  "portal/deliverables": typeof portal_deliverables;
  "portal/evidence": typeof portal_evidence;
  "portal/files": typeof portal_files;
  "portal/invoices": typeof portal_invoices;
  "portal/messages": typeof portal_messages;
  "portal/milestones": typeof portal_milestones;
  "portal/payments": typeof portal_payments;
  "portal/rateLimit": typeof portal_rateLimit;
  "portal/self": typeof portal_self;
  "portal/tokens": typeof portal_tokens;
  "premium/crossPlatformVerification": typeof premium_crossPlatformVerification;
  "premium/protectionAdvisor": typeof premium_protectionAdvisor;
  "premium/protectionPlans": typeof premium_protectionPlans;
  "premium/teamValidation": typeof premium_teamValidation;
  "projects/adaptiveEvidenceSystem": typeof projects_adaptiveEvidenceSystem;
  "projects/debugProjects": typeof projects_debugProjects;
  "projects/milestoneAlerts": typeof projects_milestoneAlerts;
  "projects/milestoneProtection": typeof projects_milestoneProtection;
  "projects/milestoneProtectionTest": typeof projects_milestoneProtectionTest;
  "projects/milestoneReports": typeof projects_milestoneReports;
  "projects/milestoneSnapshots": typeof projects_milestoneSnapshots;
  "projects/projectHealthDashboard": typeof projects_projectHealthDashboard;
  "projects/projectProtection": typeof projects_projectProtection;
  "projects/projectProtectionScore": typeof projects_projectProtectionScore;
  "projects/projectProtectionSimple": typeof projects_projectProtectionSimple;
  "projects/riskTimeline": typeof projects_riskTimeline;
  "projects/scopeFormalization": typeof projects_scopeFormalization;
  proposals: typeof proposals;
  "proposals/crud": typeof proposals_crud;
  "protection/protectionValue": typeof protection_protectionValue;
  "protection/protectionValueSimple": typeof protection_protectionValueSimple;
  scope: typeof scope;
  "scope/crud": typeof scope_crud;
  "security/audit": typeof security_audit;
  "security/consent": typeof security_consent;
  "security/crypto": typeof security_crypto;
  "security/ownerAuth": typeof security_ownerAuth;
  "security/rateLimit": typeof security_rateLimit;
  "security/utils": typeof security_utils;
  seed: typeof seed;
  seedNew: typeof seedNew;
  seedProjects: typeof seedProjects;
  seedTeamUsers: typeof seedTeamUsers;
  sharedValidators: typeof sharedValidators;
  "tables/billing": typeof tables_billing;
  "tables/business": typeof tables_business;
  "tables/clients": typeof tables_clients;
  "tables/compliance": typeof tables_compliance;
  "tables/customFields": typeof tables_customFields;
  "tables/evidence": typeof tables_evidence;
  "tables/features": typeof tables_features;
  "tables/goals": typeof tables_goals;
  "tables/leads": typeof tables_leads;
  "tables/legal": typeof tables_legal;
  "tables/manualSends": typeof tables_manualSends;
  "tables/messaging": typeof tables_messaging;
  "tables/notifications": typeof tables_notifications;
  "tables/ownerDashboard": typeof tables_ownerDashboard;
  "tables/pipeline": typeof tables_pipeline;
  "tables/platform": typeof tables_platform;
  "tables/portal": typeof tables_portal;
  "tables/projects": typeof tables_projects;
  "tables/proposals": typeof tables_proposals;
  "tables/scope": typeof tables_scope;
  "tables/security": typeof tables_security;
  "tables/tags": typeof tables_tags;
  "tables/teams": typeof tables_teams;
  "tables/tracking": typeof tables_tracking;
  "tables/users": typeof tables_users;
  "tables/work": typeof tables_work;
  "tables/workspaces": typeof tables_workspaces;
  "tags/crud": typeof tags_crud;
  teams: typeof teams;
  "teams/crud": typeof teams_crud;
  "tiers/tierDetection": typeof tiers_tierDetection;
  "tiers/upgradeTracking": typeof tiers_upgradeTracking;
  timeBlocks: typeof timeBlocks;
  "tracking/crud": typeof tracking_crud;
  users: typeof users;
  waitlist: typeof waitlist;
  waitlistHelpers: typeof waitlistHelpers;
  "wcvm/contextScanner": typeof wcvm_contextScanner;
  workSessions: typeof workSessions;
  workspaceFilter: typeof workspaceFilter;
  "workspaces/crud": typeof workspaces_crud;
  "workspaces/invitations": typeof workspaces_invitations;
  "workspaces/members": typeof workspaces_members;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  betterAuth: import("@convex-dev/better-auth/_generated/component.js").ComponentApi<"betterAuth">;
  resend: import("@convex-dev/resend/_generated/component.js").ComponentApi<"resend">;
};
