/**
 * ClientWorkspace — Shareable, no-login client portal
 *
 * URL: /workspace/:token
 * The token is generated by the agency and shared with the client.
 * The client sees ONLY their own projects, proposals, invoices, and team.
 */
import { useState, useEffect } from "react";
import { useParams } from "react-router";
import { useQuery, useMutation } from "@/lib/safe-convex-react";
import { api } from "@/convex/_generated/api";
import {
  ArrowLeft,
  FolderKanban,
  FileText,
  Receipt,
  Users,
  CheckCircle2,
  Clock,
  AlertTriangle,
  Eye,
  Shield,
  ChevronRight,
  Copy,
  Check,
  ExternalLink,
  CircleDot,
  CircleCheck,
  Circle,
  Timer,
} from "lucide-react";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface ProjectData {
  _id: string;
  projectName: string;
  projectType: string;
  status: string;
  hourlyRate: number;
  completionPct: number;
  totalDeliverables: number;
  completedDeliverables: number;
  teamMembers: { name: string; email: string; role: string; title: string }[];
  lastActivity: number;
  createdAt: number;
  milestones: { name: string; status: string }[];
}

interface ProposalData {
  _id: string;
  title: string;
  status: string;
  totalValue: number;
  currency: string;
  publicToken: string;
  createdAt: number;
  sentAt?: number;
  viewedAt?: number;
  signedAt?: number;
  validUntil?: number;
  sections: any[];
}

interface InvoiceData {
  _id: string;
  invoiceNumber: string;
  status: string;
  issueDate: number;
  dueDate: number;
  paidDate?: number;
  clientName?: string;
  lineItems: any[];
  subtotal: number;
  taxRate?: number;
  taxAmount?: number;
  total: number;
  currency: string;
  notes?: string;
  proofCount?: number;
  hasValidatedBilling?: boolean;
  workProofs: any[];
  createdAt: number;
}

interface TeamMember {
  name: string;
  email: string;
  role: string;
  title: string;
  projects: string[];
}

// ---------------------------------------------------------------------------
// Demo Data (used when token starts with "demo-")
// ---------------------------------------------------------------------------

const DEMO_PROJECTS: ProjectData[] = [
  {
    _id: "demo_proj_1",
    projectName: "TechCorp Website Redesign",
    projectType: "fixed",
    status: "active",
    hourlyRate: 85,
    completionPct: 68,
    totalDeliverables: 12,
    completedDeliverables: 8,
    lastActivity: Date.now() - 2 * 60 * 60 * 1000,
    createdAt: Date.now() - 60 * 24 * 60 * 60 * 1000,
    teamMembers: [
      { name: "Alex Rivera", email: "alex@axiaagency.com", role: "owner", title: "Creative Director" },
      { name: "Sam Chen", email: "sam@axiaagency.com", role: "member", title: "Full-Stack Developer" },
      { name: "Elena Volkov", email: "elena@axiaagency.com", role: "member", title: "UI/UX Designer" },
    ],
    milestones: [
      { name: "Discovery & Research", status: "completed" },
      { name: "Wireframes & Architecture", status: "completed" },
      { name: "UI Design System", status: "completed" },
      { name: "Frontend Development", status: "in_progress" },
      { name: "Backend Integration", status: "pending" },
      { name: "QA & Launch", status: "pending" },
    ],
  },
  {
    _id: "demo_proj_2",
    projectName: "Mobile App MVP",
    projectType: "milestone",
    status: "active",
    hourlyRate: 65,
    completionPct: 42,
    totalDeliverables: 10,
    completedDeliverables: 4,
    lastActivity: Date.now() - 15 * 60 * 1000,
    createdAt: Date.now() - 45 * 24 * 60 * 60 * 1000,
    teamMembers: [
      { name: "Priya Sharma", email: "priya@axiaagency.com", role: "manager", title: "Project Manager" },
      { name: "Sam Chen", email: "sam@axiaagency.com", role: "member", title: "Full-Stack Developer" },
    ],
    milestones: [
      { name: "Auth & User System", status: "completed" },
      { name: "Dashboard UI", status: "completed" },
      { name: "Push Notifications", status: "in_progress" },
      { name: "Payment Integration", status: "pending" },
      { name: "App Store Submission", status: "pending" },
    ],
  },
  {
    _id: "demo_proj_3",
    projectName: "Brand Identity Package",
    projectType: "fixed",
    status: "completed",
    hourlyRate: 95,
    completionPct: 100,
    totalDeliverables: 8,
    completedDeliverables: 8,
    lastActivity: Date.now() - 7 * 24 * 60 * 60 * 1000,
    createdAt: Date.now() - 120 * 24 * 60 * 60 * 1000,
    teamMembers: [
      { name: "Alex Rivera", email: "alex@axiaagency.com", role: "owner", title: "Creative Director" },
      { name: "Marcus Thompson", email: "marcus@axiaagency.com", role: "member", title: "Brand Strategist" },
    ],
    milestones: [
      { name: "Brand Discovery", status: "completed" },
      { name: "Logo Concepts", status: "completed" },
      { name: "Color & Typography", status: "completed" },
      { name: "Brand Guidelines", status: "completed" },
    ],
  },
];

const DEMO_PROPOSALS: ProposalData[] = [
  {
    _id: "demo_prop_1",
    title: "E-Commerce Platform Build",
    status: "sent",
    totalValue: 12000,
    currency: "USD",
    publicToken: "demo-prop-token-1",
    createdAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
    sentAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
    validUntil: Date.now() + 25 * 24 * 60 * 60 * 1000,
    sections: [
      { type: "heading", content: "Project Overview" },
      { type: "text", content: "A full-featured e-commerce platform with product catalog, shopping cart, checkout flow, and admin dashboard. Built with modern technologies for scalability and performance." },
      { type: "milestone", content: "Phase 1: Core Platform — $5,000" },
      { type: "milestone", content: "Phase 2: Payment & Checkout — $3,500" },
      { type: "milestone", content: "Phase 3: Admin Dashboard & Launch — $3,500" },
      { type: "terms", content: "Payment due upon completion of each milestone. 30-day warranty on all deliverables." },
    ],
  },
  {
    _id: "demo_prop_2",
    title: "Mobile Banking App — Full Development",
    status: "viewed",
    totalValue: 25000,
    currency: "USD",
    publicToken: "demo-prop-token-2",
    createdAt: Date.now() - 20 * 24 * 60 * 60 * 1000,
    sentAt: Date.now() - 15 * 24 * 60 * 60 * 1000,
    validUntil: Date.now() + 15 * 24 * 60 * 60 * 1000,
    sections: [
      { type: "heading", content: "Executive Summary" },
      { type: "text", content: "Full-featured mobile banking application with biometric authentication, real-time transactions, and compliance reporting. Designed for security-first financial services." },
      { type: "pricing", content: "Total Investment: $25,000 (estimated 12-week timeline)" },
      { type: "terms", content: "Net-15 payment terms. 60-day post-launch support included." },
    ],
  },
];

const DEMO_INVOICES: InvoiceData[] = [
  {
    _id: "demo_inv_1",
    invoiceNumber: "INV-2024-001",
    status: "paid",
    issueDate: Date.now() - 60 * 24 * 60 * 60 * 1000,
    dueDate: Date.now() - 30 * 24 * 60 * 60 * 1000,
    paidDate: Date.now() - 25 * 24 * 60 * 60 * 1000,
    clientName: "TechCorp Solutions",
    lineItems: [
      { id: "li_1", description: "Website Redesign — Phase 1: Discovery & Wireframes", quantity: 20, rate: 85, amount: 1700, hasProof: true },
      { id: "li_2", description: "Website Redesign — Phase 2: UI Design", quantity: 25, rate: 85, amount: 2125, hasProof: true },
    ],
    subtotal: 3825,
    taxRate: 0,
    taxAmount: 0,
    total: 3825,
    currency: "USD",
    notes: "Net-30 terms. Payment received on time.",
    proofCount: 8,
    hasValidatedBilling: true,
    workProofs: [
      { _id: "wp_1", proofType: "time_session", title: "Discovery Workshop", description: "4.5h discovery session with stakeholders", hours: 4.5, date: Date.now() - 58 * 24 * 60 * 60 * 1000, value: 382.5, verified: true },
      { _id: "wp_2", proofType: "time_session", title: "Wireframe Design", description: "8h wireframe creation and review", hours: 8, date: Date.now() - 50 * 24 * 60 * 60 * 1000, value: 680, verified: true },
    ],
    createdAt: Date.now() - 60 * 24 * 60 * 60 * 1000,
  },
  {
    _id: "demo_inv_2",
    invoiceNumber: "INV-2024-003",
    status: "sent",
    issueDate: Date.now() - 7 * 24 * 60 * 60 * 1000,
    dueDate: Date.now() + 23 * 24 * 60 * 60 * 1000,
    clientName: "StartupHub Inc",
    lineItems: [
      { id: "li_5", description: "Mobile App MVP — Sprint 1: Auth & Dashboard", quantity: 30, rate: 65, amount: 1950, hasProof: true },
    ],
    subtotal: 1950,
    taxRate: 0,
    taxAmount: 0,
    total: 1950,
    currency: "USD",
    proofCount: 4,
    hasValidatedBilling: true,
    workProofs: [
      { _id: "wp_3", proofType: "time_session", title: "Sprint 1 Development", description: "Authentication system and dashboard UI", hours: 30, date: Date.now() - 10 * 24 * 60 * 60 * 1000, value: 1950, verified: true },
    ],
    createdAt: Date.now() - 7 * 24 * 60 * 60 * 1000,
  },
  {
    _id: "demo_inv_3",
    invoiceNumber: "INV-2024-005",
    status: "overdue",
    issueDate: Date.now() - 45 * 24 * 60 * 60 * 1000,
    dueDate: Date.now() - 15 * 24 * 60 * 60 * 1000,
    clientName: "Global Enterprises",
    lineItems: [
      { id: "li_3", description: "Data Dashboard — Backend Architecture", quantity: 40, rate: 120, amount: 4800, hasProof: true },
      { id: "li_4", description: "Data Dashboard — Frontend Components", quantity: 30, rate: 120, amount: 3600, hasProof: false },
    ],
    subtotal: 8400,
    taxRate: 0,
    taxAmount: 0,
    total: 8400,
    currency: "USD",
    notes: "Payment 15 days overdue. Follow-up sent.",
    proofCount: 3,
    hasValidatedBilling: false,
    workProofs: [
      { _id: "wp_4", proofType: "time_session", title: "Backend API Development", description: "RESTful API endpoints and database schema", hours: 40, date: Date.now() - 40 * 24 * 60 * 60 * 1000, value: 4800, verified: true },
    ],
    createdAt: Date.now() - 45 * 24 * 60 * 60 * 1000,
  },
];

const DEMO_TEAM: TeamMember[] = [
  { name: "Alex Rivera", email: "alex@axiaagency.com", role: "owner", title: "Creative Director", projects: ["TechCorp Website Redesign", "Brand Identity Package"] },
  { name: "Priya Sharma", email: "priya@axiaagency.com", role: "manager", title: "Project Manager", projects: ["Mobile App MVP"] },
  { name: "Sam Chen", email: "sam@axiaagency.com", role: "member", title: "Full-Stack Developer", projects: ["TechCorp Website Redesign", "Mobile App MVP"] },
  { name: "Elena Volkov", email: "elena@axiaagency.com", role: "member", title: "UI/UX Designer", projects: ["TechCorp Website Redesign"] },
  { name: "Marcus Thompson", email: "marcus@axiaagency.com", role: "member", title: "Brand Strategist", projects: ["Brand Identity Package"] },
];

// ---------------------------------------------------------------------------
// Status Configs
// ---------------------------------------------------------------------------

const PROPOSAL_STATUS: Record<string, { label: string; color: string; bg: string }> = {
  draft: { label: "Draft", color: "text-gray-500", bg: "bg-gray-100 dark:bg-gray-800" },
  sent: { label: "Sent", color: "text-blue-600", bg: "bg-blue-50 dark:bg-blue-900/30" },
  viewed: { label: "Viewed", color: "text-indigo-600", bg: "bg-indigo-50 dark:bg-indigo-900/30" },
  signed: { label: "Signed", color: "text-green-600", bg: "bg-green-50 dark:bg-green-900/30" },
  declined: { label: "Declined", color: "text-red-600", bg: "bg-red-50 dark:bg-red-900/30" },
  expired: { label: "Expired", color: "text-orange-600", bg: "bg-orange-50 dark:bg-orange-900/30" },
};

const INVOICE_STATUS: Record<string, { label: string; color: string; bg: string }> = {
  draft: { label: "Draft", color: "text-gray-500", bg: "bg-gray-100 dark:bg-gray-800" },
  sent: { label: "Sent", color: "text-blue-600", bg: "bg-blue-50 dark:bg-blue-900/30" },
  viewed: { label: "Viewed", color: "text-indigo-600", bg: "bg-indigo-50 dark:bg-indigo-900/30" },
  paid: { label: "Paid", color: "text-green-600", bg: "bg-green-50 dark:bg-green-900/30" },
  partial: { label: "Partial", color: "text-yellow-600", bg: "bg-yellow-50 dark:bg-yellow-900/30" },
  overdue: { label: "Overdue", color: "text-red-600", bg: "bg-red-50 dark:bg-red-900/30" },
  cancelled: { label: "Cancelled", color: "text-gray-400", bg: "bg-gray-50 dark:bg-gray-900/30" },
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function formatDate(ts: number | undefined) {
  if (!ts) return "—";
  return new Date(ts).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

function formatCurrency(amount: number, currency = "USD") {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency,
    minimumFractionDigits: 0,
    maximumFractionDigits: 2,
  }).format(amount);
}

function relativeTime(ts: number | undefined) {
  if (!ts) return "Never";
  const diff = Date.now() - ts;
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return "Just now";
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  if (days < 30) return `${days}d ago`;
  return formatDate(ts);
}

function getInitials(name: string) {
  return name
    .split(" ")
    .map((w) => w[0])
    .join("")
    .toUpperCase()
    .slice(0, 2);
}

function getAvatarColor(name: string) {
  const colors = [
    "bg-violet-500",
    "bg-blue-500",
    "bg-emerald-500",
    "bg-amber-500",
    "bg-rose-500",
    "bg-cyan-500",
    "bg-pink-500",
    "bg-teal-500",
  ];
  let hash = 0;
  for (let i = 0; i < name.length; i++) hash = name.charCodeAt(i) + ((hash << 5) - hash);
  return colors[Math.abs(hash) % colors.length];
}

// ---------------------------------------------------------------------------
// Main Component
// ---------------------------------------------------------------------------

export default function ClientWorkspace() {
  const { token } = useParams<{ token: string }>();
  const [activeTab, setActiveTab] = useState<"projects" | "proposals" | "invoices" | "team">("projects");
  const [expandedProject, setExpandedProject] = useState<string | null>(null);
  const [expandedInvoice, setExpandedInvoice] = useState<string | null>(null);
  const [expandedProposal, setExpandedProposal] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  // Check if this is a demo token
  const isDemo = token?.startsWith("demo-") ?? false;

  // Validate token (skip for demo tokens)
  const validation = useQuery(
    api.clients.clientWorkspace.validateWorkspaceToken,
    (!isDemo && token) ? { token } : "skip"
  );

  // Fetch data (only if token is valid OR if demo)
  const shouldFetch = isDemo || validation?.valid;

  const projects = useQuery(
    api.clients.clientWorkspace.getClientProjects,
    shouldFetch && !isDemo ? { token: token! } : "skip"
  ) as ProjectData[] | undefined;

  const proposals = useQuery(
    api.clients.clientWorkspace.getClientProposals,
    shouldFetch && !isDemo ? { token: token! } : "skip"
  ) as ProposalData[] | undefined;

  const invoices = useQuery(
    api.clients.clientWorkspace.getClientInvoices,
    shouldFetch && !isDemo ? { token: token! } : "skip"
  ) as InvoiceData[] | undefined;

  const team = useQuery(
    api.clients.clientWorkspace.getClientTeamMembers,
    shouldFetch && !isDemo ? { token: token! } : "skip"
  ) as TeamMember[] | undefined;

  // For demo mode, use static mock data
  const effectiveProjects = isDemo ? DEMO_PROJECTS : projects;
  const effectiveProposals = isDemo ? DEMO_PROPOSALS : proposals;
  const effectiveInvoices = isDemo ? DEMO_INVOICES : invoices;
  const effectiveTeam = isDemo ? DEMO_TEAM : team;

  // Record access (only for real tokens)
  const recordAccess = useMutation(api.clients.clientWorkspace.recordWorkspaceAccess);
  useEffect(() => {
    if (!isDemo && validation?.valid && token) {
      recordAccess({ token });
    }
  }, [isDemo, validation?.valid, token]);

  // Mark proposals/invoices as viewed (only for real tokens)
  const markProposalViewed = useMutation(api.clients.clientWorkspace.markProposalViewedByClient);
  const markInvoiceViewed = useMutation(api.clients.clientWorkspace.markInvoiceViewedByClient);

  useEffect(() => {
    if (!isDemo && proposals) {
      proposals.forEach((p) => {
        if (p.status === "sent") {
          markProposalViewed({ proposalId: p._id as any });
        }
      });
    }
  }, [proposals]);

  useEffect(() => {
    if (!isDemo && invoices) {
      invoices.forEach((inv) => {
        if (inv.status === "sent") {
          markInvoiceViewed({ invoiceId: inv._id as any });
        }
      });
    }
  }, [invoices]);

  const copyLink = () => {
    const url = `${window.location.origin}/workspace/${token}`;
    navigator.clipboard.writeText(url);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // ---- Loading & Error States ----

  // Demo tokens are always valid
  if (!isDemo && validation === undefined) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-50 to-violet-50 dark:from-gray-950 dark:to-gray-900 flex items-center justify-center">
        <div className="flex flex-col items-center gap-4">
          <div className="w-10 h-10 border-3 border-violet-500 border-t-transparent rounded-full animate-spin" />
          <p className="text-gray-500 dark:text-gray-400 text-sm">Loading workspace...</p>
        </div>
      </div>
    );
  }

  if (!isDemo && !validation?.valid) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-50 to-violet-50 dark:from-gray-950 dark:to-gray-900 flex items-center justify-center p-6">
        <div className="bg-white dark:bg-gray-900 rounded-2xl shadow-xl border border-gray-200 dark:border-gray-800 p-10 max-w-md text-center">
          <div className="w-16 h-16 bg-red-100 dark:bg-red-900/30 rounded-full flex items-center justify-center mx-auto mb-5">
            <AlertTriangle className="w-8 h-8 text-red-500" />
          </div>
          <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-2">
            Invalid or Expired Link
          </h2>
          <p className="text-gray-500 dark:text-gray-400 text-sm mb-6">
            This workspace link is no longer valid. Please contact your agency for a new link.
          </p>
          <a
            href="/"
            className="inline-flex items-center gap-2 px-5 py-2.5 bg-violet-600 text-white rounded-lg text-sm font-medium hover:bg-violet-700 transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Go to Axia
          </a>
        </div>
      </div>
    );
  }

  const clientName = isDemo ? "Demo Client" : validation?.clientName ?? "Client";
  const projectCount = effectiveProjects?.length ?? 0;
  const activeProposals = effectiveProposals?.filter((p) => p.status === "sent" || p.status === "viewed").length ?? 0;
  const outstandingAmount = effectiveInvoices
    ?.filter((i) => i.status !== "paid" && i.status !== "cancelled" && i.status !== "draft")
    .reduce((sum, i) => sum + i.total, 0) ?? 0;

  // ---- Tab Config ----
  const tabs = [
    { id: "projects" as const, label: "Projects", icon: FolderKanban, count: projectCount },
    { id: "proposals" as const, label: "Proposals", icon: FileText, count: effectiveProposals?.length ?? 0 },
    { id: "invoices" as const, label: "Invoices", icon: Receipt, count: effectiveInvoices?.length ?? 0 },
    { id: "team" as const, label: "Team", icon: Users, count: effectiveTeam?.length ?? 0 },
  ];

  // ---- Render ----
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-violet-50 dark:from-gray-950 dark:to-gray-900">
      {/* Demo Banner */}
      {isDemo && (
        <div className="bg-violet-600 text-white text-center py-2 px-4 text-xs font-medium">
          This is a demo preview. Real share links will show live project data from your agency.
        </div>
      )}
      {/* Header */}
      <header className="sticky top-0 z-30 bg-white/80 dark:bg-gray-900/80 backdrop-blur-xl border-b border-gray-200 dark:border-gray-800">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 bg-gradient-to-br from-violet-500 to-purple-600 rounded-lg flex items-center justify-center">
                <Shield className="w-5 h-5 text-white" />
              </div>
              <div>
                <h1 className="text-lg font-bold text-gray-900 dark:text-white">
                  {clientName}
                </h1>
                <p className="text-xs text-gray-500 dark:text-gray-400">
                  Client Workspace{isDemo ? " · Demo Preview" : ""}
                </p>
              </div>
            </div>
            <button
              onClick={copyLink}
              className="flex items-center gap-2 px-3 py-2 text-xs font-medium text-violet-600 dark:text-violet-400 bg-violet-50 dark:bg-violet-900/30 rounded-lg hover:bg-violet-100 dark:hover:bg-violet-900/50 transition-colors"
            >
              {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? "Copied!" : "Copy Link"}
            </button>
          </div>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-4 sm:px-6 py-6">
        {/* Overview Cards */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-8">
          <div className="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 p-4">
            <div className="flex items-center gap-2 mb-2">
              <FolderKanban className="w-4 h-4 text-violet-500" />
              <span className="text-xs font-medium text-gray-500 dark:text-gray-400">Projects</span>
            </div>
            <p className="text-2xl font-bold text-gray-900 dark:text-white">{projectCount}</p>
          </div>
          <div className="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 p-4">
            <div className="flex items-center gap-2 mb-2">
              <FileText className="w-4 h-4 text-blue-500" />
              <span className="text-xs font-medium text-gray-500 dark:text-gray-400">Pending Proposals</span>
            </div>
            <p className="text-2xl font-bold text-gray-900 dark:text-white">{activeProposals}</p>
          </div>
          <div className="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 p-4">
            <div className="flex items-center gap-2 mb-2">
              <Receipt className="w-4 h-4 text-emerald-500" />
              <span className="text-xs font-medium text-gray-500 dark:text-gray-400">Outstanding</span>
            </div>
            <p className="text-2xl font-bold text-gray-900 dark:text-white">
              {formatCurrency(outstandingAmount)}
            </p>
          </div>
          <div className="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 p-4">
            <div className="flex items-center gap-2 mb-2">
              <Users className="w-4 h-4 text-amber-500" />
              <span className="text-xs font-medium text-gray-500 dark:text-gray-400">Team</span>
            </div>
            <p className="text-2xl font-bold text-gray-900 dark:text-white">{effectiveTeam?.length ?? 0}</p>
          </div>
        </div>

        {/* Tabs */}
        <div className="flex gap-1 bg-gray-100 dark:bg-gray-800 rounded-xl p-1 mb-6">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium transition-all flex-1 justify-center ${
                activeTab === tab.id
                  ? "bg-white dark:bg-gray-900 text-gray-900 dark:text-white shadow-sm"
                  : "text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300"
              }`}
            >
              <tab.icon className="w-4 h-4" />
              <span className="hidden sm:inline">{tab.label}</span>
              {tab.count > 0 && (
                <span
                  className={`text-xs px-1.5 py-0.5 rounded-full ${
                    activeTab === tab.id
                      ? "bg-violet-100 dark:bg-violet-900/40 text-violet-600 dark:text-violet-400"
                      : "bg-gray-200 dark:bg-gray-700 text-gray-500 dark:text-gray-400"
                  }`}
                >
                  {tab.count}
                </span>
              )}
            </button>
          ))}
        </div>

        {/* Tab Content */}
        {activeTab === "projects" && <ProjectsTab projects={effectiveProjects} expanded={expandedProject} setExpanded={setExpandedProject} />}
        {activeTab === "proposals" && <ProposalsTab proposals={effectiveProposals} expanded={expandedProposal} setExpanded={setExpandedProposal} />}
        {activeTab === "invoices" && <InvoicesTab invoices={effectiveInvoices} expanded={expandedInvoice} setExpanded={setExpandedInvoice} />}
        {activeTab === "team" && <TeamTab team={effectiveTeam} />}

        {/* Footer */}
        <div className="mt-12 pt-6 border-t border-gray-200 dark:border-gray-800 text-center">
          <p className="text-xs text-gray-400 dark:text-gray-500">
            Powered by <span className="font-semibold text-violet-500">Axia</span> — Professional Protection Platform
          </p>
        </div>
      </main>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Projects Tab
// ---------------------------------------------------------------------------

function ProjectsTab({
  projects,
  expanded,
  setExpanded,
}: {
  projects: ProjectData[] | undefined;
  expanded: string | null;
  setExpanded: (id: string | null) => void;
}) {
  if (projects === undefined) {
    return <LoadingSkeleton />;
  }

  if (projects.length === 0) {
    return <EmptyState icon={FolderKanban} title="No projects yet" description="Your projects will appear here once they are created." />;
  }

  return (
    <div className="space-y-4">
      {projects.map((project) => (
        <div
          key={project._id}
          className="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 overflow-hidden"
        >
          {/* Project Header */}
          <button
            onClick={() => setExpanded(expanded === project._id ? null : project._id)}
            className="w-full px-5 py-4 flex items-center justify-between hover:bg-gray-50 dark:hover:bg-gray-800/50 transition-colors"
          >
            <div className="flex items-center gap-4">
              <div className="w-10 h-10 bg-violet-100 dark:bg-violet-900/30 rounded-lg flex items-center justify-center">
                <FolderKanban className="w-5 h-5 text-violet-500" />
              </div>
              <div className="text-left">
                <h3 className="font-semibold text-gray-900 dark:text-white text-sm">
                  {project.projectName}
                </h3>
                <div className="flex items-center gap-3 mt-0.5">
                  <span className="text-xs text-gray-500 dark:text-gray-400">
                    {project.projectType.charAt(0).toUpperCase() + project.projectType.slice(1)}
                  </span>
                  <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${
                    project.status === "active"
                      ? "bg-green-50 dark:bg-green-900/30 text-green-600 dark:text-green-400"
                      : "bg-gray-100 dark:bg-gray-800 text-gray-500"
                  }`}>
                    {project.status.charAt(0).toUpperCase() + project.status.slice(1)}
                  </span>
                  <span className="text-xs text-gray-400">{formatCurrency(project.hourlyRate)}/hr</span>
                </div>
              </div>
            </div>
            <div className="flex items-center gap-4">
              {/* Progress Ring */}
              <div className="hidden sm:flex items-center gap-2">
                <svg width="36" height="36" viewBox="0 0 36 36" className="transform -rotate-90">
                  <circle cx="18" cy="18" r="14" fill="none" stroke="currentColor" strokeWidth="3" className="text-gray-200 dark:text-gray-700" />
                  <circle
                    cx="18" cy="18" r="14" fill="none" stroke="currentColor" strokeWidth="3"
                    strokeDasharray={`${(project.completionPct / 100) * 88} 88`}
                    className="text-violet-500"
                    strokeLinecap="round"
                  />
                </svg>
                <span className="text-sm font-semibold text-gray-900 dark:text-white">{project.completionPct}%</span>
              </div>
              <ChevronRight
                className={`w-5 h-5 text-gray-400 transition-transform ${
                  expanded === project._id ? "rotate-90" : ""
                }`}
              />
            </div>
          </button>

          {/* Expanded Content */}
          {expanded === project._id && (
            <div className="px-5 pb-5 border-t border-gray-100 dark:border-gray-800">
              {/* Progress Bar */}
              <div className="mt-4 mb-5">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-xs font-medium text-gray-500 dark:text-gray-400">Progress</span>
                  <span className="text-xs text-gray-500 dark:text-gray-400">
                    {project.completedDeliverables}/{project.totalDeliverables} deliverables
                  </span>
                </div>
                <div className="h-2 bg-gray-100 dark:bg-gray-800 rounded-full overflow-hidden">
                  <div
                    className="h-full bg-gradient-to-r from-violet-500 to-purple-500 rounded-full transition-all"
                    style={{ width: `${project.completionPct}%` }}
                  />
                </div>
              </div>

              {/* Milestones */}
              {project.milestones.length > 0 && (
                <div className="mb-5">
                  <h4 className="text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-3">
                    Milestones
                  </h4>
                  <div className="space-y-2">
                    {project.milestones.map((ms, i) => (
                      <div key={i} className="flex items-center gap-3">
                        {ms.status === "completed" || ms.status === "approved" ? (
                          <CircleCheck className="w-4 h-4 text-green-500 shrink-0" />
                        ) : ms.status === "in_progress" ? (
                          <CircleDot className="w-4 h-4 text-violet-500 shrink-0" />
                        ) : (
                          <Circle className="w-4 h-4 text-gray-300 dark:text-gray-600 shrink-0" />
                        )}
                        <span className={`text-sm ${
                          ms.status === "completed" || ms.status === "approved"
                            ? "text-gray-500 dark:text-gray-400 line-through"
                            : "text-gray-900 dark:text-white"
                        }`}>
                          {ms.name}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Team Members on this Project */}
              {project.teamMembers.length > 0 && (
                <div>
                  <h4 className="text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-3">
                    Team Members
                  </h4>
                  <div className="flex flex-wrap gap-2">
                    {project.teamMembers.map((member, i) => (
                      <div
                        key={i}
                        className="flex items-center gap-2 bg-gray-50 dark:bg-gray-800 rounded-lg px-3 py-2"
                      >
                        <div
                          className={`w-7 h-7 ${getAvatarColor(member.name)} rounded-full flex items-center justify-center text-white text-xs font-bold`}
                        >
                          {getInitials(member.name)}
                        </div>
                        <div>
                          <p className="text-xs font-medium text-gray-900 dark:text-white">
                            {member.name}
                          </p>
                          {member.title && (
                            <p className="text-[10px] text-gray-400">{member.title}</p>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Last Activity */}
              <div className="mt-4 pt-3 border-t border-gray-100 dark:border-gray-800 flex items-center gap-2">
                <Clock className="w-3.5 h-3.5 text-gray-400" />
                <span className="text-xs text-gray-400">
                  Last activity: {relativeTime(project.lastActivity)}
                </span>
              </div>
            </div>
          )}
        </div>
      ))}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Proposals Tab
// ---------------------------------------------------------------------------

function ProposalsTab({
  proposals,
  expanded,
  setExpanded,
}: {
  proposals: ProposalData[] | undefined;
  expanded: string | null;
  setExpanded: (id: string | null) => void;
}) {
  if (proposals === undefined) return <LoadingSkeleton />;
  if (proposals.length === 0)
    return <EmptyState icon={FileText} title="No proposals" description="Proposals sent to you will appear here." />;

  return (
    <div className="space-y-4">
      {proposals.map((proposal) => {
        const statusCfg = PROPOSAL_STATUS[proposal.status] ?? PROPOSAL_STATUS.draft;
        return (
          <div
            key={proposal._id}
            className="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 overflow-hidden"
          >
            <button
              onClick={() => setExpanded(expanded === proposal._id ? null : proposal._id)}
              className="w-full px-5 py-4 flex items-center justify-between hover:bg-gray-50 dark:hover:bg-gray-800/50 transition-colors"
            >
              <div className="flex items-center gap-4">
                <div className="w-10 h-10 bg-blue-100 dark:bg-blue-900/30 rounded-lg flex items-center justify-center">
                  <FileText className="w-5 h-5 text-blue-500" />
                </div>
                <div className="text-left">
                  <h3 className="font-semibold text-gray-900 dark:text-white text-sm">
                    {proposal.title}
                  </h3>
                  <div className="flex items-center gap-3 mt-0.5">
                    <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${statusCfg.bg} ${statusCfg.color}`}>
                      {statusCfg.label}
                    </span>
                    <span className="text-xs text-gray-500">{formatCurrency(proposal.totalValue, proposal.currency)}</span>
                    <span className="text-xs text-gray-400">{formatDate(proposal.createdAt)}</span>
                  </div>
                </div>
              </div>
              <ChevronRight
                className={`w-5 h-5 text-gray-400 transition-transform ${expanded === proposal._id ? "rotate-90" : ""}`}
              />
            </button>

            {expanded === proposal._id && (
              <div className="px-5 pb-5 border-t border-gray-100 dark:border-gray-800">
                {/* Proposal Details */}
                <div className="mt-4 grid grid-cols-2 gap-4 mb-4">
                  <div>
                    <p className="text-xs text-gray-400 mb-1">Value</p>
                    <p className="text-lg font-bold text-gray-900 dark:text-white">
                      {formatCurrency(proposal.totalValue, proposal.currency)}
                    </p>
                  </div>
                  <div>
                    <p className="text-xs text-gray-400 mb-1">Status</p>
                    <span className={`inline-flex items-center gap-1.5 text-sm font-medium ${statusCfg.color}`}>
                      {proposal.status === "signed" && <CheckCircle2 className="w-4 h-4" />}
                      {statusCfg.label}
                    </span>
                  </div>
                  {proposal.sentAt && (
                    <div>
                      <p className="text-xs text-gray-400 mb-1">Sent</p>
                      <p className="text-sm text-gray-700 dark:text-gray-300">{formatDate(proposal.sentAt)}</p>
                    </div>
                  )}
                  {proposal.validUntil && (
                    <div>
                      <p className="text-xs text-gray-400 mb-1">Valid Until</p>
                      <p className="text-sm text-gray-700 dark:text-gray-300">{formatDate(proposal.validUntil)}</p>
                    </div>
                  )}
                </div>

                {/* Proposal Sections */}
                {proposal.sections && proposal.sections.length > 0 && (
                  <div>
                    <h4 className="text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-3">
                      Proposal Content
                    </h4>
                    <div className="space-y-3">
                      {proposal.sections.map((section: any, i: number) => (
                        <div key={i}>
                          {section.type === "heading" && (
                            <h5 className="text-sm font-semibold text-gray-900 dark:text-white mt-2">
                              {section.content}
                            </h5>
                          )}
                          {section.type === "text" && (
                            <p className="text-sm text-gray-600 dark:text-gray-300 whitespace-pre-wrap">
                              {section.content}
                            </p>
                          )}
                          {section.type === "pricing" && (
                            <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-3 mt-1">
                              <p className="text-sm font-medium text-gray-900 dark:text-white">
                                {section.content}
                              </p>
                            </div>
                          )}
                          {section.type === "terms" && (
                            <div className="bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-lg p-3 mt-1">
                              <p className="text-sm text-amber-800 dark:text-amber-200 whitespace-pre-wrap">
                                {section.content}
                              </p>
                            </div>
                          )}
                          {section.type === "milestone" && (
                            <div className="flex items-center gap-2 bg-violet-50 dark:bg-violet-900/20 rounded-lg p-3 mt-1">
                              <CircleDot className="w-4 h-4 text-violet-500 shrink-0" />
                              <p className="text-sm text-violet-800 dark:text-violet-200">
                                {section.content}
                              </p>
                            </div>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Invoices Tab
// ---------------------------------------------------------------------------

function InvoicesTab({
  invoices,
  expanded,
  setExpanded,
}: {
  invoices: InvoiceData[] | undefined;
  expanded: string | null;
  setExpanded: (id: string | null) => void;
}) {
  if (invoices === undefined) return <LoadingSkeleton />;
  if (invoices.length === 0)
    return <EmptyState icon={Receipt} title="No invoices" description="Invoices for your projects will appear here." />;

  return (
    <div className="space-y-4">
      {invoices.map((invoice) => {
        const statusCfg = INVOICE_STATUS[invoice.status] ?? INVOICE_STATUS.draft;
        return (
          <div
            key={invoice._id}
            className="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 overflow-hidden"
          >
            <button
              onClick={() => setExpanded(expanded === invoice._id ? null : invoice._id)}
              className="w-full px-5 py-4 flex items-center justify-between hover:bg-gray-50 dark:hover:bg-gray-800/50 transition-colors"
            >
              <div className="flex items-center gap-4">
                <div className="w-10 h-10 bg-emerald-100 dark:bg-emerald-900/30 rounded-lg flex items-center justify-center">
                  <Receipt className="w-5 h-5 text-emerald-500" />
                </div>
                <div className="text-left">
                  <h3 className="font-semibold text-gray-900 dark:text-white text-sm">
                    {invoice.invoiceNumber}
                  </h3>
                  <div className="flex items-center gap-3 mt-0.5">
                    <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${statusCfg.bg} ${statusCfg.color}`}>
                      {statusCfg.label}
                    </span>
                    <span className="text-xs font-semibold text-gray-900 dark:text-white">
                      {formatCurrency(invoice.total, invoice.currency)}
                    </span>
                    {invoice.hasValidatedBilling && (
                      <span className="flex items-center gap-1 text-xs text-green-600 dark:text-green-400">
                        <Shield className="w-3 h-3" />
                        Validated
                      </span>
                    )}
                    <span className="text-xs text-gray-400">Due {formatDate(invoice.dueDate)}</span>
                  </div>
                </div>
              </div>
              <ChevronRight
                className={`w-5 h-5 text-gray-400 transition-transform ${expanded === invoice._id ? "rotate-90" : ""}`}
              />
            </button>

            {expanded === invoice._id && (
              <div className="px-5 pb-5 border-t border-gray-100 dark:border-gray-800">
                {/* Invoice Summary */}
                <div className="mt-4 grid grid-cols-2 sm:grid-cols-4 gap-4 mb-5">
                  <div>
                    <p className="text-xs text-gray-400 mb-1">Issued</p>
                    <p className="text-sm font-medium text-gray-900 dark:text-white">
                      {formatDate(invoice.issueDate)}
                    </p>
                  </div>
                  <div>
                    <p className="text-xs text-gray-400 mb-1">Due</p>
                    <p className="text-sm font-medium text-gray-900 dark:text-white">
                      {formatDate(invoice.dueDate)}
                    </p>
                  </div>
                  <div>
                    <p className="text-xs text-gray-400 mb-1">Total</p>
                    <p className="text-sm font-bold text-gray-900 dark:text-white">
                      {formatCurrency(invoice.total, invoice.currency)}
                    </p>
                  </div>
                  <div>
                    <p className="text-xs text-gray-400 mb-1">Proofs</p>
                    <p className="text-sm font-medium text-gray-900 dark:text-white">
                      {invoice.proofCount ?? invoice.workProofs.length} items
                    </p>
                  </div>
                </div>

                {/* Line Items */}
                <div className="mb-5">
                  <h4 className="text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-3">
                    Line Items
                  </h4>
                  <div className="space-y-2">
                    {invoice.lineItems.map((item: any) => (
                      <div
                        key={item.id}
                        className="flex items-center justify-between py-2 px-3 bg-gray-50 dark:bg-gray-800 rounded-lg"
                      >
                        <div className="flex items-center gap-2">
                          <span className="text-sm text-gray-900 dark:text-white">{item.description}</span>
                          {item.hasProof && (
                            <span className="flex items-center gap-1 text-[10px] text-green-600 dark:text-green-400">
                              <Shield className="w-3 h-3" />
                              Proven
                            </span>
                          )}
                        </div>
                        <div className="flex items-center gap-3 text-xs text-gray-500">
                          <span>{item.quantity} x {formatCurrency(item.rate, invoice.currency)}</span>
                          <span className="font-semibold text-gray-900 dark:text-white">
                            {formatCurrency(item.amount, invoice.currency)}
                          </span>
                        </div>
                      </div>
                    ))}
                  </div>
                  {/* Totals */}
                  <div className="mt-3 pt-3 border-t border-gray-200 dark:border-gray-700 space-y-1">
                    <div className="flex justify-between text-xs text-gray-500">
                      <span>Subtotal</span>
                      <span>{formatCurrency(invoice.subtotal, invoice.currency)}</span>
                    </div>
                    {invoice.taxAmount != null && (
                      <div className="flex justify-between text-xs text-gray-500">
                        <span>Tax ({invoice.taxRate}%)</span>
                        <span>{formatCurrency(invoice.taxAmount, invoice.currency)}</span>
                      </div>
                    )}
                    <div className="flex justify-between text-sm font-bold text-gray-900 dark:text-white">
                      <span>Total</span>
                      <span>{formatCurrency(invoice.total, invoice.currency)}</span>
                    </div>
                  </div>
                </div>

                {/* Work Proofs */}
                {invoice.workProofs.length > 0 && (
                  <div>
                    <h4 className="text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-3">
                      Work Proofs ({invoice.workProofs.length})
                    </h4>
                    <div className="space-y-2">
                      {invoice.workProofs.map((proof: any) => (
                        <div
                          key={proof._id}
                          className="flex items-center justify-between py-2 px-3 bg-gray-50 dark:bg-gray-800 rounded-lg"
                        >
                          <div className="flex items-center gap-3">
                            <div className={`w-7 h-7 rounded flex items-center justify-center ${
                              proof.verified
                                ? "bg-green-100 dark:bg-green-900/30"
                                : "bg-blue-100 dark:bg-blue-900/30"
                            }`}>
                              {proof.verified ? (
                                <CheckCircle2 className="w-4 h-4 text-green-500" />
                              ) : (
                                <Timer className="w-4 h-4 text-blue-500" />
                              )}
                            </div>
                            <div>
                              <p className="text-sm text-gray-900 dark:text-white">{proof.title}</p>
                              <p className="text-[10px] text-gray-400">
                                {proof.proofType.replace(/_/g, " ")}
                                {proof.hours ? ` — ${proof.hours}h` : ""}
                                {proof.value ? ` — ${formatCurrency(proof.value, invoice.currency)}` : ""}
                              </p>
                            </div>
                          </div>
                          <span className="text-xs text-gray-400">{formatDate(proof.date)}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Notes */}
                {invoice.notes && (
                  <div className="mt-4 p-3 bg-gray-50 dark:bg-gray-800 rounded-lg">
                    <p className="text-xs text-gray-400 mb-1">Notes</p>
                    <p className="text-sm text-gray-700 dark:text-gray-300 whitespace-pre-wrap">{invoice.notes}</p>
                  </div>
                )}
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Team Tab
// ---------------------------------------------------------------------------

function TeamTab({ team }: { team: TeamMember[] | undefined }) {
  if (team === undefined) return <LoadingSkeleton />;
  if (team.length === 0)
    return <EmptyState icon={Users} title="No team members" description="Team members assigned to your projects will appear here." />;

  const roleLabels: Record<string, string> = {
    owner: "Owner",
    manager: "Manager",
    member: "Member",
  };

  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
      {team.map((member, i) => (
        <div
          key={i}
          className="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 p-5 flex items-start gap-4"
        >
          <div
            className={`w-12 h-12 ${getAvatarColor(member.name)} rounded-xl flex items-center justify-center text-white font-bold shrink-0`}
          >
            {getInitials(member.name)}
          </div>
          <div className="min-w-0 flex-1">
            <h3 className="font-semibold text-gray-900 dark:text-white text-sm truncate">
              {member.name}
            </h3>
            {member.title && (
              <p className="text-xs text-gray-500 dark:text-gray-400 mt-0.5">{member.title}</p>
            )}
            <span className={`inline-flex items-center mt-1.5 text-xs px-2 py-0.5 rounded-full font-medium ${
              member.role === "owner"
                ? "bg-violet-100 dark:bg-violet-900/30 text-violet-600 dark:text-violet-400"
                : member.role === "manager"
                ? "bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400"
                : "bg-gray-100 dark:bg-gray-800 text-gray-500"
            }`}>
              {roleLabels[member.role] ?? member.role}
            </span>
            {member.projects.length > 0 && (
              <div className="mt-3 flex flex-wrap gap-1.5">
                {member.projects.map((proj, j) => (
                  <span
                    key={j}
                    className="text-[10px] px-2 py-0.5 bg-gray-100 dark:bg-gray-800 text-gray-500 dark:text-gray-400 rounded-full"
                  >
                    {proj}
                  </span>
                ))}
              </div>
            )}
          </div>
        </div>
      ))}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Shared Sub-components
// ---------------------------------------------------------------------------

function LoadingSkeleton() {
  return (
    <div className="space-y-4">
      {[1, 2, 3].map((i) => (
        <div key={i} className="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 p-5 animate-pulse">
          <div className="flex items-center gap-4">
            <div className="w-10 h-10 bg-gray-200 dark:bg-gray-700 rounded-lg" />
            <div className="flex-1">
              <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-1/3 mb-2" />
              <div className="h-3 bg-gray-200 dark:bg-gray-700 rounded w-1/4" />
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}

function EmptyState({
  icon: Icon,
  title,
  description,
}: {
  icon: React.ComponentType<{ className?: string }>;
  title: string;
  description: string;
}) {
  return (
    <div className="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 p-10 text-center">
      <div className="w-14 h-14 bg-gray-100 dark:bg-gray-800 rounded-xl flex items-center justify-center mx-auto mb-4">
        <Icon className="w-7 h-7 text-gray-400" />
      </div>
      <h3 className="font-semibold text-gray-900 dark:text-white text-sm mb-1">{title}</h3>
      <p className="text-xs text-gray-400 max-w-xs mx-auto">{description}</p>
    </div>
  );
}
