import { defineTable } from "convex/server";
import { v } from "convex/values";
import { sharingEntry } from "../sharedValidators";

export const scopeTables = {
  scopeDefinitions: defineTable({
    userId: v.id("users"),
    workspaceId: v.optional(v.id("workspaces")),
    projectId: v.optional(v.id("projects")),
    proposalId: v.optional(v.id("proposals")),
    title: v.string().maxLength(200),
    description: v.string().maxLength(5000),
    deliverables: v.array(
      v.object({
        id: v.string().maxLength(1000),
        name: v.string().maxLength(100),
        description: v.string().maxLength(5000),
        estimatedHours: v.optional(v.number()),
        status: v.optional(v.union(
          v.literal("pending"),
          v.literal("in_progress"),
          v.literal("completed"),
          v.literal("revised")
        )),
      })
    ),
    totalEstimatedHours: v.optional(v.number()),
    revisionLimit: v.number(), // max revisions allowed
    revisionCount: v.number(), // current revisions used
    status: v.union(
      v.literal("active"),
      v.literal("completed"),
      v.literal("disputed")
    ),
    clientApprovedAt: v.optional(v.number()),
    approvalToken: v.optional(v.string().maxLength(64)),
    createdBy: v.optional(v.id("users")),
    teamId: v.optional(v.id("teams")),
    sharing: v.optional(v.array(sharingEntry)),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_project", ["projectId"])
    .index("by_proposal", ["proposalId"])
    .index("by_approval_token", ["approvalToken"])
    .index("by_workspace", ["workspaceId"])
    .index("by_team", ["teamId"]),

  scopeChangeOrders: defineTable({
    userId: v.id("users"),
    workspaceId: v.optional(v.id("workspaces")),
    scopeId: v.id("scopeDefinitions"),
    title: v.string().maxLength(200),
    description: v.string().maxLength(5000),
    changeType: v.union(
      v.literal("addition"),
      v.literal("modification"),
      v.literal("removal"),
      v.literal("revision")
    ),
    impact: v.object({
      hoursAdded: v.number(),
      costImpact: v.number(),
      deadlineImpact: v.optional(v.number()),
    }),
    reason: v.string().maxLength(1000),
    status: v.union(
      v.literal("pending"),
      v.literal("approved"),
      v.literal("rejected"),
      v.literal("auto_generated")
    ),
    clientApprovalToken: v.optional(v.string().maxLength(64)),
    clientApprovedAt: v.optional(v.number()),
    autoGenerated: v.optional(v.boolean()),
    originalLimit: v.optional(v.number()),
    newLimit: v.optional(v.number()),
    createdBy: v.optional(v.id("users")),
    teamId: v.optional(v.id("teams")),
    sharing: v.optional(v.array(sharingEntry)),
    createdAt: v.number(),
  })
    .index("by_scope", ["scopeId"])
    .index("by_user", ["userId"])
    .index("by_approval_token", ["clientApprovalToken"])
    .index("by_workspace", ["workspaceId"])
    .index("by_team", ["teamId"]),
};
