import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogDescription } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";
import { toast } from "sonner";
import {
  Shield,
  Plus,
  AlertTriangle,
  CheckCircle2,
  Clock,
  FileText,
  TrendingUp,
  ArrowRight,
  Copy,
  ExternalLink,
  ChevronDown,
  ChevronUp,
  Edit3,
  Trash2,
  Eye,
  XCircle,
  Zap,
  BarChart3,
  GitBranch,
  MessageSquare,
  DollarSign,
} from "lucide-react";

// ─── Types ──────────────────────────────────────────────────────────────────

interface Deliverable {
  id: string;
  name: string;
  description: string;
  estimatedHours?: number;
  status?: "pending" | "in_progress" | "completed" | "revised";
}

interface ScopeDefinition {
  _id: string;
  title: string;
  description: string;
  projectId?: string;
  projectName?: string;
  deliverables: Deliverable[];
  totalEstimatedHours?: number;
  revisionLimit: number;
  revisionCount: number;
  status: "active" | "completed" | "disputed";
  clientApprovedAt?: number;
  approvalToken?: string;
  createdAt: number;
  updatedAt: number;
}

interface ScopeChangeOrder {
  _id: string;
  scopeId: string;
  scopeTitle?: string;
  title: string;
  description: string;
  changeType: "addition" | "modification" | "removal" | "revision";
  impact: {
    hoursAdded: number;
    costImpact: number;
    deadlineImpact?: number;
  };
  reason: string;
  status: "pending" | "approved" | "rejected" | "auto_generated";
  autoGenerated?: boolean;
  originalLimit?: number;
  newLimit?: number;
  createdAt: number;
  clientApprovedAt?: number;
}

interface ScopeFormalization {
  _id: string;
  projectId: string;
  projectName?: string;
  changeDescription: string;
  originalScope: string;
  newScope: string;
  impactAssessment: {
    timeImpact: string;
    budgetImpact: string;
    deliverableImpact: string;
  };
  clientAcknowledgment?: string;
  clientApprovalEvidence?: string;
  status: "pending" | "formalized" | "rejected";
  createdAt: number;
  formalizedAt?: number;
}

// ─── Mock Data ──────────────────────────────────────────────────────────────

const MOCK_SCOPES: ScopeDefinition[] = [
  {
    _id: "scope_1",
    title: "E-Commerce Website Redesign",
    description: "Complete redesign of the client's e-commerce platform including homepage, product pages, checkout flow, and admin dashboard. Scope covers UI/UX design, frontend development, and integration with existing payment gateway.",
    projectId: "proj_1",
    projectName: "E-Commerce Redesign",
    deliverables: [
      { id: "d1", name: "Homepage Redesign", description: "Full homepage with hero, featured products, testimonials", estimatedHours: 24, status: "completed" },
      { id: "d2", name: "Product Catalog Pages", description: "Product listing, detail pages with filters and search", estimatedHours: 32, status: "in_progress" },
      { id: "d3", name: "Checkout Flow", description: "Cart, payment, and order confirmation pages", estimatedHours: 20, status: "pending" },
      { id: "d4", name: "Admin Dashboard", description: "Order management, inventory, analytics dashboard", estimatedHours: 28, status: "pending" },
      { id: "d5", name: "Mobile Responsive", description: "Ensure all pages work seamlessly on mobile devices", estimatedHours: 16, status: "pending" },
    ],
    totalEstimatedHours: 120,
    revisionLimit: 3,
    revisionCount: 2,
    status: "active",
    clientApprovedAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
    approvalToken: "apr_tk_abc123",
    createdAt: Date.now() - 45 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
  },
  {
    _id: "scope_2",
    title: "Mobile App MVP - Task Manager",
    description: "Build a cross-platform task management mobile app with user authentication, task CRUD, categories, and push notifications. MVP scope only — no team features or integrations.",
    projectId: "proj_2",
    projectName: "Task Manager App",
    deliverables: [
      { id: "d6", name: "User Auth System", description: "Sign up, login, password reset, social auth", estimatedHours: 16, status: "completed" },
      { id: "d7", name: "Task CRUD Operations", description: "Create, read, update, delete tasks with categories", estimatedHours: 24, status: "completed" },
      { id: "d8", name: "Push Notifications", description: "Local and remote push notifications for reminders", estimatedHours: 12, status: "in_progress" },
      { id: "d9", name: "Settings & Preferences", description: "App settings, notification preferences, theme", estimatedHours: 8, status: "pending" },
    ],
    totalEstimatedHours: 60,
    revisionLimit: 2,
    revisionCount: 1,
    status: "active",
    approvalToken: "apr_tk_def456",
    createdAt: Date.now() - 20 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
  },
  {
    _id: "scope_3",
    title: "Brand Identity Package",
    description: "Complete brand identity design including logo, color palette, typography guide, business cards, and social media templates.",
    projectId: "proj_3",
    projectName: "Brand Identity",
    deliverables: [
      { id: "d10", name: "Logo Design", description: "Primary logo, secondary logo, and favicon", estimatedHours: 12, status: "completed" },
      { id: "d11", name: "Brand Guidelines", description: "Color palette, typography, spacing rules document", estimatedHours: 8, status: "completed" },
      { id: "d12", name: "Business Cards", description: "Front and back business card design", estimatedHours: 4, status: "completed" },
      { id: "d13", name: "Social Media Kit", description: "Templates for Instagram, LinkedIn, Twitter", estimatedHours: 6, status: "completed" },
    ],
    totalEstimatedHours: 30,
    revisionLimit: 2,
    revisionCount: 2,
    status: "completed",
    clientApprovedAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
    approvalToken: "apr_tk_ghi789",
    createdAt: Date.now() - 60 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
  },
];

const MOCK_CHANGE_ORDERS: ScopeChangeOrder[] = [
  {
    _id: "co_1",
    scopeId: "scope_1",
    scopeTitle: "E-Commerce Website Redesign",
    title: "Add Product Review System",
    description: "Client requested a full product review and rating system after the project started. This includes star ratings, text reviews, review moderation, and display on product pages.",
    changeType: "addition",
    impact: { hoursAdded: 16, costImpact: 1360, deadlineImpact: 5 },
    reason: "Client email on March 15th requesting review functionality for all products",
    status: "approved",
    createdAt: Date.now() - 15 * 24 * 60 * 60 * 1000,
    clientApprovedAt: Date.now() - 12 * 24 * 60 * 60 * 1000,
  },
  {
    _id: "co_2",
    scopeId: "scope_1",
    scopeTitle: "E-Commerce Website Redesign",
    title: "Modify Checkout to Add PayPal",
    description: "Original scope only included Stripe. Client now also wants PayPal as a payment option in the checkout flow.",
    changeType: "modification",
    impact: { hoursAdded: 8, costImpact: 680, deadlineImpact: 3 },
    reason: "Client feedback: Many customers prefer PayPal over credit card",
    status: "pending",
    createdAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
  },
  {
    _id: "co_3",
    scopeId: "scope_2",
    scopeTitle: "Mobile App MVP - Task Manager",
    title: "Revision: Redesign Task List Layout",
    description: "Client wasn't satisfied with the initial task list layout and requested a redesign with drag-and-drop reordering and swipe actions.",
    changeType: "revision",
    impact: { hoursAdded: 10, costImpact: 650, deadlineImpact: 4 },
    reason: "Client felt the initial design didn't match their vision after seeing the prototype",
    status: "approved",
    autoGenerated: false,
    originalLimit: 2,
    newLimit: 2,
    createdAt: Date.now() - 8 * 24 * 60 * 60 * 1000,
    clientApprovedAt: Date.now() - 6 * 24 * 60 * 60 * 1000,
  },
  {
    _id: "co_4",
    scopeId: "scope_2",
    scopeTitle: "Mobile App MVP - Task Manager",
    title: "Add Team Collaboration Features",
    description: "Client wants to add team workspaces, shared task lists, and assignment features — this was explicitly excluded from MVP scope.",
    changeType: "addition",
    impact: { hoursAdded: 40, costImpact: 2600, deadlineImpact: 14 },
    reason: "Client stakeholders decided they need team features for Q2 launch",
    status: "auto_generated",
    autoGenerated: true,
    originalLimit: 2,
    newLimit: 3,
    createdAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
  },
];

const MOCK_FORMALIZATIONS: ScopeFormalization[] = [
  {
    _id: "form_1",
    projectId: "proj_1",
    projectName: "E-Commerce Redesign",
    changeDescription: "Added product review and rating system to the e-commerce platform. Includes star ratings, text reviews, moderation dashboard, and review display on product pages.",
    originalScope: "Product pages with images, description, price, and add-to-cart only",
    newScope: "Product pages with all original features plus review system (star ratings, text reviews, moderation, user profiles for reviewers)",
    impactAssessment: {
      timeImpact: "+16 hours additional development time",
      budgetImpact: "+$1,360 to project total",
      deliverableImpact: "1 new deliverable: Product Review System",
    },
    clientAcknowledgment: "Email from client on March 15th: 'Yes, please add the review system. How much extra will it cost?'",
    clientApprovalEvidence: "Client approved via email and confirmed budget increase on March 16th call",
    status: "formalized",
    createdAt: Date.now() - 15 * 24 * 60 * 60 * 1000,
    formalizedAt: Date.now() - 12 * 24 * 60 * 60 * 1000,
  },
  {
    _id: "form_2",
    projectId: "proj_2",
    projectName: "Task Manager App",
    changeDescription: "Redesigned task list layout with drag-and-drop reordering and swipe-to-complete/delete gestures. Original flat list design replaced with card-based layout.",
    originalScope: "Simple flat task list with checkbox for completion",
    newScope: "Card-based task list with drag-and-drop reordering, swipe gestures, priority colors, and quick-edit mode",
    impactAssessment: {
      timeImpact: "+10 hours for UX redesign and gesture implementation",
      budgetImpact: "+$650 to project total",
      deliverableImpact: "Modified deliverable: Task CRUD Operations (redesigned UI)",
    },
    clientAcknowledgment: "Slack message: 'The new layout looks much better, go ahead with this direction'",
    status: "formalized",
    createdAt: Date.now() - 8 * 24 * 60 * 60 * 1000,
    formalizedAt: Date.now() - 6 * 24 * 60 * 60 * 1000,
  },
  {
    _id: "form_3",
    projectId: "proj_2",
    projectName: "Task Manager App",
    changeDescription: "Client requested team collaboration features (workspaces, shared lists, assignments) which were explicitly out of MVP scope.",
    originalScope: "MVP scope: Single-user task manager with no team or collaboration features",
    newScope: "Adding team workspaces, shared task lists, task assignment, and member management",
    impactAssessment: {
      timeImpact: "+40 hours — this is a major scope expansion",
      budgetImpact: "+$2,600 (40 hrs × $65/hr)",
      deliverableImpact: "3 new deliverables: Team Workspaces, Shared Lists, Task Assignment",
    },
    status: "pending",
    createdAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
  },
];

// ─── Helper Functions ───────────────────────────────────────────────────────

function formatDate(ts: number): string {
  return new Date(ts).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

function timeAgo(ts: number): string {
  const diff = Date.now() - ts;
  const minutes = Math.floor(diff / 60000);
  const hours = Math.floor(minutes / 60);
  const days = Math.floor(hours / 24);
  if (days > 0) return `${days}d ago`;
  if (hours > 0) return `${hours}h ago`;
  return `${minutes}m ago`;
}

function getChangeTypeIcon(type: string) {
  switch (type) {
    case "addition": return <Plus className="w-3.5 h-3.5 text-blue-500" />;
    case "modification": return <Edit3 className="w-3.5 h-3.5 text-amber-500" />;
    case "removal": return <Trash2 className="w-3.5 h-3.5 text-red-500" />;
    case "revision": return <GitBranch className="w-3.5 h-3.5 text-purple-500" />;
    default: return <FileText className="w-3.5 h-3.5" />;
  }
}

function getChangeTypeLabel(type: string) {
  return type.charAt(0).toUpperCase() + type.slice(1);
}

function getStatusBadge(status: string) {
  switch (status) {
    case "approved":
    case "formalized":
      return <Badge className="bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400 border-0 text-xs"><CheckCircle2 className="w-3 h-3 mr-1" />{status === "formalized" ? "Formalized" : "Approved"}</Badge>;
    case "pending":
      return <Badge className="bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-400 border-0 text-xs"><Clock className="w-3 h-3 mr-1" />Pending</Badge>;
    case "rejected":
      return <Badge className="bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400 border-0 text-xs"><XCircle className="w-3 h-3 mr-1" />Rejected</Badge>;
    case "auto_generated":
      return <Badge className="bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-400 border-0 text-xs"><Zap className="w-3 h-3 mr-1" />Auto-Detected</Badge>;
    case "active":
      return <Badge className="bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400 border-0 text-xs">Active</Badge>;
    case "completed":
      return <Badge className="bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400 border-0 text-xs">Completed</Badge>;
    case "disputed":
      return <Badge className="bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400 border-0 text-xs">Disputed</Badge>;
    default:
      return <Badge variant="secondary">{status}</Badge>;
  }
}

function getDeliverableStatusIcon(status?: string) {
  switch (status) {
    case "completed": return <CheckCircle2 className="w-4 h-4 text-green-500" />;
    case "in_progress": return <Clock className="w-4 h-4 text-blue-500" />;
    case "revised": return <Edit3 className="w-4 h-4 text-purple-500" />;
    case "pending": return <Clock className="w-4 h-4 text-muted-foreground" />;
    default: return <Clock className="w-4 h-4 text-muted-foreground" />;
  }
}

// ─── Scope Creep Detection ──────────────────────────────────────────────────

function calculateScopeHealth(scope: ScopeDefinition, changeOrders: ScopeChangeOrder[]) {
  const scopeChanges = changeOrders.filter(co => co.scopeId === scope._id);
  const pendingChanges = scopeChanges.filter(co => co.status === "pending" || co.status === "auto_generated");
  const revisionUsage = scope.revisionLimit > 0 ? (scope.revisionCount / scope.revisionLimit) * 100 : 0;
  const totalHoursAdded = scopeChanges.reduce((sum, co) => sum + co.impact.hoursAdded, 0);
  const totalCostImpact = scopeChanges.reduce((sum, co) => sum + co.impact.costImpact, 0);
  const hoursOverrun = scope.totalEstimatedHours ? (totalHoursAdded / scope.totalEstimatedHours) * 100 : 0;

  let riskLevel: "low" | "medium" | "high" = "low";
  if (revisionUsage >= 100 || hoursOverrun > 30 || pendingChanges.length >= 3) riskLevel = "high";
  else if (revisionUsage >= 66 || hoursOverrun > 15 || pendingChanges.length >= 2) riskLevel = "medium";

  const completedDeliverables = scope.deliverables.filter(d => d.status === "completed").length;
  const progressPercent = scope.deliverables.length > 0 ? (completedDeliverables / scope.deliverables.length) * 100 : 0;

  return {
    riskLevel,
    revisionUsage,
    totalHoursAdded,
    totalCostImpact,
    hoursOverrun,
    pendingChanges: pendingChanges.length,
    completedDeliverables,
    totalDeliverables: scope.deliverables.length,
    progressPercent,
  };
}

// ─── Sub-Components ─────────────────────────────────────────────────────────

function ScopeHealthBar({ health }: { health: ReturnType<typeof calculateScopeHealth> }) {
  const barColor = health.riskLevel === "high" ? "bg-red-500" : health.riskLevel === "medium" ? "bg-amber-500" : "bg-green-500";
  return (
    <div className="space-y-2">
      <div className="flex items-center justify-between text-xs">
        <span className="text-muted-foreground">Scope Health</span>
        <span className={`font-semibold ${health.riskLevel === "high" ? "text-red-600 dark:text-red-400" : health.riskLevel === "medium" ? "text-amber-600 dark:text-amber-400" : "text-green-600 dark:text-green-400"}`}>
          {health.riskLevel === "high" ? "High Risk" : health.riskLevel === "medium" ? "Moderate Risk" : "Healthy"}
        </span>
      </div>
      <div className="h-2 bg-muted rounded-full overflow-hidden">
        <div className={`h-full rounded-full transition-all ${barColor}`} style={{ width: `${Math.max(5, 100 - health.hoursOverrun - health.revisionUsage * 0.3)}%` }} />
      </div>
    </div>
  );
}

function ScopeCard({
  scope,
  changeOrders,
  isSelected,
  onSelect,
}: {
  scope: ScopeDefinition;
  changeOrders: ScopeChangeOrder[];
  isSelected: boolean;
  onSelect: () => void;
}) {
  const health = calculateScopeHealth(scope, changeOrders);
  const [expanded, setExpanded] = useState(isSelected);

  return (
    <Card className={`p-0 overflow-hidden transition-all border ${isSelected ? "border-primary ring-1 ring-primary/20" : "border-border hover:border-primary/30"}`}>
      {/* Header */}
      <div
        className="p-5 cursor-pointer"
        onClick={() => { onSelect(); setExpanded(!expanded); }}
      >
        <div className="flex items-start justify-between">
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 mb-1">
              <h3 className="font-bold text-foreground truncate">{scope.title}</h3>
              {getStatusBadge(scope.status)}
            </div>
            <p className="text-sm text-muted-foreground line-clamp-2">{scope.description}</p>
            {scope.projectName && (
              <p className="text-xs text-muted-foreground mt-1.5 flex items-center gap-1">
                <BriefcaseIcon className="w-3 h-3" /> {scope.projectName}
              </p>
            )}
          </div>
          <div className="flex-shrink-0 ml-4">
            {expanded ? <ChevronUp className="w-5 h-5 text-muted-foreground" /> : <ChevronDown className="w-5 h-5 text-muted-foreground" />}
          </div>
        </div>

        {/* Quick Stats */}
        <div className="grid grid-cols-4 gap-3 mt-4">
          <div className="text-center">
            <p className="text-lg font-bold text-foreground">{scope.deliverables.length}</p>
            <p className="text-[10px] text-muted-foreground uppercase tracking-wider">Deliverables</p>
          </div>
          <div className="text-center">
            <p className="text-lg font-bold text-foreground">{scope.revisionCount}/{scope.revisionLimit}</p>
            <p className="text-[10px] text-muted-foreground uppercase tracking-wider">Revisions</p>
          </div>
          <div className="text-center">
            <p className="text-lg font-bold text-foreground">{health.totalHoursAdded}h</p>
            <p className="text-[10px] text-muted-foreground uppercase tracking-wider">Hours Added</p>
          </div>
          <div className="text-center">
            <p className={`text-lg font-bold ${health.riskLevel === "high" ? "text-red-600 dark:text-red-400" : health.riskLevel === "medium" ? "text-amber-600 dark:text-amber-400" : "text-green-600 dark:text-green-400"}`}>
              {health.riskLevel === "high" ? "High" : health.riskLevel === "medium" ? "Med" : "Low"}
            </p>
            <p className="text-[10px] text-muted-foreground uppercase tracking-wider">Risk</p>
          </div>
        </div>

        <div className="mt-3">
          <ScopeHealthBar health={health} />
        </div>
      </div>

      {/* Expanded Content */}
      {expanded && (
        <div className="border-t border-border px-5 pb-5 pt-4 space-y-5">
          {/* Deliverables */}
          <div>
            <h4 className="text-sm font-semibold text-foreground mb-3 flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-primary" />
              Deliverables ({health.completedDeliverables}/{health.totalDeliverables})
            </h4>
            <div className="space-y-2">
              {scope.deliverables.map((d) => (
                <div key={d.id} className="flex items-start gap-3 p-2.5 rounded-lg bg-muted/50">
                  <div className="mt-0.5">{getDeliverableStatusIcon(d.status)}</div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium text-foreground">{d.name}</p>
                    <p className="text-xs text-muted-foreground">{d.description}</p>
                  </div>
                  {d.estimatedHours && (
                    <span className="text-xs text-muted-foreground whitespace-nowrap">{d.estimatedHours}h</span>
                  )}
                </div>
              ))}
            </div>
            <div className="mt-3">
              <Progress value={health.progressPercent} className="h-1.5" />
              <p className="text-xs text-muted-foreground mt-1">{Math.round(health.progressPercent)}% complete</p>
            </div>
          </div>

          {/* Revision Tracking */}
          <div>
            <h4 className="text-sm font-semibold text-foreground mb-2 flex items-center gap-2">
              <GitBranch className="w-4 h-4 text-primary" />
              Revision Tracking
            </h4>
            <div className="p-3 rounded-lg bg-muted/50 space-y-2">
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">Revisions Used</span>
                <span className="font-medium">{scope.revisionCount} of {scope.revisionLimit}</span>
              </div>
              <Progress value={health.revisionUsage} className="h-1.5" />
              {health.revisionUsage >= 100 && (
                <div className="flex items-center gap-1.5 text-xs text-red-600 dark:text-red-400">
                  <AlertTriangle className="w-3 h-3" />
                  Revision limit exceeded — new changes auto-detected as scope creep
                </div>
              )}
              {health.revisionUsage >= 66 && health.revisionUsage < 100 && (
                <div className="flex items-center gap-1.5 text-xs text-amber-600 dark:text-amber-400">
                  <AlertTriangle className="w-3 h-3" />
                  Approaching revision limit — formalize remaining changes carefully
                </div>
              )}
            </div>
          </div>

          {/* Client Approval */}
          <div>
            <h4 className="text-sm font-semibold text-foreground mb-2 flex items-center gap-2">
              <Shield className="w-4 h-4 text-primary" />
              Client Approval
            </h4>
            <div className="p-3 rounded-lg bg-muted/50">
              {scope.clientApprovedAt ? (
                <div className="flex items-center gap-2 text-sm">
                  <CheckCircle2 className="w-4 h-4 text-green-500" />
                  <span className="text-green-700 dark:text-green-400 font-medium">Approved by client</span>
                  <span className="text-muted-foreground">on {formatDate(scope.clientApprovedAt)}</span>
                </div>
              ) : (
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2 text-sm">
                    <Clock className="w-4 h-4 text-amber-500" />
                    <span className="text-amber-700 dark:text-amber-400 font-medium">Awaiting client approval</span>
                  </div>
                  {scope.approvalToken && (
                    <Button
                      variant="outline"
                      size="sm"
                      className="text-xs h-7"
                      onClick={(e) => {
                        e.stopPropagation();
                        const url = `${window.location.origin}/scope/approve/${scope.approvalToken}`;
                        navigator.clipboard.writeText(url);
                        toast.success("Approval link copied to clipboard!");
                      }}
                    >
                      <Copy className="w-3 h-3 mr-1" />
                      Copy Approval Link
                    </Button>
                  )}
                </div>
              )}
            </div>
          </div>

          {/* Impact Summary */}
          <div>
            <h4 className="text-sm font-semibold text-foreground mb-2 flex items-center gap-2">
              <BarChart3 className="w-4 h-4 text-primary" />
              Scope Impact Summary
            </h4>
            <div className="grid grid-cols-3 gap-3">
              <div className="p-3 rounded-lg bg-muted/50 text-center">
                <p className="text-lg font-bold text-foreground">+{health.totalHoursAdded}h</p>
                <p className="text-[10px] text-muted-foreground uppercase">Hours Added</p>
              </div>
              <div className="p-3 rounded-lg bg-muted/50 text-center">
                <p className="text-lg font-bold text-foreground">${health.totalCostImpact.toLocaleString()}</p>
                <p className="text-[10px] text-muted-foreground uppercase">Cost Impact</p>
              </div>
              <div className="p-3 rounded-lg bg-muted/50 text-center">
                <p className="text-lg font-bold text-foreground">{health.pendingChanges}</p>
                <p className="text-[10px] text-muted-foreground uppercase">Pending Changes</p>
              </div>
            </div>
          </div>
        </div>
      )}
    </Card>
  );
}

function BriefcaseIcon({ className }: { className?: string }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <rect x="2" y="7" width="20" height="14" rx="2" ry="2" />
      <path d="M16 7V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v2" />
    </svg>
  );
}

// ─── Main Scope Page ────────────────────────────────────────────────────────

export default function Scope() {
  const [selectedScopeId, setSelectedScopeId] = useState<string | null>("scope_1");
  const [activeTab, setActiveTab] = useState("definitions");

  // Dialog states
  const [showCreateScope, setShowCreateScope] = useState(false);
  const [showCreateChangeOrder, setShowCreateChangeOrder] = useState(false);
  const [showFormalizeDialog, setShowFormalizeDialog] = useState(false);

  // Create scope form
  const [newScopeTitle, setNewScopeTitle] = useState("");
  const [newScopeDescription, setNewScopeDescription] = useState("");
  const [newScopeRevisionLimit, setNewScopeRevisionLimit] = useState("3");
  const [newScopeEstimatedHours, setNewScopeEstimatedHours] = useState("");

  // Create change order form
  const [coTitle, setCoTitle] = useState("");
  const [coDescription, setCoDescription] = useState("");
  const [coChangeType, setCoChangeType] = useState<"addition" | "modification" | "removal" | "revision">("addition");
  const [coHoursAdded, setCoHoursAdded] = useState("");
  const [coCostImpact, setCoCostImpact] = useState("");
  const [coDeadlineImpact, setCoDeadlineImpact] = useState("");
  const [coReason, setCoReason] = useState("");

  // Formalize form
  const [formChangeDesc, setFormChangeDesc] = useState("");
  const [formOriginalScope, setFormOriginalScope] = useState("");
  const [formNewScope, setFormNewScope] = useState("");
  const [formTimeImpact, setFormTimeImpact] = useState("");
  const [formBudgetImpact, setFormBudgetImpact] = useState("");
  const [formDeliverableImpact, setFormDeliverableImpact] = useState("");
  const [formClientAck, setFormClientAck] = useState("");

  // Selected scope change orders and formalizations
  const selectedScope = MOCK_SCOPES.find(s => s._id === selectedScopeId);
  const selectedScopeChangeOrders = MOCK_CHANGE_ORDERS.filter(co => co.scopeId === selectedScopeId);
  const selectedScopeFormalizations = MOCK_FORMALIZATIONS.filter(f => {
    if (!selectedScope?.projectId) return false;
    return f.projectId === selectedScope.projectId;
  });

  // Overall metrics
  const totalScopes = MOCK_SCOPES.length;
  const activeScopes = MOCK_SCOPES.filter(s => s.status === "active").length;
  const totalPendingChanges = MOCK_CHANGE_ORDERS.filter(co => co.status === "pending" || co.status === "auto_generated").length;
  const totalUnformalized = MOCK_FORMALIZATIONS.filter(f => f.status === "pending").length;
  const totalHoursAtRisk = MOCK_CHANGE_ORDERS
    .filter(co => co.status === "pending" || co.status === "auto_generated")
    .reduce((sum, co) => sum + co.impact.hoursAdded, 0);
  const totalCostAtRisk = MOCK_CHANGE_ORDERS
    .filter(co => co.status === "pending" || co.status === "auto_generated")
    .reduce((sum, co) => sum + co.impact.costImpact, 0);

  const handleCreateScope = () => {
    if (!newScopeTitle || !newScopeDescription) {
      toast.error("Please fill in all required fields");
      return;
    }
    toast.success("Scope definition created successfully! (Demo mode)");
    setShowCreateScope(false);
    setNewScopeTitle("");
    setNewScopeDescription("");
    setNewScopeRevisionLimit("3");
    setNewScopeEstimatedHours("");
  };

  const handleCreateChangeOrder = () => {
    if (!coTitle || !coDescription || !coHoursAdded || !coCostImpact || !coReason) {
      toast.error("Please fill in all required fields");
      return;
    }
    toast.success("Change order recorded successfully! (Demo mode)");
    setShowCreateChangeOrder(false);
    setCoTitle("");
    setCoDescription("");
    setCoChangeType("addition");
    setCoHoursAdded("");
    setCoCostImpact("");
    setCoDeadlineImpact("");
    setCoReason("");
  };

  const handleFormalize = () => {
    if (!formChangeDesc || !formOriginalScope || !formNewScope) {
      toast.error("Please fill in all required fields");
      return;
    }
    toast.success("Scope change formalized successfully! (Demo mode)");
    setShowFormalizeDialog(false);
    setFormChangeDesc("");
    setFormOriginalScope("");
    setFormNewScope("");
    setFormTimeImpact("");
    setFormBudgetImpact("");
    setFormDeliverableImpact("");
    setFormClientAck("");
  };

  return (
    <div className="w-full min-h-screen bg-background">
      <div className="flex-1 transition-all duration-300 p-8 space-y-6">
        {/* Page Header */}
        <div className="flex items-start justify-between">
          <div>
            <h1 className="text-3xl font-bold text-foreground tracking-tight flex items-center gap-3">
              <Shield className="w-8 h-8 text-primary" />
              Scope Protection
            </h1>
            <p className="text-muted-foreground mt-1">
              Define project scope, track changes, formalize scope creep, and protect your income
            </p>
          </div>
          <div className="flex gap-2">
            <Button
              onClick={() => setShowFormalizeDialog(true)}
              variant="outline"
              size="sm"
            >
              <FileText className="w-4 h-4 mr-2" />
              Formalize Change
            </Button>
            <Button
              onClick={() => setShowCreateScope(true)}
              size="sm"
              className="bg-primary hover:bg-primary/90"
            >
              <Plus className="w-4 h-4 mr-2" />
              New Scope
            </Button>
          </div>
        </div>

        {/* Summary Cards */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <Card className="p-4 bg-card rounded-xl border border-border">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-blue-100 dark:bg-blue-900/30">
                <Shield className="w-4 h-4 text-blue-600 dark:text-blue-400" />
              </div>
              <div>
                <p className="text-2xl font-bold text-foreground">{totalScopes}</p>
                <p className="text-xs text-muted-foreground">Active Scopes</p>
              </div>
            </div>
          </Card>
          <Card className="p-4 bg-card rounded-xl border border-border">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-amber-100 dark:bg-amber-900/30">
                <AlertTriangle className="w-4 h-4 text-amber-600 dark:text-amber-400" />
              </div>
              <div>
                <p className="text-2xl font-bold text-foreground">{totalPendingChanges}</p>
                <p className="text-xs text-muted-foreground">Pending Changes</p>
              </div>
            </div>
          </Card>
          <Card className="p-4 bg-card rounded-xl border border-border">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-red-100 dark:bg-red-900/30">
                <DollarSign className="w-4 h-4 text-red-600 dark:text-red-400" />
              </div>
              <div>
                <p className="text-2xl font-bold text-foreground">${totalCostAtRisk.toLocaleString()}</p>
                <p className="text-xs text-muted-foreground">Value at Risk</p>
              </div>
            </div>
          </Card>
          <Card className="p-4 bg-card rounded-xl border border-border">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-purple-100 dark:bg-purple-900/30">
                <FileText className="w-4 h-4 text-purple-600 dark:text-purple-400" />
              </div>
              <div>
                <p className="text-2xl font-bold text-foreground">{totalUnformalized}</p>
                <p className="text-xs text-muted-foreground">Unformalized</p>
              </div>
            </div>
          </Card>
        </div>

        {/* Scope Creep Alert */}
        {(totalPendingChanges > 0 || totalUnformalized > 0) && (
          <div className="p-4 bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-800 rounded-xl">
            <div className="flex items-start gap-3">
              <AlertTriangle className="w-5 h-5 text-amber-600 dark:text-amber-400 mt-0.5 flex-shrink-0" />
              <div className="flex-1">
                <p className="font-bold text-sm text-amber-800 dark:text-amber-200">Scope Creep Warning</p>
                <p className="text-xs text-amber-700 dark:text-amber-300 mt-1">
                  You have {totalPendingChanges} pending change{totalPendingChanges !== 1 ? "s" : ""} and {totalUnformalized} unformalized scope change{totalUnformalized !== 1 ? "s" : ""}.
                  Unformalized scope changes put <strong>${totalCostAtRisk.toLocaleString()}</strong> at risk.
                  Formalize changes to create legally-referencable records and protect your income.
                </p>
                <Button
                  onClick={() => setShowFormalizeDialog(true)}
                  size="sm"
                  className="mt-2 bg-amber-600 hover:bg-amber-700 text-white h-7 text-xs"
                >
                  <FileText className="w-3 h-3 mr-1" />
                  Formalize Now
                </Button>
              </div>
            </div>
          </div>
        )}

        {/* Tabs */}
        <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-6">
          <TabsList className="bg-muted/50">
            <TabsTrigger value="definitions" className="text-xs">
              <Shield className="w-3.5 h-3.5 mr-1.5" />
              Scope Definitions
            </TabsTrigger>
            <TabsTrigger value="changes" className="text-xs">
              <GitBranch className="w-3.5 h-3.5 mr-1.5" />
              Change Orders
              {totalPendingChanges > 0 && (
                <Badge className="ml-1.5 bg-amber-500 text-white text-[10px] h-4 min-w-4 px-1">{totalPendingChanges}</Badge>
              )}
            </TabsTrigger>
            <TabsTrigger value="formalizations" className="text-xs">
              <FileText className="w-3.5 h-3.5 mr-1.5" />
              Formalizations
              {totalUnformalized > 0 && (
                <Badge className="ml-1.5 bg-purple-500 text-white text-[10px] h-4 min-w-4 px-1">{totalUnformalized}</Badge>
              )}
            </TabsTrigger>
          </TabsList>

          {/* ─── Scope Definitions Tab ────────────────────────────────── */}
          <TabsContent value="definitions" className="space-y-4">
            {MOCK_SCOPES.length === 0 ? (
              <Card className="p-8 bg-card rounded-xl border border-border text-center">
                <Shield className="w-12 h-12 text-muted-foreground/30 mx-auto mb-4" />
                <h3 className="text-lg font-semibold text-foreground mb-2">No Scope Definitions Yet</h3>
                <p className="text-sm text-muted-foreground mb-4">
                  Create your first scope definition to start tracking deliverables, revisions, and scope changes.
                </p>
                <Button onClick={() => setShowCreateScope(true)} className="bg-primary hover:bg-primary/90">
                  <Plus className="w-4 h-4 mr-2" />
                  Create Scope Definition
                </Button>
              </Card>
            ) : (
              <div className="space-y-4">
                {MOCK_SCOPES.map((scope) => (
                  <ScopeCard
                    key={scope._id}
                    scope={scope}
                    changeOrders={MOCK_CHANGE_ORDERS}
                    isSelected={selectedScopeId === scope._id}
                    onSelect={() => setSelectedScopeId(scope._id)}
                  />
                ))}
              </div>
            )}
          </TabsContent>

          {/* ─── Change Orders Tab ────────────────────────────────────── */}
          <TabsContent value="changes" className="space-y-4">
            {selectedScope && (
              <div className="flex items-center gap-2 mb-2">
                <span className="text-sm text-muted-foreground">Showing changes for:</span>
                <Select
                  value={selectedScopeId || ""}
                  onValueChange={(v) => setSelectedScopeId(v)}
                >
                  <SelectTrigger className="w-[280px] h-8 text-xs">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {MOCK_SCOPES.map((s) => (
                      <SelectItem key={s._id} value={s._id}>{s.title}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                <Button
                  variant="outline"
                  size="sm"
                  className="h-8 text-xs ml-auto"
                  onClick={() => setShowCreateChangeOrder(true)}
                >
                  <Plus className="w-3 h-3 mr-1" />
                  Record Change
                </Button>
              </div>
            )}

            {selectedScopeChangeOrders.length === 0 ? (
              <Card className="p-6 bg-card rounded-xl border border-border text-center">
                <GitBranch className="w-10 h-10 text-muted-foreground/30 mx-auto mb-3" />
                <h3 className="text-sm font-semibold text-foreground mb-1">No Change Orders</h3>
                <p className="text-xs text-muted-foreground">
                  No scope changes have been recorded for this project yet.
                </p>
              </Card>
            ) : (
              <div className="space-y-3">
                {selectedScopeChangeOrders.map((co) => (
                  <Card key={co._id} className="p-0 overflow-hidden border border-border">
                    <div className="p-4">
                      <div className="flex items-start justify-between mb-2">
                        <div className="flex items-center gap-2">
                          {getChangeTypeIcon(co.changeType)}
                          <h4 className="font-semibold text-sm text-foreground">{co.title}</h4>
                          {getStatusBadge(co.status)}
                        </div>
                        <span className="text-xs text-muted-foreground">{timeAgo(co.createdAt)}</span>
                      </div>
                      <p className="text-xs text-muted-foreground mb-3">{co.description}</p>

                      {/* Impact Grid */}
                      <div className="grid grid-cols-3 gap-3 mb-3">
                        <div className="p-2.5 rounded-lg bg-muted/50">
                          <div className="flex items-center gap-1 text-xs text-muted-foreground mb-0.5">
                            <Clock className="w-3 h-3" /> Time
                          </div>
                          <p className="text-sm font-bold text-foreground">+{co.impact.hoursAdded}h</p>
                        </div>
                        <div className="p-2.5 rounded-lg bg-muted/50">
                          <div className="flex items-center gap-1 text-xs text-muted-foreground mb-0.5">
                            <DollarSign className="w-3 h-3" /> Cost
                          </div>
                          <p className="text-sm font-bold text-foreground">+${co.impact.costImpact.toLocaleString()}</p>
                        </div>
                        {co.impact.deadlineImpact && (
                          <div className="p-2.5 rounded-lg bg-muted/50">
                            <div className="flex items-center gap-1 text-xs text-muted-foreground mb-0.5">
                              <TrendingUp className="w-3 h-3" /> Deadline
                            </div>
                            <p className="text-sm font-bold text-foreground">+{co.impact.deadlineImpact} days</p>
                          </div>
                        )}
                      </div>

                      {/* Reason */}
                      <div className="p-2.5 rounded-lg bg-muted/30 text-xs">
                        <span className="font-medium text-muted-foreground">Reason: </span>
                        <span className="text-foreground">{co.reason}</span>
                      </div>

                      {/* Auto-generated warning */}
                      {co.autoGenerated && (
                        <div className="mt-2 p-2.5 rounded-lg bg-red-50 dark:bg-red-950/20 border border-red-200 dark:border-red-800 flex items-start gap-2">
                          <Zap className="w-3.5 h-3.5 text-red-600 dark:text-red-400 mt-0.5 flex-shrink-0" />
                          <div className="text-xs text-red-700 dark:text-red-300">
                            <p className="font-semibold">Auto-Detected Scope Creep</p>
                            <p>This change was automatically detected because it exceeds the revision limit ({co.originalLimit}). The limit has been increased to {co.newLimit}.</p>
                          </div>
                        </div>
                      )}

                      {/* Actions */}
                      {co.status === "pending" && (
                        <div className="mt-3 flex gap-2">
                          <Button size="sm" className="h-7 text-xs bg-green-600 hover:bg-green-700 text-white" onClick={() => toast.success("Change order approved! (Demo mode)")}>
                            <CheckCircle2 className="w-3 h-3 mr-1" />
                            Approve
                          </Button>
                          <Button size="sm" variant="outline" className="h-7 text-xs" onClick={() => setShowFormalizeDialog(true)}>
                            <FileText className="w-3 h-3 mr-1" />
                            Formalize
                          </Button>
                          <Button size="sm" variant="outline" className="h-7 text-xs text-red-600 hover:text-red-700" onClick={() => toast.info("Change order rejected (Demo mode)")}>
                            <XCircle className="w-3 h-3 mr-1" />
                            Reject
                          </Button>
                        </div>
                      )}
                      {co.status === "auto_generated" && (
                        <div className="mt-3 flex gap-2">
                          <Button size="sm" className="h-7 text-xs bg-purple-600 hover:bg-purple-700 text-white" onClick={() => setShowFormalizeDialog(true)}>
                            <FileText className="w-3 h-3 mr-1" />
                            Formalize This Change
                          </Button>
                        </div>
                      )}
                    </div>
                  </Card>
                ))}
              </div>
            )}
          </TabsContent>

          {/* ─── Formalizations Tab ───────────────────────────────────── */}
          <TabsContent value="formalizations" className="space-y-4">
            <div className="flex items-center justify-between mb-2">
              <p className="text-sm text-muted-foreground">
                Formalized scope changes create a legal record that protects your income in case of disputes.
              </p>
              <Button
                variant="outline"
                size="sm"
                className="h-8 text-xs"
                onClick={() => setShowFormalizeDialog(true)}
              >
                <Plus className="w-3 h-3 mr-1" />
                New Formalization
              </Button>
            </div>

            {selectedScopeFormalizations.length === 0 ? (
              <Card className="p-6 bg-card rounded-xl border border-border text-center">
                <FileText className="w-10 h-10 text-muted-foreground/30 mx-auto mb-3" />
                <h3 className="text-sm font-semibold text-foreground mb-1">No Formalizations</h3>
                <p className="text-xs text-muted-foreground">
                  No scope changes have been formalized for this project yet. Formalize changes to create dispute-proof records.
                </p>
              </Card>
            ) : (
              <div className="space-y-3">
                {selectedScopeFormalizations.map((form) => (
                  <Card key={form._id} className="p-0 overflow-hidden border border-border">
                    <div className="p-4">
                      <div className="flex items-start justify-between mb-2">
                        <div className="flex items-center gap-2">
                          <FileText className="w-4 h-4 text-primary" />
                          <h4 className="font-semibold text-sm text-foreground">{form.changeDescription.slice(0, 80)}{form.changeDescription.length > 80 ? "..." : ""}</h4>
                        </div>
                        <div className="flex items-center gap-2">
                          {getStatusBadge(form.status)}
                          <span className="text-xs text-muted-foreground">{timeAgo(form.createdAt)}</span>
                        </div>
                      </div>

                      {/* Scope Diff */}
                      <div className="grid grid-cols-2 gap-3 mb-3">
                        <div className="p-2.5 rounded-lg bg-red-50 dark:bg-red-950/20 border border-red-100 dark:border-red-900/30">
                          <p className="text-[10px] font-semibold text-red-600 dark:text-red-400 uppercase tracking-wider mb-1">Original Scope</p>
                          <p className="text-xs text-foreground">{form.originalScope}</p>
                        </div>
                        <div className="p-2.5 rounded-lg bg-green-50 dark:bg-green-950/20 border border-green-100 dark:border-green-900/30">
                          <p className="text-[10px] font-semibold text-green-600 dark:text-green-400 uppercase tracking-wider mb-1">New Scope</p>
                          <p className="text-xs text-foreground">{form.newScope}</p>
                        </div>
                      </div>

                      {/* Impact Assessment */}
                      <div className="p-2.5 rounded-lg bg-muted/50 mb-3">
                        <p className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wider mb-2">Impact Assessment</p>
                        <div className="grid grid-cols-3 gap-3 text-xs">
                          <div>
                            <span className="text-muted-foreground">Time:</span>
                            <p className="font-medium text-foreground">{form.impactAssessment.timeImpact}</p>
                          </div>
                          <div>
                            <span className="text-muted-foreground">Budget:</span>
                            <p className="font-medium text-foreground">{form.impactAssessment.budgetImpact}</p>
                          </div>
                          <div>
                            <span className="text-muted-foreground">Deliverables:</span>
                            <p className="font-medium text-foreground">{form.impactAssessment.deliverableImpact}</p>
                          </div>
                        </div>
                      </div>

                      {/* Client Acknowledgment */}
                      {form.clientAcknowledgment && (
                        <div className="p-2.5 rounded-lg bg-blue-50 dark:bg-blue-950/20 border border-blue-100 dark:border-blue-900/30 mb-3">
                          <p className="text-[10px] font-semibold text-blue-600 dark:text-blue-400 uppercase tracking-wider mb-1 flex items-center gap-1">
                            <MessageSquare className="w-3 h-3" /> Client Acknowledgment
                          </p>
                          <p className="text-xs text-foreground">{form.clientAcknowledgment}</p>
                        </div>
                      )}

                      {form.clientApprovalEvidence && (
                        <div className="p-2.5 rounded-lg bg-green-50 dark:bg-green-950/20 border border-green-100 dark:border-green-900/30">
                          <p className="text-[10px] font-semibold text-green-600 dark:text-green-400 uppercase tracking-wider mb-1 flex items-center gap-1">
                            <CheckCircle2 className="w-3 h-3" /> Approval Evidence
                          </p>
                          <p className="text-xs text-foreground">{form.clientApprovalEvidence}</p>
                        </div>
                      )}

                      {/* Pending actions */}
                      {form.status === "pending" && (
                        <div className="mt-3 flex gap-2">
                          <Button size="sm" className="h-7 text-xs bg-green-600 hover:bg-green-700 text-white" onClick={() => toast.success("Formalization completed! (Demo mode)")}>
                            <CheckCircle2 className="w-3 h-3 mr-1" />
                            Mark Formalized
                          </Button>
                          <Button size="sm" variant="outline" className="h-7 text-xs text-red-600 hover:text-red-700" onClick={() => toast.info("Formalization rejected (Demo mode)")}>
                            <XCircle className="w-3 h-3 mr-1" />
                            Reject
                          </Button>
                        </div>
                      )}
                    </div>
                  </Card>
                ))}
              </div>
            )}
          </TabsContent>
        </Tabs>
      </div>

      {/* ─── Create Scope Definition Dialog ──────────────────────────── */}
      <Dialog open={showCreateScope} onOpenChange={setShowCreateScope}>
        <DialogContent className="sm:max-w-[600px] max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Shield className="w-5 h-5 text-primary" />
              Create Scope Definition
            </DialogTitle>
            <DialogDescription>
              Define the scope of work for a project. This creates a baseline for tracking scope changes and protecting against scope creep.
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4 py-4">
            <div className="p-3 bg-indigo-50 dark:bg-indigo-950/20 border border-indigo-200 dark:border-indigo-800 rounded-lg flex items-start gap-2">
              <Shield className="w-4 h-4 text-indigo-600 dark:text-indigo-400 mt-0.5" />
              <div className="text-xs text-indigo-800 dark:text-indigo-200">
                <p className="font-bold mb-1">Why define scope?</p>
                <p>Scope definitions create a documented baseline. When clients request changes beyond this baseline, they're formally tracked as change orders with time, cost, and deadline impacts — protecting your income from scope creep.</p>
              </div>
            </div>

            <div className="grid gap-2">
              <Label htmlFor="scopeTitle">Title <span className="text-red-500">*</span></Label>
              <Input id="scopeTitle" placeholder="e.g., E-Commerce Website Redesign" value={newScopeTitle} onChange={(e) => setNewScopeTitle(e.target.value)} />
            </div>

            <div className="grid gap-2">
              <Label htmlFor="scopeDescription">Description <span className="text-red-500">*</span></Label>
              <Textarea id="scopeDescription" placeholder="Describe the full scope of work..." value={newScopeDescription} onChange={(e) => setNewScopeDescription(e.target.value)} rows={3} />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="grid gap-2">
                <Label htmlFor="revisionLimit">Revision Limit</Label>
                <Input id="revisionLimit" type="number" placeholder="3" value={newScopeRevisionLimit} onChange={(e) => setNewScopeRevisionLimit(e.target.value)} />
                <p className="text-xs text-muted-foreground">Max revisions before auto-detecting scope creep</p>
              </div>
              <div className="grid gap-2">
                <Label htmlFor="estimatedHours">Estimated Hours</Label>
                <Input id="estimatedHours" type="number" placeholder="120" value={newScopeEstimatedHours} onChange={(e) => setNewScopeEstimatedHours(e.target.value)} />
              </div>
            </div>

            <div className="grid gap-2">
              <Label>Deliverables</Label>
              <p className="text-xs text-muted-foreground">Add deliverables after creating the scope definition</p>
            </div>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setShowCreateScope(false)}>Cancel</Button>
            <Button onClick={handleCreateScope} className="bg-primary hover:bg-primary/90">
              <Shield className="w-4 h-4 mr-2" />
              Create Scope
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ─── Create Change Order Dialog ──────────────────────────────── */}
      <Dialog open={showCreateChangeOrder} onOpenChange={setShowCreateChangeOrder}>
        <DialogContent className="sm:max-w-[600px] max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <GitBranch className="w-5 h-5 text-primary" />
              Record Scope Change
            </DialogTitle>
            <DialogDescription>
              Document a scope change to track its impact and ensure proper client approval. This creates a formal record for dispute protection.
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4 py-4">
            <div className="grid gap-2">
              <Label htmlFor="coTitle">Change Title <span className="text-red-500">*</span></Label>
              <Input id="coTitle" placeholder="e.g., Add Product Review System" value={coTitle} onChange={(e) => setCoTitle(e.target.value)} />
            </div>

            <div className="grid gap-2">
              <Label htmlFor="coDescription">Description <span className="text-red-500">*</span></Label>
              <Textarea id="coDescription" placeholder="Describe what changed..." value={coDescription} onChange={(e) => setCoDescription(e.target.value)} rows={3} />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="grid gap-2">
                <Label>Change Type</Label>
                <Select value={coChangeType} onValueChange={(v: any) => setCoChangeType(v)}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="addition">Addition</SelectItem>
                    <SelectItem value="modification">Modification</SelectItem>
                    <SelectItem value="removal">Removal</SelectItem>
                    <SelectItem value="revision">Revision</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="grid gap-2">
                <Label htmlFor="coReason">Reason <span className="text-red-500">*</span></Label>
                <Input id="coReason" placeholder="Why this change was requested" value={coReason} onChange={(e) => setCoReason(e.target.value)} />
              </div>
            </div>

            <Separator />

            <div>
              <h4 className="text-sm font-semibold mb-3 flex items-center gap-2">
                <DollarSign className="w-4 h-4" />
                Impact Assessment
              </h4>
              <div className="grid grid-cols-3 gap-4">
                <div className="grid gap-2">
                  <Label htmlFor="coHoursAdded">Hours Added <span className="text-red-500">*</span></Label>
                  <Input id="coHoursAdded" type="number" placeholder="16" value={coHoursAdded} onChange={(e) => setCoHoursAdded(e.target.value)} />
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="coCostImpact">Cost Impact ($) <span className="text-red-500">*</span></Label>
                  <Input id="coCostImpact" type="number" placeholder="1360" value={coCostImpact} onChange={(e) => setCoCostImpact(e.target.value)} />
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="coDeadlineImpact">Deadline Impact (days)</Label>
                  <Input id="coDeadlineImpact" type="number" placeholder="5" value={coDeadlineImpact} onChange={(e) => setCoDeadlineImpact(e.target.value)} />
                </div>
              </div>
            </div>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setShowCreateChangeOrder(false)}>Cancel</Button>
            <Button onClick={handleCreateChangeOrder} className="bg-primary hover:bg-primary/90">
              <GitBranch className="w-4 h-4 mr-2" />
              Record Change
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ─── Formalize Scope Change Dialog ───────────────────────────── */}
      <Dialog open={showFormalizeDialog} onOpenChange={setShowFormalizeDialog}>
        <DialogContent className="sm:max-w-[600px] max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <FileText className="w-5 h-5 text-primary" />
              Formalize Scope Change
            </DialogTitle>
            <DialogDescription>
              Document scope changes to protect your work and maintain clear client expectations. This creates a formal record that can be referenced in case of disputes.
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4 py-4">
            <div className="p-3 bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-800 rounded-lg flex items-start gap-2">
              <AlertTriangle className="w-4 h-4 text-amber-600 dark:text-amber-400 mt-0.5" />
              <div className="text-xs text-amber-800 dark:text-amber-200">
                <p className="font-bold mb-1">Why formalize scope changes?</p>
                <p>Unformalized scope creep is the #1 cause of payment disputes. Documenting changes protects your income and maintains professional boundaries.</p>
              </div>
            </div>

            <div className="grid gap-2">
              <Label htmlFor="formChangeDesc">Change Description <span className="text-red-500">*</span></Label>
              <Textarea id="formChangeDesc" placeholder="Describe what changed in the project scope..." value={formChangeDesc} onChange={(e) => setFormChangeDesc(e.target.value)} rows={3} />
            </div>

            <div className="grid gap-2">
              <Label htmlFor="formOriginalScope">Original Scope <span className="text-red-500">*</span></Label>
              <Textarea id="formOriginalScope" placeholder="What was originally agreed upon..." value={formOriginalScope} onChange={(e) => setFormOriginalScope(e.target.value)} rows={2} />
            </div>

            <div className="grid gap-2">
              <Label htmlFor="formNewScope">New Scope <span className="text-red-500">*</span></Label>
              <Textarea id="formNewScope" placeholder="What is now expected..." value={formNewScope} onChange={(e) => setFormNewScope(e.target.value)} rows={2} />
            </div>

            <div className="border rounded-lg p-4 space-y-3 bg-slate-50 dark:bg-slate-900/50">
              <h4 className="font-bold text-sm flex items-center gap-2">
                <DollarSign className="w-4 h-4" />
                Impact Assessment
              </h4>
              <div className="grid gap-2">
                <Label htmlFor="formTimeImpact" className="flex items-center gap-1">
                  <Clock className="w-3 h-3" /> Time Impact
                </Label>
                <Input id="formTimeImpact" placeholder="e.g., +10 hours, 2 extra weeks" value={formTimeImpact} onChange={(e) => setFormTimeImpact(e.target.value)} />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="formBudgetImpact">Budget Impact</Label>
                <Input id="formBudgetImpact" placeholder="e.g., +$500, 20% increase" value={formBudgetImpact} onChange={(e) => setFormBudgetImpact(e.target.value)} />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="formDeliverableImpact">Deliverable Impact</Label>
                <Input id="formDeliverableImpact" placeholder="e.g., 3 additional features, revised timeline" value={formDeliverableImpact} onChange={(e) => setFormDeliverableImpact(e.target.value)} />
              </div>
            </div>

            <div className="grid gap-2">
              <Label htmlFor="formClientAck">Client Acknowledgment (Optional)</Label>
              <Textarea id="formClientAck" placeholder="Paste client's email, message, or approval here..." value={formClientAck} onChange={(e) => setFormClientAck(e.target.value)} rows={3} />
              <p className="text-xs text-muted-foreground">Including client acknowledgment strengthens your protection score</p>
            </div>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setShowFormalizeDialog(false)}>Cancel</Button>
            <Button onClick={handleFormalize} className="bg-indigo-600 hover:bg-indigo-700">
              <CheckCircle2 className="w-4 h-4 mr-2" />
              Formalize Change
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
