import { query, mutation } from "../_generated/server";
import { v } from "convex/values";
import { getAuthUserId } from "@convex-dev/auth/server";

// ─── QUERIES ──────────────────────────────────────────────────────────────

export const getScopeDefinitions = query({
  args: { projectId: v.optional(v.id("projects")) },
  handler: async (ctx, { projectId }) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) return [];

    if (projectId) {
      return await ctx.db
        .query("scopeDefinitions")
        .withIndex("by_project", (q) => q.eq("projectId", projectId))
        .collect();
    }
    return await ctx.db
      .query("scopeDefinitions")
      .withIndex("by_user", (q) => q.eq("userId", userId))
      .collect();
  },
});

export const getScopeDefinition = query({
  args: { scopeId: v.id("scopeDefinitions") },
  handler: async (ctx, { scopeId }) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) return null;
    const scope = await ctx.db.get(scopeId);
    if (!scope || scope.userId !== userId) return null;
    return scope;
  },
});

export const getChangeOrders = query({
  args: { scopeId: v.id("scopeDefinitions") },
  handler: async (ctx, { scopeId }) => {
    return await ctx.db
      .query("scopeChangeOrders")
      .withIndex("by_scope", (q) => q.eq("scopeId", scopeId))
      .collect();
  },
});

export const getScopeByApprovalToken = query({
  args: { approvalToken: v.string() },
  handler: async (ctx, { approvalToken }) => {
    return await ctx.db
      .query("scopeDefinitions")
      .withIndex("by_approval_token", (q) => q.eq("approvalToken", approvalToken))
      .first();
  },
});

// ─── MUTATIONS ────────────────────────────────────────────────────────────

function generateToken(): string {
  const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  let result = "";
  for (let i = 0; i < 32; i++) result += chars.charAt(Math.floor(Math.random() * chars.length));
  return result;
}

export const createScopeDefinition = mutation({
  args: {
    title: v.string(),
    description: v.string(),
    projectId: v.optional(v.id("projects")),
    proposalId: v.optional(v.id("proposals")),
    deliverables: v.array(v.object({
      id: v.string(),
      name: v.string(),
      description: v.string(),
      estimatedHours: v.optional(v.number()),
      status: v.optional(v.union(v.literal("pending"), v.literal("in_progress"), v.literal("completed"), v.literal("revised"))),
    })),
    totalEstimatedHours: v.optional(v.number()),
    revisionLimit: v.number(),
  },
  handler: async (ctx, args) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) throw new Error("Not authenticated");

    return await ctx.db.insert("scopeDefinitions", {
      userId,
      ...args,
      revisionCount: 0,
      status: "active",
      approvalToken: generateToken(),
      createdAt: Date.now(),
      updatedAt: Date.now(),
    });
  },
});

export const updateScopeDefinition = mutation({
  args: {
    scopeId: v.id("scopeDefinitions"),
    title: v.optional(v.string()),
    description: v.optional(v.string()),
    deliverables: v.optional(v.array(v.object({
      id: v.string(),
      name: v.string(),
      description: v.string(),
      estimatedHours: v.optional(v.number()),
      status: v.optional(v.union(v.literal("pending"), v.literal("in_progress"), v.literal("completed"), v.literal("revised"))),
    }))),
    totalEstimatedHours: v.optional(v.number()),
    revisionLimit: v.optional(v.number()),
  },
  handler: async (ctx, { scopeId, ...updates }) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) throw new Error("Not authenticated");

    const scope = await ctx.db.get(scopeId);
    if (!scope || scope.userId !== userId) throw new Error("Not authorized");

    await ctx.db.patch(scopeId, { ...updates, updatedAt: Date.now() });
  },
});

export const recordRevision = mutation({
  args: {
    scopeId: v.id("scopeDefinitions"),
    title: v.string(),
    description: v.string(),
    changeType: v.union(v.literal("addition"), v.literal("modification"), v.literal("removal"), v.literal("revision")),
    hoursAdded: v.number(),
    costImpact: v.number(),
    deadlineImpact: v.optional(v.number()),
    reason: v.string(),
  },
  handler: async (ctx, args) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) throw new Error("Not authenticated");

    const scope = await ctx.db.get(args.scopeId);
    if (!scope || scope.userId !== userId) throw new Error("Not authorized");

    const newRevisionCount = scope.revisionCount + 1;
    const autoGenerated = newRevisionCount > scope.revisionLimit;

    const changeOrderId = await ctx.db.insert("scopeChangeOrders", {
      userId,
      scopeId: args.scopeId,
      title: args.title,
      description: args.description,
      changeType: args.changeType,
      impact: {
        hoursAdded: args.hoursAdded,
        costImpact: args.costImpact,
        deadlineImpact: args.deadlineImpact,
      },
      reason: args.reason,
      status: autoGenerated ? "auto_generated" : "pending",
      clientApprovalToken: generateToken(),
      autoGenerated,
      originalLimit: scope.revisionLimit,
      newLimit: autoGenerated ? scope.revisionLimit + 1 : scope.revisionLimit,
      createdAt: Date.now(),
    });

    await ctx.db.patch(args.scopeId, {
      revisionCount: newRevisionCount,
      updatedAt: Date.now(),
    });

    return { changeOrderId, autoGenerated, revisionCount: newRevisionCount, limit: scope.revisionLimit };
  },
});

export const approveChangeOrder = mutation({
  args: { changeOrderId: v.id("scopeChangeOrders") },
  handler: async (ctx, { changeOrderId }) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) throw new Error("Not authenticated");

    const co = await ctx.db.get(changeOrderId);
    if (!co || co.userId !== userId) throw new Error("Not authorized");

    await ctx.db.patch(changeOrderId, {
      status: "approved",
      clientApprovedAt: Date.now(),
    });

    if (co.newLimit) {
      await ctx.db.patch(co.scopeId, {
        revisionLimit: co.newLimit,
        updatedAt: Date.now(),
      });
    }
  },
});

export const approveScopeByClient = mutation({
  args: { approvalToken: v.string() },
  handler: async (ctx, { approvalToken }) => {
    // This is a public action via shared link — client approves without being a platform user
    // SECURITY: Only allow approval for scopes that haven't been approved yet
    const scope = await ctx.db
      .query("scopeDefinitions")
      .withIndex("by_approval_token", (q) => q.eq("approvalToken", approvalToken))
      .first();

    if (!scope) throw new Error("Invalid approval token");
    if (scope.clientApprovedAt) throw new Error("Scope has already been approved");

    await ctx.db.patch(scope._id, {
      clientApprovedAt: Date.now(),
      updatedAt: Date.now(),
    });

    return { success: true, scopeTitle: scope.title };
  },
});

export const deleteScopeDefinition = mutation({
  args: { scopeId: v.id("scopeDefinitions") },
  handler: async (ctx, { scopeId }) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) throw new Error("Not authenticated");

    const scope = await ctx.db.get(scopeId);
    if (!scope || scope.userId !== userId) throw new Error("Not authorized");

    const changeOrders = await ctx.db
      .query("scopeChangeOrders")
      .withIndex("by_scope", (q) => q.eq("scopeId", scopeId))
      .collect();
    for (const co of changeOrders) await ctx.db.delete(co._id);

    await ctx.db.delete(scopeId);
  },
});
