import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { useState } from "react";
import { toast } from "sonner";
import jsPDF from "jspdf";

type Props = {
  isOpen: boolean;
  onClose: () => void;
  caseId?: string;
  reportContent?: string;
};

export function ReportViewerModal({ isOpen, onClose, caseId, reportContent }: Props) {
  const [downloading, setDownloading] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(reportContent || "");
      toast.success("Report copied to clipboard");
    } catch {
      toast.error("Failed to copy");
    }
  };

  const handleDownloadMD = async () => {
    try {
      setDownloading(true);
      const blob = new Blob([reportContent || ""], { type: "text/markdown;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${caseId || "axia_report"}.md`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
      toast.success("Markdown downloaded");
    } catch {
      toast.error("Failed to download");
    } finally {
      setDownloading(false);
    }
  };

  const handleDownloadPDF = async () => {
    try {
      setDownloading(true);
      const doc = new jsPDF({ unit: "mm", format: "a4" });
      const margin = 20;
      const pageWidth = doc.internal.pageSize.getWidth();
      const contentWidth = pageWidth - margin * 2;

      // Title
      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.setTextColor(26, 26, 46);
      doc.text("Universal Dispute Report", margin, 20);
      if (caseId) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        doc.setTextColor(148, 163, 184);
        doc.text(`Case ID: ${caseId}`, margin, 26);
      }

      // Content — split into lines and handle pagination
      const lines = doc.setFont("helvetica", "normal").setFontSize(10).splitTextToSize(reportContent || "No content", contentWidth);
      let y = 34;
      const pageHeight = doc.internal.pageSize.getHeight();
      const bottomMargin = 20;

      lines.forEach((line: string) => {
        if (y > pageHeight - bottomMargin) {
          doc.addPage();
          y = margin;
        }
        doc.setTextColor(51, 65, 85);
        doc.text(line, margin, y);
        y += 5;
      });

      // Footer
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      doc.setTextColor(203, 213, 225);
      doc.text(`Generated by Axia \u2022 ${new Date().toLocaleString()}`, margin, pageHeight - 10);

      doc.save(`${caseId || "axia_report"}.pdf`);
      toast.success("PDF downloaded");
    } catch {
      toast.error("Failed to generate PDF");
    } finally {
      setDownloading(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={(v) => (!v ? onClose() : null)}>
      <DialogContent className="sm:max-w-3xl max-h-[85vh] overflow-y-auto overflow-x-hidden">
        <DialogHeader>
          <DialogTitle className="flex items-center justify-between">
            <span>Universal Dispute Report</span>
            {caseId && <span className="text-xs text-muted-foreground">Case ID: {caseId}</span>}
          </DialogTitle>
          <DialogDescription>View, copy, or download your dispute report.</DialogDescription>
        </DialogHeader>

        <div className="border border-border rounded-md">
          <ScrollArea className="h-[60vh] p-4">
            <pre className="text-sm whitespace-pre-wrap break-words text-foreground">{reportContent || "No content"}</pre>
          </ScrollArea>
        </div>

        <DialogFooter className="gap-2">
          <Button variant="outline" onClick={handleCopy}>Copy</Button>
          <Button onClick={handleDownloadPDF} disabled={downloading}>
            {downloading ? "Downloading..." : "Download PDF"}
          </Button>
          <Button variant="outline" onClick={handleDownloadMD} disabled={downloading}>
            Download .md
          </Button>
          <Button variant="outline" onClick={onClose}>Close</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
