import { defineTable } from "convex/server";
import { v } from "convex/values";

export const scopeTables = {
  scopeDefinitions: defineTable({
    userId: v.id("users"),
    workspaceId: v.optional(v.id("workspaces")),
    projectId: v.optional(v.id("projects")),
    proposalId: v.optional(v.id("proposals")),
    title: v.string(),
    description: v.string(),
    deliverables: v.array(
      v.object({
        id: v.string(),
        name: v.string(),
        description: v.string(),
        estimatedHours: v.optional(v.number()),
        status: v.optional(v.union(
          v.literal("pending"),
          v.literal("in_progress"),
          v.literal("completed"),
          v.literal("revised")
        )),
      })
    ),
    totalEstimatedHours: v.optional(v.number()),
    revisionLimit: v.number(), // max revisions allowed
    revisionCount: v.number(), // current revisions used
    status: v.union(
      v.literal("active"),
      v.literal("completed"),
      v.literal("disputed")
    ),
    clientApprovedAt: v.optional(v.number()),
    approvalToken: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_project", ["projectId"])
    .index("by_proposal", ["proposalId"])
    .index("by_approval_token", ["approvalToken"])
    .index("by_workspace", ["workspaceId"]),

  scopeChangeOrders: defineTable({
    userId: v.id("users"),
    workspaceId: v.optional(v.id("workspaces")),
    scopeId: v.id("scopeDefinitions"),
    title: v.string(),
    description: v.string(),
    changeType: v.union(
      v.literal("addition"),
      v.literal("modification"),
      v.literal("removal"),
      v.literal("revision")
    ),
    impact: v.object({
      hoursAdded: v.number(),
      costImpact: v.number(),
      deadlineImpact: v.optional(v.number()),
    }),
    reason: v.string(),
    status: v.union(
      v.literal("pending"),
      v.literal("approved"),
      v.literal("rejected"),
      v.literal("auto_generated")
    ),
    clientApprovalToken: v.optional(v.string()),
    clientApprovedAt: v.optional(v.number()),
    autoGenerated: v.optional(v.boolean()),
    originalLimit: v.optional(v.number()),
    newLimit: v.optional(v.number()),
    createdAt: v.number(),
  })
    .index("by_scope", ["scopeId"])
    .index("by_user", ["userId"])
    .index("by_approval_token", ["clientApprovalToken"])
    .index("by_workspace", ["workspaceId"]),
};
