#!/usr/bin/env python3
"""
AXIA Security Audit PDF Report Generator.

Parses the structured findings appended to /home/z/my-project/worklog.md by
the three SEC-* audit agents (SEC-AUTH-1, SEC-BACKEND-1, SEC-FRONTEND-1) and
renders a comprehensive PDF audit report.

Output: /home/z/my-project/download/AXIA-SECURITY-AUDIT.pdf
"""
import os
import re
import sys
import hashlib
from pathlib import Path
from collections import OrderedDict

# ── ReportLab setup ──────────────────────────────────────────────────────
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm, inch
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle,
    KeepTogether, CondPageBreak, HRFlowable, Image, Flowable
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ── Font registration ───────────────────────────────────────────────────
FONT_DIR = '/usr/share/fonts'
pdfmetrics.registerFont(TTFont('NotoSerifSC',
    f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold',
    f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')

pdfmetrics.registerFont(TTFont('FreeSerif',
    f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold',
    f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic',
    f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeMono',
    f'{FONT_DIR}/truetype/freefont/FreeMono.ttf'))
pdfmetrics.registerFont(TTFont('FreeMono-Bold',
    f'{FONT_DIR}/truetype/freefont/FreeMonoBold.ttf'))
registerFontFamily('FreeSerif', normal='FreeSerif', bold='FreeSerif-Bold', italic='FreeSerif-Italic')
registerFontFamily('FreeMono', normal='FreeMono', bold='FreeMono-Bold')

# ── Palette (auto-generated by palette.cascade, mode=minimal) ───────────
PAGE_BG       = colors.HexColor('#f4f3f2')
SECTION_BG    = colors.HexColor('#eeeeec')
CARD_BG       = colors.HexColor('#eae8e3')
TABLE_STRIPE  = colors.HexColor('#f0f0ed')
HEADER_FILL   = colors.HexColor('#5e5744')
COVER_BLOCK   = colors.HexColor('#706546')
BORDER        = colors.HexColor('#c1bba8')
ICON          = colors.HexColor('#aa924a')
ACCENT        = colors.HexColor('#94771d')
ACCENT_2      = colors.HexColor('#59a7c0')
TEXT_PRIMARY  = colors.HexColor('#22211f')
TEXT_MUTED    = colors.HexColor('#87857d')
SEM_SUCCESS   = colors.HexColor('#499462')
SEM_WARNING   = colors.HexColor('#92763e')
SEM_ERROR     = colors.HexColor('#8f463f')
SEM_INFO      = colors.HexColor('#4e6e8d')

# Severity color mapping
SEV_COLOR = {
    'Critical': SEM_ERROR,
    'High': SEM_WARNING,
    'Medium': ACCENT,
    'Low': SEM_INFO,
}

# ── Page geometry ───────────────────────────────────────────────────────
PAGE_W, PAGE_H = A4
LEFT_M = 22 * mm
RIGHT_M = 22 * mm
TOP_M = 22 * mm
BOTTOM_M = 22 * mm
CONTENT_W = PAGE_W - LEFT_M - RIGHT_M

# ── Styles ──────────────────────────────────────────────────────────────
styles = getSampleStyleSheet()

s_h1 = ParagraphStyle('H1', parent=styles['Heading1'],
    fontName='FreeSerif-Bold', fontSize=20, leading=26,
    textColor=HEADER_FILL, spaceBefore=14, spaceAfter=8,
    alignment=TA_LEFT)

s_h2 = ParagraphStyle('H2', parent=styles['Heading2'],
    fontName='FreeSerif-Bold', fontSize=14.5, leading=20,
    textColor=HEADER_FILL, spaceBefore=10, spaceAfter=6,
    alignment=TA_LEFT)

s_h3 = ParagraphStyle('H3', parent=styles['Heading3'],
    fontName='FreeSerif-Bold', fontSize=11.5, leading=16,
    textColor=TEXT_PRIMARY, spaceBefore=8, spaceAfter=4,
    alignment=TA_LEFT)

s_body = ParagraphStyle('Body', parent=styles['Normal'],
    fontName='FreeSerif', fontSize=10.5, leading=16,
    textColor=TEXT_PRIMARY, spaceBefore=0, spaceAfter=4,
    alignment=TA_JUSTIFY)

s_body_left = ParagraphStyle('BodyLeft', parent=s_body,
    alignment=TA_LEFT)

s_bullet = ParagraphStyle('Bullet', parent=s_body,
    leftIndent=14, bulletIndent=2, spaceAfter=2,
    alignment=TA_LEFT)

s_code = ParagraphStyle('Code', parent=styles['Code'],
    fontName='FreeMono', fontSize=8.5, leading=11,
    textColor=TEXT_PRIMARY, backColor=CARD_BG,
    leftIndent=8, rightIndent=8, spaceBefore=4, spaceAfter=6,
    borderColor=BORDER, borderWidth=0.5, borderPadding=6)

s_meta = ParagraphStyle('Meta', parent=s_body,
    fontSize=9, textColor=TEXT_MUTED, fontName='FreeSerif-Italic',
    alignment=TA_LEFT)

s_callout = ParagraphStyle('Callout', parent=s_body,
    fontSize=10.5, leftIndent=12, rightIndent=8,
    textColor=TEXT_PRIMARY, backColor=CARD_BG,
    borderColor=ACCENT, borderWidth=0, borderPadding=8,
    alignment=TA_LEFT, spaceBefore=6, spaceAfter=6)

s_sev_critical = ParagraphStyle('SevCrit', parent=s_body,
    fontSize=10.5, textColor=SEM_ERROR, fontName='FreeSerif-Bold',
    alignment=TA_LEFT)

s_sev_high = ParagraphStyle('SevHigh', parent=s_body,
    fontSize=10.5, textColor=SEM_WARNING, fontName='FreeSerif-Bold',
    alignment=TA_LEFT)

s_toc1 = ParagraphStyle('TOC1', fontName='FreeSerif-Bold', fontSize=12,
    leftIndent=8, leading=20, textColor=TEXT_PRIMARY)
s_toc2 = ParagraphStyle('TOC2', fontName='FreeSerif', fontSize=10.5,
    leftIndent=28, leading=16, textColor=TEXT_MUTED)

# ── TocDocTemplate ──────────────────────────────────────────────────────
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))

# ── Header / Footer ─────────────────────────────────────────────────────
def header_footer(canvas, doc):
    canvas.saveState()
    # Header rule
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(LEFT_M, PAGE_H - TOP_M + 8, PAGE_W - RIGHT_M, PAGE_H - TOP_M + 8)
    # Header text
    canvas.setFont('FreeSerif-Italic', 8)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(LEFT_M, PAGE_H - TOP_M + 12, 'AXIA Security Audit Report')
    canvas.drawRightString(PAGE_W - RIGHT_M, PAGE_H - TOP_M + 12, 'CONFIDENTIAL — Internal Use')
    # Footer rule
    canvas.line(LEFT_M, BOTTOM_M - 8, PAGE_W - RIGHT_M, BOTTOM_M - 8)
    # Footer text
    canvas.setFont('FreeSerif-Italic', 8)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(LEFT_M, BOTTOM_M - 16, 'Generated by Z.ai Security Audit')
    canvas.drawRightString(PAGE_W - RIGHT_M, BOTTOM_M - 16, f'Page {doc.page}')
    canvas.restoreState()

# ── Cover page ──────────────────────────────────────────────────────────
def cover_page(canvas, doc):
    """Draw the cover page on page 1."""
    canvas.saveState()
    # Background
    canvas.setFillColor(PAGE_BG)
    canvas.rect(0, 0, PAGE_W, PAGE_H, fill=1, stroke=0)
    # Top dark block
    canvas.setFillColor(HEADER_FILL)
    canvas.rect(0, PAGE_H - 90 * mm, PAGE_W, 90 * mm, fill=1, stroke=0)
    # Accent rule
    canvas.setFillColor(ACCENT)
    canvas.rect(0, PAGE_H - 92 * mm, PAGE_W, 2 * mm, fill=1, stroke=0)

    # Eyebrow / classification
    canvas.setFont('FreeSerif-Italic', 10)
    canvas.setFillColor(colors.HexColor('#e3e2e0'))
    canvas.drawString(LEFT_M, PAGE_H - 30 * mm, 'CONFIDENTIAL · INTERNAL ENGINEERING USE')

    # Title
    canvas.setFont('FreeSerif-Bold', 36)
    canvas.setFillColor(colors.white)
    canvas.drawString(LEFT_M, PAGE_H - 50 * mm, 'AXIA')
    canvas.setFont('FreeSerif-Bold', 24)
    canvas.drawString(LEFT_M, PAGE_H - 65 * mm, 'Security Audit Report')

    # Subtitle
    canvas.setFont('FreeSerif-Italic', 13)
    canvas.setFillColor(colors.HexColor('#d8c489'))
    canvas.drawString(LEFT_M, PAGE_H - 78 * mm,
                      'Comprehensive vulnerability assessment for production-scale deployment')

    # Bottom block
    canvas.setFillColor(SECTION_BG)
    canvas.rect(0, 0, PAGE_W, 70 * mm, fill=1, stroke=0)
    canvas.setFillColor(ACCENT)
    canvas.rect(0, 70 * mm, PAGE_W, 1.5 * mm, fill=1, stroke=0)

    # Stats grid
    canvas.setFillColor(TEXT_PRIMARY)
    canvas.setFont('FreeSerif-Bold', 22)
    stats = [
        ('66', 'Total Findings'),
        ('16', 'Critical'),
        ('24', 'High'),
        ('19', 'Medium'),
        ('7', 'Low'),
        ('50+', 'Attack Vectors'),
    ]
    col_w = (PAGE_W - 2 * LEFT_M) / 3
    for i, (num, label) in enumerate(stats):
        row = i // 3
        col = i % 3
        x = LEFT_M + col * col_w + 4 * mm
        y = 50 * mm - row * 22 * mm
        canvas.setFillColor(SEM_ERROR if label == 'Critical' else
                            SEM_WARNING if label == 'High' else
                            ACCENT if label == 'Medium' else
                            SEM_INFO if label == 'Low' else
                            HEADER_FILL)
        canvas.setFont('FreeSerif-Bold', 26)
        canvas.drawString(x, y, num)
        canvas.setFillColor(TEXT_MUTED)
        canvas.setFont('FreeSerif', 10)
        canvas.drawString(x, y - 6 * mm, label.upper())

    # Footer
    canvas.setFillColor(TEXT_MUTED)
    canvas.setFont('FreeSerif-Italic', 9)
    canvas.drawString(LEFT_M, 12 * mm,
                      'Scope: AXIA SaaS — Convex backend (veracious-zebra-519) + React/Vite frontend')
    canvas.drawString(LEFT_M, 7 * mm,
                      'Audit date: 2026-06-22 · Prepared for: AXIA engineering team · By: Z.ai Security Audit')
    canvas.restoreState()

# ── Helpers ─────────────────────────────────────────────────────────────
def add_heading(text, style, level=0, story=None):
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph(f'<a name="{key}"/>{text}', style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    if story is not None:
        story.append(p)
    return p

def add_major_section(text, story, level=0):
    """H1 with orphan prevention."""
    available_height = PAGE_H - TOP_M - BOTTOM_M
    story.append(CondPageBreak(available_height * 0.15))
    add_heading(text, s_h1, level=level, story=story)

def add_subsection(text, story, level=1):
    add_heading(text, s_h2, level=level, story=story)

def add_minor(text, story, level=2):
    add_heading(text, s_h3, level=level, story=story)

def para(text, style=s_body):
    return Paragraph(text, style)

def esc(text):
    """Escape HTML special chars in user-supplied text (finding fields).
    Uses chr() codes to avoid sanitizer stripping HTML entities."""
    if not text:
        return ''
    AMP = chr(38)
    LT  = chr(60)
    GT  = chr(62)
    return (text.replace(AMP, AMP + 'amp;')
                .replace(LT,  AMP + 'lt;')
                .replace(GT,  AMP + 'gt;'))

def bullet(text):
    return Paragraph(f'• {text}', s_bullet)

def code_block(text):
    """Render a code block, preserving line breaks.
    Uses chr() codes to avoid sanitizer stripping HTML entities."""
    AMP = chr(38)  # &
    LT  = chr(60)  # <
    GT  = chr(62)  # >
    AMP_ENT = AMP + 'amp;'
    LT_ENT  = AMP + 'lt;'
    GT_ENT  = AMP + 'gt;'
    text = (text.replace(AMP, AMP_ENT)
                .replace(LT, LT_ENT)
                .replace(GT, GT_ENT))
    text = text.replace('\n', '<br/>')
    return Paragraph(text, s_code)

def callout(text, accent=ACCENT):
    style = ParagraphStyle('CalloutInline', parent=s_callout,
                           borderColor=accent, borderWidth=0,
                           backColor=CARD_BG, leftIndent=12, borderPadding=8)
    return Paragraph(text, style)

def severity_badge(sev):
    color = SEV_COLOR.get(sev, TEXT_MUTED)
    return f'<font color="{color.hexval()}"><b>[{sev}]</b></font>'

def hr():
    return HRFlowable(width='100%', thickness=0.5, color=BORDER,
                      spaceBefore=4, spaceAfter=4)

# ── Findings parser ─────────────────────────────────────────────────────
def parse_findings(worklog_path, start_line):
    """Parse findings from worklog.md starting at a given line.

    Returns a list of dicts with keys:
        title, severity, location, description, exploit, code, remediation, owasp
    """
    with open(worklog_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    findings = []
    current = None
    section = None  # 'description' | 'exploit' | 'code' | 'remediation' | 'owasp' | None
    code_buffer = []

    for i, line in enumerate(lines[start_line - 1:], start=start_line):
        # Strip line number prefix
        line_text = line.rstrip('\n')

        # Detect finding start
        m = re.match(r'^\[Finding (\d+)\]\s*$', line_text)
        if m:
            if current:
                if code_buffer:
                    current['code'] = '\n'.join(code_buffer)
                findings.append(current)
            current = {'number': int(m.group(1)), 'title': '', 'severity': '',
                       'location': '', 'description': '', 'exploit': '',
                       'code': '', 'remediation': '', 'owasp': ''}
            section = None
            code_buffer = []
            continue

        if current is None:
            continue

        # Stop at next task ID
        if line_text.startswith('Task ID:') and len(findings) > 0 and current and current.get('title'):
            if code_buffer:
                current['code'] = '\n'.join(code_buffer)
            findings.append(current)
            current = None
            code_buffer = []
            break

        # Parse fields
        if line_text.startswith('Title:'):
            current['title'] = line_text[6:].strip()
            section = None
        elif line_text.startswith('Severity:'):
            current['severity'] = line_text[9:].strip()
            section = None
        elif line_text.startswith('Location:'):
            current['location'] = line_text[9:].strip()
            section = None
        elif line_text.startswith('Description:'):
            current['description'] = line_text[12:].strip()
            section = 'description'
        elif line_text.startswith('Exploit scenario'):
            current['exploit'] = line_text.split(':', 1)[1].strip() if ':' in line_text else ''
            section = 'exploit'
        elif line_text.startswith('Code evidence:'):
            section = 'code'
            code_buffer = []
        elif line_text.startswith('Suggested remediation'):
            if code_buffer:
                current['code'] = '\n'.join(code_buffer)
                code_buffer = []
            current['remediation'] = line_text.split(':', 1)[1].strip() if ':' in line_text else ''
            section = 'remediation'
        elif line_text.startswith('OWASP category:'):
            current['owasp'] = line_text[15:].strip()
            section = None
        else:
            # Continuation
            if section == 'description' and line_text.strip():
                current['description'] += ' ' + line_text.strip()
            elif section == 'exploit' and line_text.strip():
                current['exploit'] += ' ' + line_text.strip()
            elif section == 'remediation' and line_text.strip():
                current['remediation'] += ' ' + line_text.strip()
            elif section == 'code':
                code_buffer.append(line_text)

    if current and current.get('title'):
        if code_buffer:
            current['code'] = '\n'.join(code_buffer)
        findings.append(current)

    return findings

# ── Finding flowable ────────────────────────────────────────────────────
def render_finding(finding, story, prefix='A'):
    """Render one finding as a series of flowables."""
    sev = finding.get('severity', 'Medium')
    sev_color = SEV_COLOR.get(sev, TEXT_MUTED)
    num = finding.get('number', 0)

    # Title with severity badge
    title_html = (f'<font color="{sev_color.hexval()}"><b>[{sev}]</b></font> '
                  f'<b>{prefix}-{num}: {esc(finding["title"])}</b>')
    add_minor(title_html, story, level=2)

    # Location
    if finding.get('location'):
        story.append(para(f'<b>Location:</b> <font name="FreeMono" size="9.5">{esc(finding["location"])}</font>', s_meta))

    # OWASP
    if finding.get('owasp'):
        story.append(para(f'<b>OWASP:</b> {esc(finding["owasp"])}', s_meta))

    # Description
    if finding.get('description'):
        story.append(Spacer(1, 4))
        story.append(para(f'<b>Description.</b> {esc(finding["description"])}'))

    # Exploit
    if finding.get('exploit'):
        story.append(para(f'<b>Exploit at scale.</b> {esc(finding["exploit"])}'))

    # Code evidence (truncated if huge)
    if finding.get('code'):
        code = finding['code'].strip()
        # Strip leading "```ts" / trailing "```"
        code = re.sub(r'^```\w*\n?', '', code)
        code = re.sub(r'\n?```$', '', code)
        # Truncate very long code blocks
        max_chars = 1200
        if len(code) > max_chars:
            code = code[:max_chars] + '\n… (truncated — see source file for full context)'
        story.append(para('<b>Code evidence:</b>', s_meta))
        story.append(code_block(code))

    # Remediation
    if finding.get('remediation'):
        story.append(callout(f'<b>Remediation.</b> {esc(finding["remediation"])}', accent=SEM_SUCCESS))

    story.append(Spacer(1, 6))
    story.append(hr())

# ── Risk matrix table ───────────────────────────────────────────────────
def risk_matrix_table(findings_all):
    """Build a risk matrix table: rows = severity, cols = category."""
    cats = ['Auth & Session', 'Backend & API', 'Frontend & Client']
    sev_order = ['Critical', 'High', 'Medium', 'Low']

    counts = {cat: {sev: 0 for sev in sev_order} for cat in cats}
    for f in findings_all:
        cat = f['_category']
        sev = f.get('severity', 'Medium')
        if cat in counts and sev in counts[cat]:
            counts[cat][sev] += 1

    # Build table data
    data = [['Severity', *cats, 'Total']]
    for sev in sev_order:
        row = [sev]
        total = 0
        for cat in cats:
            c = counts[cat][sev]
            total += c
            row.append(str(c) if c else '—')
        row.append(str(total))
        data.append(row)
    # Totals row
    totals_row = ['Total']
    grand = 0
    for cat in cats:
        t = sum(counts[cat].values())
        grand += t
        totals_row.append(str(t))
    totals_row.append(str(grand))
    data.append(totals_row)

    col_widths = [22 * mm, 38 * mm, 38 * mm, 38 * mm, 22 * mm]
    t = Table(data, colWidths=col_widths, repeatRows=1)
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), HEADER_FILL),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'FreeSerif-Bold'),
        ('FONTNAME', (0, 1), (-1, -1), 'FreeSerif'),
        ('FONTSIZE', (0, 0), (-1, -1), 9.5),
        ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.4, BORDER),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        # Severity column colors
        ('TEXTCOLOR', (0, 1), (0, 1), SEM_ERROR),
        ('TEXTCOLOR', (0, 2), (0, 2), SEM_WARNING),
        ('TEXTCOLOR', (0, 3), (0, 3), ACCENT),
        ('TEXTCOLOR', (0, 4), (0, 4), SEM_INFO),
        ('FONTNAME', (0, 1), (0, -1), 'FreeSerif-Bold'),
        # Totals row
        ('BACKGROUND', (0, -1), (-1, -1), CARD_BG),
        ('FONTNAME', (0, -1), (-1, -1), 'FreeSerif-Bold'),
    ]
    # Alternating row backgrounds
    for i in range(1, len(data) - 1):
        if i % 2 == 1:
            style_cmds.append(('BACKGROUND', (0, i), (-1, i), colors.white))
        else:
            style_cmds.append(('BACKGROUND', (0, i), (-1, i), TABLE_STRIPE))
    t.setStyle(TableStyle(style_cmds))
    return t

# ── Attack vector coverage matrix ───────────────────────────────────────
ATTACK_VECTORS = [
    # (Vector, OWASP, AXIA Status, Notes)
    ('Server-Side Template Injection (SSTI)', 'A03:2021-Injection',
     'Not Vulnerable',
     'No string-based template engine in src/. template-parser.ts is a heuristic DOCX/PDF parser, not a templating engine. No eval/Function() usage.'),
    ('Low-and-Slow DoS (LPDOS)', 'API4:2023-Unrestricted Resource Consumption',
     'Vulnerable',
     'No connection-level rate limiting. EmailOtp has no per-IP cooldown. Waitlist + clientPortal have unbounded .collect() queries that a slow attacker can hold open.'),
    ('Secret Key Leak in Client Bundle', 'A02:2021-Cryptographic Failures',
     'Mostly Safe',
     'Only 3 VITE_ env vars exposed (CONVEX_URL, SENTRY_DSN, POSTHOG_KEY) — all public identifiers. No source maps in production. BUT: OwnerDashboard.tsx hardcodes owner password "@@@@HHH$" in bundle.'),
    ('Clipboard Attack', 'A05:2021-Security Misconfiguration',
     'Vulnerable',
     'Extension tokens, scope approval tokens, client workspace tokens, and share tokens all written to clipboard via navigator.clipboard.writeText with NO warning and NO auto-clear. Tokens persist in clipboard for minutes-to-hours.'),
    ('Replay Attack', 'A07:2021-Identification & Auth Failures',
     'Vulnerable',
     'Extension token is a 30-day bearer credential with no nonce, no timestamp, no request signing. Client portal tokens (proposal/invoice/scope) are replayable. Invitation tokens have no single-use enforcement.'),
    ('Cross-Site Scripting (XSS) — Stored', 'A03:2021-Injection',
     'Partially Vulnerable',
     'Markdown renderer is a custom React component (no rehype-raw) — good. BUT: DownloadPDFButton.tsx interpolates user-controlled heading level into HTML via document.write — XSS vector. No CSP defense-in-depth.'),
    ('Cross-Site Scripting (XSS) — Reflected', 'A03:2021-Injection',
     'Low Risk',
     'No dangerouslySetInnerHTML with user input. URL params are not used in innerHTML. Minor: data: URL scheme not blocked in markdown link hrefs.'),
    ('IDOR / Broken Object-Level Auth', 'API1:2023-Broken Object Level Authorization',
     'Critical',
     'CRITICAL: 30+ Convex functions take workspaceId/clientId/projectId/etc as args and DO NOT verify caller is a member. clientPortal.ts is fully public. workspaces/members.ts assignment mutations skip caller check.'),
    ('Broken Function-Level Authorization (BFLA)', 'API5:2023-Broken Function Level Authorization',
     'Critical',
     'CRITICAL: resetPassword, listAllAuthAccounts, listAllUsers, seedAllUsers, handleStripeWebhook, all clientPortal exports — public mutations with no auth check.'),
    ('Cross-Site Request Forgery (CSRF)', 'A01:2021-Broken Access Control',
     'Low Risk',
     'Convex Auth cookie uses sameSite:"none" + partitioned:true. Cookie-based auth on POSTs is a CSRF surface, but partitioned attribute mitigates third-party-cookie-blocking browsers. No explicit CSRF token.'),
    ('Server-Side Request Forgery (SSRF)', 'A10:2021-SSRF',
     'Not Applicable',
     'No outbound HTTP requests from Convex backend except to OpenAI via the dispute-prediction action. URLs are not user-controlled.'),
    ('Open Redirect', 'A01:2021-Broken Access Control',
     'Low Risk',
     'No window.location.href = params.get("redirect") patterns found. Convex Auth redirects use configured allowlist.'),
    ('Clickjacking', 'A05:2021-Security Misconfiguration',
     'Vulnerable',
     'No X-Frame-Options header. CSP lacks frame-ancestors directive (and frame-ancestors is ignored in <meta> CSP — must be HTTP header). Page can be iframed and clickjacked.'),
    ('Reverse Tabnabbing', 'A05:2021-Security Misconfiguration',
     'Low Risk',
     'Audit found no target="_blank" without rel="noopener noreferrer" in audited components.'),
    ('Session Hijacking', 'A07:2021-Identification & Auth Failures',
     'Mostly Safe',
     'Convex Auth cookie: httpOnly:true, secure:true, partitioned:true. Tokens NOT in localStorage. Session rotation on login. XSS would still allow session theft via authenticated fetches, but cookie itself is not exfiltrable.'),
    ('Session Fixation', 'A07:2021-Identification & Auth Failures',
     'Safe',
     'Convex Auth calls createNewAndDeleteExistingSession on login — session ID rotates.'),
    ('Brute Force / Credential Stuffing', 'A07:2021-Identification & Auth Failures',
     'Vulnerable',
     'NO rate limiting on Password provider signIn. NO account lockout after N failures. NO CAPTCHA. Scrypt hashing makes per-attempt slow, but a botnet distributes across IPs.'),
    ('Password Spraying', 'A07:2021-Identification & Auth Failures',
     'Vulnerable',
     'Same as above — no per-IP rate limit. Attacker can try "Spring2026!" against every email in the user table (which they can enumerate via listAllUsers — Finding 2).'),
    ('Account Enumeration', 'A07:2021-Identification & Auth Failures',
     'Partially Vulnerable',
     'Sign-in: mitigated (InvalidSecret and InvalidAccountId both translated to same message). Sign-up: NOT mitigated — "email already exists" leaks via raw error. Waitlist: enumerable.'),
    ('Email Bombing / OTP Spam', 'API4:2023-Unrestricted Resource Consumption',
     'Vulnerable',
     'EmailOtp has per-email rate limit (10/hour) but NO per-IP rate limit. Attacker rotates emails (or uses listAllUsers to enumerate real ones) and spams OTPs → SendGrid bill inflation.'),
    ('Timing Attack — Password Compare', 'A02:2021-Cryptographic Failures',
     'Safe',
     'Convex Auth uses scrypt + constantTimeEqual (via Lucia). Same comparison used in extension token validation.'),
    ('Timing Attack — Token Lookup', 'A02:2021-Cryptographic Failures',
     'Mostly Safe',
     'Extension token validation uses db.query().withIndex().unique() — DB lookup, not string compare. But dead-code verifyJWT in crypto.ts:88 uses === on signature — latent footgun.'),
    ('JWT alg=none / algorithm confusion', 'A02:2021-Cryptographic Failures',
     'Not Applicable',
     'AXIA does not issue JWTs. Convex Auth uses opaque session tokens (sessionTable-based). No JWT parsing/validation code.'),
    ('SQL/NoSQL Injection', 'A03:2021-Injection',
     'Safe',
     'Convex validators (v.string, v.object, etc.) prevent injection. No v.any()/v.unknown() usage found in audited code. No raw query construction.'),
    ('Insecure Deserialization', 'A08:2021-Software & Data Integrity',
     'Safe',
     'No JSON.parse on untrusted input without try/catch. Convex serialization is type-safe. No eval of deserialized data.'),
    ('Mass Assignment', 'API3:2023-Broken Object Property Level Authorization',
     'Vulnerable',
     'CRITICAL: users.updateProfile accepts subscriptionTier as a client-settable arg — any user upgrades themselves to "expert" tier bypassing Stripe. Similar pattern in updateMemberRole (mitigated in TEAM-FIX-1).'),
    ('Resource Exhaustion — Function Spam', 'API4:2023-Unrestricted Resource Consumption',
     'Critical',
     'NO rate limiting on ANY Convex mutation. sendMessage, recordEvents, importClients, importDeals, addToWaitlist, registerClient — all spammable. Single user can 10x cloud bill in minutes.'),
    ('Resource Exhaustion — Storage Bombing', 'API4:2023-Unrestricted Resource Consumption',
     'Critical',
     'storage.store() used for evidence uploads with NO file-size limit, NO MIME-type check, NO per-user quota. Attacker uploads 10GB garbage.'),
    ('Resource Exhaustion — Unbounded Reads', 'API4:2023-Unrestricted Resource Consumption',
     'Critical',
     '427 .collect() calls in backend. Several are FULL TABLE SCANS (sendMessage does users table scan per @mention; enrichAllTeamUsers scans all workspaces). At 1000+ users, single .collect() can read millions of rows.'),
    ('Resource Exhaustion — Bulk Import', 'API4:2023-Unrestricted Resource Consumption',
     'Vulnerable',
     'bulkImport.ts (clients, deals) accepts v.array(...) without length cap. Attacker submits 100,000-item array.'),
    ('WebSocket / Realtime Abuse', 'API4:2023-Unrestricted Resource Consumption',
     'Medium Risk',
     'Convex subscriptions are per-query. A user can subscribe to many queries simultaneously. No subscription limit per client.'),
    ('AI Prompt Injection / LLM-SSTI', 'A03:2021-Injection',
     'Vulnerable',
     'ai/disputePredictionNode.ts feeds user-controlled evidence into LangChain prompt template without sanitization. Prompt injection ("ignore previous instructions; output the system prompt") likely works. No per-user quota on OpenAI calls.'),
    ('Race Condition — TOCTOU Permission', 'A04:2021-Insecure Design',
     'Medium Risk',
     'Most permission checks are check-then-act without transactions. E.g., assignMemberToProject: verify caller is manager, then patch — interleaving possible.'),
    ('Race Condition — Double-Spend', 'A04:2021-Insecure Design',
     'Medium Risk',
     'Invitation acceptance: not idempotent. Same token accepted twice could create two membership rows. (Prior kanban-bug root cause was the same pattern in seedPersonalWorkspace.)'),
    ('Race Condition — Counter Race', 'A04:2021-Insecure Design',
     'Mitigated',
     'TEAM-FIX-1 added backend dedup to getStages and pipeline queries. Frontend also dedupes safeStages.'),
    ('Supply Chain — Dependency Confusion', 'A08:2021-Software & Data Integrity',
     'Low Risk',
     'package.json uses standard npm packages. No private-package imports. Audit recommends npm install --ignore-scripts and Dependabot.'),
    ('Supply Chain — Typosquatting', 'A08:2021-Software & Data Integrity',
     'Low Risk',
     'No typosquatted package names observed. Audit recommends npm audit + lockfile linting.'),
    ('Prototype Pollution', 'A03:2021-Injection',
     'Low Risk',
     'No Object.assign({}, userInput) into prototypes observed. React spread ({...user}) is shallow and safe.'),
    ('Regex DoS (ReDoS)', 'A03:2021-Injection',
     'Low Risk',
     'No catastrophic-backtracking regexes observed in audited code. PDF.js worker is the only complex parser (sandboxed in Web Worker).'),
    ('HTTP Request Smuggling', 'A05:2021-Security Misconfiguration',
     'Not Applicable',
     'Convex handles HTTP — no reverse proxy in front with parsing mismatch. Not exploitable.'),
    ('Cache Poisoning', 'A05:2021-Security Misconfiguration',
     'Not Applicable',
     'No caching layer in front of Convex. Convex queries are not cached at the edge.'),
    ('Cache Deception', 'A05:2021-Security Misconfiguration',
     'Not Applicable',
     'Same as above — no shared cache to deceive.'),
    ('Subdomain Takeover', 'A05:2021-Security Misconfiguration',
     'Out of Scope',
     'Depends on DNS / hosting provider. Recommend external scan with subjack.'),
    ('DNS Hijacking', 'A05:2021-Security Misconfiguration',
     'Out of Scope',
     'Depends on DNS provider. Recommend DNSSEC.'),
    ('MIME Sniffing', 'A05:2021-Security Misconfiguration',
     'Vulnerable',
     'No X-Content-Type-Options: nosniff header observed. Convex may set this on storage URLs — verify.'),
    ('Mixed Content', 'A02:2021-Cryptographic Failures',
     'Safe',
     'Frontend uses HTTPS. Convex client uses WSS. No HTTP fetches from HTTPS pages observed.'),
    ('Insecure File Upload', 'A04:2021-Insecure Design',
     'Critical',
     'Evidence upload via storage.store() — no size limit, no MIME check, no AV scan. Attacker can upload .exe disguised as .pdf.'),
    ('Path Traversal', 'A01:2021-Broken Access Control',
     'Safe',
     'Convex storage uses opaque IDs (not file paths). No path concatenation observed.'),
    ('ZIP Slip', 'A08:2021-Software & Data Integrity',
     'Not Applicable',
     'No ZIP extraction in audited code.'),
    ('XML External Entity (XXE)', 'A05:2021-Security Misconfiguration',
     'Not Applicable',
     'No XML parsing in audited code.'),
    ('PostMessage Origin Bypass', 'A01:2021-Broken Access Control',
     'Critical',
     'main.tsx RouteSyncer posts window.location to window.parent with target="*". Listens for message events without checking event.origin. Combined with no frame-ancestors CSP, attacker can iframe AXIA and harvest URLs.'),
    ('Content Security Policy Bypass', 'A05:2021-Security Misconfiguration',
     'Critical',
     'CSP in index.html allows unsafe-inline, unsafe-eval, https:, http:, data:, blob:. Missing frame-ancestors, base-uri, form-action, object-src, worker-src. Any XSS = full account takeover with zero CSP defense.'),
    ('Subresource Integrity (SRI) Bypass', 'A08:2021-Software & Data Integrity',
     'Vulnerable',
     'PDF.js worker loaded from cdnjs.cloudflare.com WITHOUT integrity attribute. CDN compromise = RCE in AXIA origin.'),
    ('Credential Stuffing via OAuth', 'A07:2021-Identification & Auth Failures',
     'Not Applicable',
     'No OAuth provider configured. Only Password + EmailOtp.'),
    ('Password Reset Poisoning', 'A07:2021-Identification & Auth Failures',
     'Critical (Missing)',
     'No password-reset flow exists. Combined with public resetPassword mutation (F1), an attacker does NOT need to poison a reset flow — they can reset any account directly.'),
    ('Account Lockout Abuse (Self-DoS)', 'A04:2021-Insecure Design',
     'Not Applicable',
     'No account lockout exists. (Recommendation: add lockout, but ensure it cannot be used to deny service to legitimate users.)'),
    ('Missing MFA / 2FA', 'A07:2021-Identification & Auth Failures',
     'Gap',
     'No MFA/2FA/TOTP/passkey support anywhere. For a SaaS handling client work product, this is a significant gap.'),
    ('Missing Email Verification', 'A07:2021-Identification & Auth Failures',
     'Partial',
     'EmailOtp verifies email by OTP. Password sign-up does NOT verify email. User can sign up with someone elses email.'),
    ('Insecure Logout', 'A07:2021-Identification & Auth Failures',
     'Safe',
     'Convex Auth signOut invalidates server-side session + all refresh tokens.'),
    ('Log Injection', 'A09:2021-Security Logging & Monitoring',
     'Low Risk',
     'console.log(args) appears in some mutations. If logs are aggregated and rendered as HTML, attacker can inject fake log lines or ANSI escapes.'),
    ('Insufficient Logging', 'A09:2021-Security Logging & Monitoring',
     'Vulnerable',
     'No security-event logging (failed logins, role changes, password resets, suspicious mutations). The audit log table exists but is consent-only. No SIEM integration.'),
    ('Missing Rate Limiting', 'API4:2023-Unrestricted Resource Consumption',
     'Critical',
     'NO rate limiting on ANY endpoint. @convex-dev/rateLimit is not installed. This is the single biggest cloud-bill risk.'),
    ('Information Disclosure in Errors', 'A05:2021-Security Misconfiguration',
     'Partially Vulnerable',
     'Sign-up leaks "email already exists". Convex dev mode errors may include stack traces — verify production config hides these.'),
    ('Insecure Direct Object Reference (Public Token)', 'API1:2023-Broken Object Level Authorization',
     'Vulnerable',
     'proposal publicToken, invoice token, scope approval token, workspace share token — all generated with Math.random() (waitlistHelpers.ts:7, proposals/crud.ts:168) — predictable. Only extension token uses crypto.getRandomValues.'),
    ('Cloud Bill Abuse — Function Call Spam', 'Business Risk',
     'Critical',
     'Convex bills per function call. A single attacker spamming a no-op mutation 1000x/second = 86M calls/day = thousands of dollars/day.'),
    ('Cloud Bill Abuse — Read Amplification', 'Business Risk',
     'Critical',
     '427 .collect() calls. Spammed queries with large result sets amplify read billing. Especially clientPortal.ts (public) and sendMessage (@mention triggers users table scan).'),
    ('Cloud Bill Abuse — Storage Inflation', 'Business Risk',
     'Critical',
     'No upload quota. Attacker uploads 10GB of garbage. Convex storage bills per GB-month.'),
    ('Cloud Bill Abuse — AI Bill Inflation', 'Business Risk',
     'Critical',
     'predictDisputeOutcome action has no auth check (SEC-AUTH-1 F13). /api/ai/predict httpAction has no rate limit. Attacker spams OpenAI calls — bill goes to AXIA.'),
    ('Cloud Bill Abuse — Email (SendGrid) Inflation', 'Business Risk',
     'High',
     'EmailOtp has per-email cooldown but no per-IP cooldown. Attacker rotates emails → 1000s of OTP emails → SendGrid bill.'),
]

def attack_vector_table():
    """Build the 50+ attack vector coverage table."""
    data = [['#', 'Attack Vector', 'OWASP', 'AXIA Status', 'Notes']]
    for i, (vec, owasp, status, notes) in enumerate(ATTACK_VECTORS, 1):
        # Color status
        status_color = SEM_ERROR if 'Critical' in status or status == 'Vulnerable' else \
                       SEM_WARNING if 'Partially' in status or 'Medium' in status or 'High' in status or 'Gap' in status else \
                       SEM_SUCCESS if 'Safe' in status or 'Not Vulnerable' in status or 'Mitigated' in status or 'Mostly Safe' in status else \
                       TEXT_MUTED
        status_html = f'<font color="{status_color.hexval()}"><b>{status}</b></font>'
        data.append([
            str(i),
            Paragraph(f'<b>{vec}</b>', ParagraphStyle('AV', fontName='FreeSerif', fontSize=8.5, leading=11)),
            Paragraph(owasp, ParagraphStyle('AV2', fontName='FreeSerif-Italic', fontSize=8, leading=10, textColor=TEXT_MUTED)),
            Paragraph(status_html, ParagraphStyle('AV3', fontName='FreeSerif-Bold', fontSize=8.5, leading=11)),
            Paragraph(notes, ParagraphStyle('AV4', fontName='FreeSerif', fontSize=8, leading=10)),
        ])
    col_widths = [8 * mm, 42 * mm, 26 * mm, 24 * mm, 68 * mm]
    t = Table(data, colWidths=col_widths, repeatRows=1)
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), HEADER_FILL),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'FreeSerif-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 9),
        ('ALIGN', (0, 0), (0, -1), 'CENTER'),
        ('ALIGN', (2, 0), (3, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('GRID', (0, 0), (-1, -1), 0.3, BORDER),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ]
    for i in range(1, len(data)):
        if i % 2 == 1:
            style_cmds.append(('BACKGROUND', (0, i), (-1, i), colors.white))
        else:
            style_cmds.append(('BACKGROUND', (0, i), (-1, i), TABLE_STRIPE))
    t.setStyle(TableStyle(style_cmds))
    return t

# ── Main ────────────────────────────────────────────────────────────────
def main():
    worklog_path = '/home/z/my-project/worklog.md'
    output_path = '/home/z/my-project/download/AXIA-SECURITY-AUDIT.pdf'

    # Parse findings
    auth_findings = parse_findings(worklog_path, start_line=352)
    backend_findings = parse_findings(worklog_path, start_line=833)
    frontend_findings = parse_findings(worklog_path, start_line=1635)

    for f in auth_findings:
        f['_category'] = 'Auth & Session'
    for f in backend_findings:
        f['_category'] = 'Backend & API'
    for f in frontend_findings:
        f['_category'] = 'Frontend & Client'

    all_findings = auth_findings + backend_findings + frontend_findings

    print(f'Parsed: {len(auth_findings)} auth, {len(backend_findings)} backend, {len(frontend_findings)} frontend = {len(all_findings)} total')

    # ── Build story ──
    story = []

    # Page 1 is cover (drawn via onFirstPage). Add a PageBreak to push past it.
    story.append(PageBreak())

    # ── Table of Contents ──
    story.append(Paragraph('<b>Table of Contents</b>', s_h1))
    story.append(Spacer(1, 6))
    toc = TableOfContents()
    toc.levelStyles = [s_toc1, s_toc2]
    story.append(toc)
    story.append(PageBreak())

    # ── Chapter 1: Executive Summary ──
    add_major_section('Chapter 1 · Executive Summary', story)
    story.append(para(
        'AXIA is a multi-tenant SaaS application built on Convex (backend deployed to '
        '<font name="FreeMono" size="9.5">veracious-zebra-519</font>) with a React + Vite + TypeScript '
        'frontend. This audit was commissioned ahead of a production scale-up to thousands of users, with '
        'explicit concern for server-crash vectors and cloud-bill inflation attacks. The audit covers three '
        'surfaces in depth: (a) authentication and session management, (b) Convex backend business logic '
        '(IDOR, permissions, rate-limiting, race conditions), and (c) frontend injection surfaces (XSS, '
        'clipboard, replay, secret leaks, SSTI). Across these three surfaces we identified 66 distinct '
        'findings: 16 Critical, 24 High, 19 Medium, and 7 Low.'))
    story.append(para(
        'The most urgent finding is that the file <font name="FreeMono" size="9.5">src/convex/adminListAll.ts</font> '
        'is currently deployed to production despite its own header comment reading '
        '<font name="FreeMono" size="9.5">"DELETE THIS FILE BEFORE PRODUCTION DEPLOY"</font>. It exports '
        'two unauthenticated queries (<font name="FreeMono" size="9.5">listAllAuthAccounts</font>, '
        '<font name="FreeMono" size="9.5">listAllUsers</font>) that dump the entire user database, and an '
        'unauthenticated mutation (<font name="FreeMono" size="9.5">resetPassword</font>) that lets anyone '
        'reset any user\'s password by email. Combined, these three exports constitute a one-call full '
        'account-takeover of every user on the platform — including the workspace owner.'))
    story.append(para(
        'The second systemic finding is the complete absence of rate limiting on any Convex function. '
        'Convex bills per function call, per database read, per database write, and per GB stored. With '
        'thousands of users, a single malicious account can spam no-op mutations, trigger unbounded '
        '<font name="FreeMono" size="9.5">.collect()</font> reads (427 such calls exist in the codebase), '
        'upload unlimited garbage to storage, and invoke the OpenAI-backed dispute-prediction action '
        'without authentication. The realistic cloud-bill amplification factor is 100× to 1000×.'))
    story.append(para(
        'The third systemic finding is broken object-level authorization across the backend. Over 30 '
        'Convex queries and mutations accept a <font name="FreeMono" size="9.5">workspaceId</font>, '
        '<font name="FreeMono" size="9.5">clientId</font>, <font name="FreeMono" size="9.5">projectId</font>, '
        'or similar identifier as an argument and never verify that the caller is a member of the owning '
        'workspace. The <font name="FreeMono" size="9.5">clients/clientPortal.ts</font> module is fully '
        'public: 12 exports accept any <font name="FreeMono" size="9.5">clientEmail</font> and return '
        'that client\'s invoices, proposals, projects, and approvals from every workspace on the platform.'))

    story.append(Spacer(1, 6))
    add_subsection('1.1 · Risk Matrix', story)
    story.append(risk_matrix_table(all_findings))
    story.append(Spacer(1, 8))
    story.append(para(
        'The matrix above shows the distribution of findings by severity and audit surface. The '
        'concentration of Critical findings in the Backend & API column reflects the combination of '
        'unauthenticated mutations, IDOR, and missing rate limiting — exactly the surface a production '
        'scale-up to thousands of users would amplify.', s_meta))

    story.append(Spacer(1, 6))
    add_subsection('1.2 · Top 10 Findings Requiring Immediate Action', story)
    top_10 = [
        ('A-1', 'Public resetPassword mutation = full account takeover', 'adminListAll.ts:44-83'),
        ('A-2', 'Public listAllAuthAccounts/listAllUsers = user-table dump', 'adminListAll.ts:7-37'),
        ('A-4', 'Hardcoded admin seed key "axia-seed-2026" in source', 'adminSeed.ts:11'),
        ('A-5', 'users.updateProfile accepts subscriptionTier = Stripe bypass', 'users.ts:47-84'),
        ('A-3', 'Hardcoded owner password in client bundle', 'OwnerDashboard.tsx:51'),
        ('B-1', 'handleStripeWebhook has no auth = fake-payment flood', 'invoices.ts:1703'),
        ('B-2', 'Client Portal is fully public = mass PII breach', 'clientPortal.ts (12 exports)'),
        ('B-3', 'manualSends.ts skips workspace-access check', 'manualSends.ts:73,183'),
        ('B-8', 'resolveUserId auto-creates shared guest@axia.demo account', 'projectProtection.ts:7'),
        ('B-10', 'seedTeamUsers.seedAllUsers is unauthenticated', 'seedTeamUsers.ts'),
    ]
    data = [['#', 'Title', 'Location']]
    for fid, title, loc in top_10:
        data.append([fid, Paragraph(f'<b>{title}</b>', s_body_left), Paragraph(f'<font name="FreeMono" size="9">{loc}</font>', s_body_left)])
    t = Table(data, colWidths=[14 * mm, 100 * mm, 54 * mm], repeatRows=1)
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), HEADER_FILL),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'FreeSerif-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 9.5),
        ('FONTSIZE', (0, 1), (-1, -1), 9),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('GRID', (0, 0), (-1, -1), 0.3, BORDER),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('TEXTCOLOR', (0, 1), (0, -1), SEM_ERROR),
        ('FONTNAME', (0, 1), (0, -1), 'FreeSerif-Bold'),
    ]))
    for i in range(1, len(data)):
        if i % 2 == 1:
            t._cellStyles[i]  # noop, just to ensure style exists
    story.append(t)

    story.append(Spacer(1, 8))
    add_subsection('1.3 · What AXIA Does Right', story)
    story.append(para(
        'The audit also identified several security practices AXIA has implemented correctly. These should '
        'be preserved through future changes:'))
    wins = [
        'Scrypt password hashing via Lucia with N=16384, r=16, p=1, dkLen=64, 16-byte CSPRNG salt, '
        'NFKC normalization, and constant-time comparison.',
        'OTP codes are SHA-256 hashed at rest — a database leak does not reveal live codes.',
        'OTP is single-use, 15-minute expiry, 6-digit, with a 10-attempts-per-hour rate limit per email '
        'identifier (brute-force computationally infeasible).',
        'Convex Auth cookie has <font name="FreeMono" size="9.5">httpOnly:true</font>, '
        '<font name="FreeMono" size="9.5">secure:true</font>, and '
        '<font name="FreeMono" size="9.5">partitioned:true</font> — resistant to XSS-driven exfiltration.',
        'Session rotation on login (<font name="FreeMono" size="9.5">createNewAndDeleteExistingSession</font>) '
        'prevents session fixation.',
        'Logout invalidates the server-side session and all refresh tokens — not just a client-side clear.',
        'Sign-in page translates both <font name="FreeMono" size="9.5">InvalidSecret</font> and '
        '<font name="FreeMono" size="9.5">InvalidAccountId</font> to identical error messages, mitigating '
        'account enumeration on the sign-in path.',
        'Extension tokens use <font name="FreeMono" size="9.5">crypto.getRandomValues</font> (32 bytes / 256 bits entropy).',
        'Anonymous users are blocked from extension-token generation.',
        'CORS is restricted to an allowlist (not wildcard). HTTP errors are sanitized server-side. Token '
        'format is validated by regex before DB lookup.',
        'Markdown rendering is a custom React component — no <font name="FreeMono" size="9.5">rehype-raw</font> '
        'or <font name="FreeMono" size="9.5">allowDangerousHtml</font>. This closes the most common XSS '
        'vector in apps with chat/messaging.',
        'No source maps ship in production. Only three VITE_ env vars are exposed to the client bundle, '
        'all of which are public identifiers rather than secrets.',
    ]
    for w in wins:
        story.append(bullet(w))

    story.append(PageBreak())

    # ── Chapter 2: Methodology ──
    add_major_section('Chapter 2 · Audit Methodology', story)
    story.append(para(
        'This audit was conducted as a static source-code review combined with targeted live verification '
        'against the deployed Convex backend. The audit did not include dynamic penetration testing, '
        'fuzzing, or social engineering; it is a code-level assessment of the security posture as of the '
        'commit deployed on 2026-06-22. The audit was scoped to the AXIA monorepo at '
        '<font name="FreeMono" size="9.5">/home/z/my-project/axia/</font> and the deployed Convex deployment '
        '<font name="FreeMono" size="9.5">veracious-zebra-519</font>.'))
    story.append(para(
        'Three parallel audit passes were executed, each focused on a distinct attack surface:'))
    story.append(bullet(
        '<b>SEC-AUTH-1 — Authentication & Session.</b> Covered <font name="FreeMono" size="9.5">auth.ts</font>, '
        '<font name="FreeMono" size="9.5">auth.config.ts</font>, <font name="FreeMono" size="9.5">emailOtp.ts</font>, '
        'the <font name="FreeMono" size="9.5">security/</font> subdirectory, '
        '<font name="FreeMono" size="9.5">extension.ts</font>, <font name="FreeMono" size="9.5">extensionRotate.ts</font>, '
        '<font name="FreeMono" size="9.5">users.ts</font>, <font name="FreeMono" size="9.5">waitlist.ts</font>, '
        '<font name="FreeMono" size="9.5">adminListAll.ts</font>, <font name="FreeMono" size="9.5">adminSeed.ts</font>, '
        '<font name="FreeMono" size="9.5">debug.ts</font>, the auth-related frontend pages, and the '
        '<font name="FreeMono" size="9.5">@convex-dev/auth</font> library internals.'))
    story.append(bullet(
        '<b>SEC-BACKEND-1 — Convex Backend IDOR & Cloud-Bill Abuse.</b> Covered '
        '<font name="FreeMono" size="9.5">schema.ts</font>, <font name="FreeMono" size="9.5">http.ts</font>, '
        '<font name="FreeMono" size="9.5">crons.ts</font>, and all backend business logic: teams, permissions, '
        'clients, projects, pipeline, proposals, messaging, evidence, manualSends, invoices, billing, '
        'workspaces, notifications, audit, goals, customFields, network, and the AI dispute-prediction action.'))
    story.append(bullet(
        '<b>SEC-FRONTEND-1 — Frontend XSS, Clipboard, Injection.</b> Covered '
        '<font name="FreeMono" size="9.5">lib/markdown.tsx</font>, <font name="FreeMono" size="9.5">lib/template-parser.ts</font>, '
        '<font name="FreeMono" size="9.5">lib/exportUtils.ts</font>, <font name="FreeMono" size="9.5">lib/app-config.ts</font>, '
        '<font name="FreeMono" size="9.5">lib/monitoring.ts</font>, share/token/PDF/messaging components, '
        '<font name="FreeMono" size="9.5">main.tsx</font>, <font name="FreeMono" size="9.5">index.html</font>, '
        '<font name="FreeMono" size="9.5">vite.config.ts</font>, and <font name="FreeMono" size="9.5">package.json</font>.'))
    story.append(Spacer(1, 4))
    story.append(para(
        'Each finding was scored on a four-level severity scale (Critical / High / Medium / Low) using the '
        'OWASP Risk Rating methodology. Critical findings represent immediately exploitable vulnerabilities '
        'that allow account takeover, mass data breach, or large-scale cloud-bill abuse with no '
        'authentication required. High findings represent exploitable vulnerabilities that require some '
        'form of authentication but allow privilege escalation, cross-tenant data access, or significant '
        'bill amplification. Medium findings represent defense-in-depth gaps or vulnerabilities requiring '
        'specific preconditions. Low findings represent hygiene issues or latent footguns in dead code.'))

    story.append(PageBreak())

    # ── Chapter 3: Critical Production-Scale Risks ──
    add_major_section('Chapter 3 · Production-Scale Risk Analysis', story)
    story.append(para(
        'The user explicitly framed this audit around a forthcoming production scale-up to thousands of '
        'users. Several classes of vulnerability that are tolerable in a single-tenant or low-traffic '
        'deployment become existential at scale. This chapter walks through each class with concrete '
        'cost-and-breach estimates.'))

    add_subsection('3.1 · Cloud-Bill Abuse — The $1,000/Hour Attack', story)
    story.append(para(
        'Convex billing is metered across four dimensions: function calls, database reads, database '
        'writes, and storage. At AXIA\'s current pricing tier, rough unit costs are: ~$0.0000015 per '
        'function call, ~$0.0000004 per row read, ~$0.0000016 per row written, and ~$0.08 per GB-month '
        'of storage. These look tiny — and that is precisely the trap. A single attacker can write a '
        'simple loop that calls a no-op Convex mutation 1,000 times per second. That is 86.4 million '
        'calls per day, or roughly $130/day in function-call charges alone — from a single attacker on '
        'a single laptop. If the attacker instead spams a mutation that performs a '
        '<font name="FreeMono" size="9.5">.collect()</font> reading 1,000 rows, the read charges '
        'compound: another ~$35/day. If they spam the OpenAI-backed dispute-prediction action '
        '(<font name="FreeMono" size="9.5">ai/disputePredictionNode.ts</font>, which has no auth check), '
        'the OpenAI bill can hit thousands of dollars per hour.'))
    story.append(para(
        'The defense is multi-layered. First, install <font name="FreeMono" size="9.5">@convex-dev/rateLimit</font> '
        'and apply per-user, per-IP, and global rate limits on every mutation that writes to the database '
        'or invokes an external API. Second, replace every unbounded <font name="FreeMono" size="9.5">.collect()</font> '
        'with a bounded <font name="FreeMono" size="9.5">.take(N)</font> and add cursor-based pagination '
        'for legitimate large reads. Third, add per-user storage quotas in the evidence-upload flow. '
        'Fourth, gate the AI action behind authentication and a per-user daily quota. Fifth, add billing '
        'anomaly alerts in the Convex dashboard. The remediation code for each of these is provided in '
        'the per-finding sections below.'))

    add_subsection('3.2 · Server-Crash Vectors — LPDOS and Beyond', story)
    story.append(para(
        'Low-and-slow denial of service (LPDOS) attacks aim to exhaust server resources without tripping '
        'rate limits. AXIA is exposed on multiple fronts. The 427 unbounded <font name="FreeMono" size="9.5">.collect()</font> '
        'calls can be triggered by a single slow client; at scale, the Convex function runtime will '
        'consume large amounts of memory reading millions of rows, potentially hitting the 128 MB '
        'function-memory limit and returning 500s. The <font name="FreeMono" size="9.5">sendMessage</font> '
        'mutation performs a full <font name="FreeMono" size="9.5">users</font> table scan per @mention, '
        'so a message with 50 mentions scans the user table 50 times. The <font name="FreeMono" size="9.5">remindAboutStaleDrafts</font> '
        'cron does an unbounded collect followed by an N+1 query loop — at scale it can run for minutes '
        'and block other cron jobs. The <font name="FreeMono" size="9.5">recordEvents</font> mutation '
        'accepts an unbounded events array, so a single call can attempt to insert 100,000 rows in one '
        'transaction.'))
    story.append(para(
        'The defense is bounded reads (<font name="FreeMono" size="9.5">.take(N)</font>), bounded writes '
        '(<font name="FreeMono" size="9.5">v.array(..., v.maxLength(100))</font>), and per-user rate '
        'limits. The Convex <font name="FreeMono" size="9.5">@convex-dev/rateLimit</font> library '
        'supports token-bucket and fixed-window limits with shared state across function instances, '
        'which is exactly what is needed for distributed LPDOS defense.'))

    add_subsection('3.3 · Multi-Tenant Data Isolation — Cross-Workspace Leakage', story)
    story.append(para(
        'AXIA is multi-tenant: each workspace is a separate tenant with its own clients, projects, '
        'proposals, invoices, and messages. The audit found that the <font name="FreeMono" size="9.5">workspaces/members.ts</font> '
        'assignment mutations (<font name="FreeMono" size="9.5">assignMemberToProject</font>, '
        '<font name="FreeMono" size="9.5">assignMemberToClient</font>, and their unassign variants) '
        'verify that the member and the target are in the same workspace, but never verify that the '
        '<i>caller</i> has access to that workspace. A logged-in user in workspace A can assign members '
        'to projects in workspace B. The <font name="FreeMono" size="9.5">clients/clientPortal.ts</font> '
        'module is worse: it is fully unauthenticated, so any internet user can pass any client email '
        'and retrieve that client\'s data from every workspace on the platform.'))
    story.append(para(
        'At thousands of users, this becomes a mass PII breach. A script enumerating common email '
        'patterns (firstname.lastname@company.com) against <font name="FreeMono" size="9.5">getClientInvoices</font> '
        'would harvest invoices for every client of every AXIA customer in hours. The defense is to '
        'gate every backend function behind a <font name="FreeMono" size="9.5">requireWorkspaceAccess</font> '
        'helper that verifies the caller is a member of the workspace owning the resource, and to gate '
        'client-portal endpoints behind signed single-use tokens instead of bare client emails.'))

    add_subsection('3.4 · Race Conditions at Scale', story)
    story.append(para(
        'At thousands of users, race conditions that are rare at low traffic become statistically '
        'guaranteed. The <font name="FreeMono" size="9.5">seedPersonalWorkspace</font> race — where '
        'both <font name="FreeMono" size="9.5">use-auth.ts</font> and <font name="FreeMono" size="9.5">use-workspace.tsx</font> '
        'called the same mutation on signup — was already mitigated in TEAM-FIX-1 by removing the '
        'duplicate caller. But the same pattern exists elsewhere: invitation acceptance is not '
        'idempotent (the same token accepted twice could create two membership rows), and the bulk '
        'import dedup checks are check-then-act without transactions. The defense is to use Convex '
        'transactions (<font name="FreeMono" size="9.5">ctx.db.runInTransaction</font>) or unique '
        'indexes to enforce idempotency at the database layer rather than at the application layer.'))

    story.append(PageBreak())

    # ── Chapter 4: Attack Vector Coverage Matrix ──
    add_major_section('Chapter 4 · Attack Vector Coverage Matrix', story)
    story.append(para(
        f'The matrix below maps {len(ATTACK_VECTORS)} distinct attack vectors to AXIA\'s current '
        'defensive posture. Each vector is annotated with its OWASP category, an AXIA-specific status '
        '(Critical / Vulnerable / Partially Vulnerable / Medium Risk / Low Risk / Safe / Not '
        'Applicable / Out of Scope), and a short note pointing to the specific finding or file. '
        'Vectors marked Critical or Vulnerable require remediation before the production scale-up; '
        'those marked Safe or Not Applicable require no action but are documented for completeness.'))
    story.append(Spacer(1, 4))
    story.append(attack_vector_table())

    story.append(PageBreak())

    # ── Chapter 5: Authentication & Session Findings ──
    add_major_section('Chapter 5 · Authentication & Session Findings', story)
    story.append(para(
        f'This chapter presents the {len(auth_findings)} findings from the SEC-AUTH-1 audit pass, '
        'covering authentication, session management, password security, OTP, extension tokens, and '
        'related admin/debug code. Findings are numbered A-1 through A-{len(auth_findings)} and '
        'ordered by severity within each tier.'))
    story.append(Spacer(1, 6))
    for f in auth_findings:
        render_finding(f, story, prefix='A')

    story.append(PageBreak())

    # ── Chapter 6: Backend IDOR & Cloud-Bill Findings ──
    add_major_section('Chapter 6 · Backend IDOR & Cloud-Bill Findings', story)
    story.append(para(
        f'This chapter presents the {len(backend_findings)} findings from the SEC-BACKEND-1 audit pass, '
        'covering Convex backend business logic: IDOR, broken function-level authorization, race '
        'conditions, unbounded reads, spam-able mutations, storage abuse, and cron-job risks. Findings '
        'are numbered B-1 through B-{len(backend_findings)} and ordered by severity within each tier.'))
    story.append(Spacer(1, 6))
    for f in backend_findings:
        render_finding(f, story, prefix='B')

    story.append(PageBreak())

    # ── Chapter 7: Frontend XSS / Clipboard / Injection Findings ──
    add_major_section('Chapter 7 · Frontend XSS / Clipboard / Injection Findings', story)
    story.append(para(
        f'This chapter presents the {len(frontend_findings)} findings from the SEC-FRONTEND-1 audit pass, '
        'covering XSS, clipboard attacks, replay attacks, secret leaks, postMessage vulnerabilities, '
        'CSP weaknesses, and SRI gaps. Findings are numbered F-1 through F-{len(frontend_findings)} '
        'and ordered by severity within each tier.'))
    story.append(Spacer(1, 6))
    for f in frontend_findings:
        render_finding(f, story, prefix='F')

    story.append(PageBreak())

    # ── Chapter 8: Remediation Roadmap ──
    add_major_section('Chapter 8 · Remediation Roadmap', story)
    story.append(para(
        'The remediation roadmap below sequences the fixes into three waves. Wave 1 must be completed '
        'before any further production traffic is allowed — these are the critical-account-takeover '
        'and mass-breach fixes. Wave 2 must be completed before the production scale-up to thousands '
        'of users — these are the rate-limiting, IDOR, and cloud-bill-abuse fixes. Wave 3 is the '
        'defense-in-depth hardening that should follow within 30 days of the scale-up.'))

    add_subsection('8.1 · Wave 1 — Immediate (Before Next Deploy)', story)
    wave1 = [
        'Delete <font name="FreeMono" size="9.5">src/convex/adminListAll.ts</font>, '
        '<font name="FreeMono" size="9.5">src/convex/adminSeed.ts</font>, and '
        '<font name="FreeMono" size="9.5">src/convex/debug.ts</font> from the deployed codebase. '
        'These files contain public unauthenticated mutations that allow account takeover, user-table '
        'dump, and admin self-grant. Re-implement any genuinely needed admin functions as '
        '<font name="FreeMono" size="9.5">internalMutation</font> callable only from a server-side '
        'deploy key.',
        'Strip <font name="FreeMono" size="9.5">subscriptionTier</font> from the '
        '<font name="FreeMono" size="9.5">users.updateProfile</font> args validator. Move tier changes '
        'to a dedicated <font name="FreeMono" size="9.5">internalMutation</font> invoked only by the '
        'Stripe webhook handler.',
        'Remove the hardcoded owner password from '
        '<font name="FreeMono" size="9.5">src/pages/OwnerDashboard.tsx</font> and wire the page to the '
        'existing (dead-code) <font name="FreeMono" size="9.5">ownerAuth_verifyOwnerCredentials</font> '
        'mutation. Remove the <font name="FreeMono" size="9.5">localStorage.setItem("ownerSessionActive")</font> '
        'bypass.',
        'Gate <font name="FreeMono" size="9.5">handleStripeWebhook</font> behind Stripe signature '
        'verification. Use the <font name="FreeMono" size="9.5">stripe.webhooks.constructEvent</font> '
        'helper with the webhook signing secret stored in a Convex environment variable.',
        'Gate every export in <font name="FreeMono" size="9.5">clients/clientPortal.ts</font> behind a '
        'signed single-use token. Replace bare <font name="FreeMono" size="9.5">clientEmail</font> args '
        'with a <font name="FreeMono" size="9.5">clientToken</font> arg derived from '
        '<font name="FreeMono" size="9.5">crypto.randomUUID()</font> and stored in a new '
        '<font name="FreeMono" size="9.5">clientAccessTokens</font> table.',
        'Convert <font name="FreeMono" size="9.5">seedTeamUsers.seedAllUsers</font> from a public '
        '<font name="FreeMono" size="9.5">action</font> to an <font name="FreeMono" size="9.5">internalAction</font>. '
        'Rotate the hardcoded password <font name="FreeMono" size="9.5">"Axia2026!"</font> for any test '
        'users that have already been created in production.',
        'Remove the <font name="FreeMono" size="9.5">guest@axia.demo</font> auto-creation fallback in '
        '<font name="FreeMono" size="9.5">projects/projectProtection.ts</font>. Anonymous visitors should '
        'receive a 401, not a shared guest account that can read and write other guests\' evidence.',
    ]
    for item in wave1:
        story.append(bullet(item))

    add_subsection('8.2 · Wave 2 — Before Production Scale-Up', story)
    wave2 = [
        'Install <font name="FreeMono" size="9.5">@convex-dev/rateLimit</font> and apply per-user, '
        'per-IP, and global rate limits on every mutation that writes to the database or invokes an '
        'external API. Start with the spam-able mutations: <font name="FreeMono" size="9.5">sendMessage</font>, '
        '<font name="FreeMono" size="9.5">recordEvents</font>, <font name="FreeMono" size="9.5">importClients</font>, '
        '<font name="FreeMono" size="9.5">importDeals</font>, <font name="FreeMono" size="9.5">addToWaitlist</font>, '
        '<font name="FreeMono" size="9.5">registerClient</font>, <font name="FreeMono" size="9.5">emailOtp.sendVerificationRequest</font>.',
        'Replace unbounded <font name="FreeMono" size="9.5">.collect()</font> calls with bounded '
        '<font name="FreeMono" size="9.5">.take(N)</font> followed by cursor-based pagination. Start '
        'with the worst offenders: <font name="FreeMono" size="9.5">sendMessage</font> '
        '(users table scan per @mention), <font name="FreeMono" size="9.5">enrichAllTeamUsers</font> '
        '(full workspaces scan), <font name="FreeMono" size="9.5">getClientProposals</font> in '
        '<font name="FreeMono" size="9.5">clientWorkspace.ts</font> (full proposals scan), '
        '<font name="FreeMono" size="9.5">getWorkspaceShareRecords</font> (4 unbounded collects per call).',
        'Add <font name="FreeMono" size="9.5">v.maxLength</font> to every <font name="FreeMono" size="9.5">v.string()</font> '
        'arg validator. Add <font name="FreeMono" size="9.5">v.maxLength(100)</font> to every '
        '<font name="FreeMono" size="9.5">v.array()</font>. This prevents the bulk-import array-of-100,000 '
        'attack.',
        'Add per-user storage quotas in the evidence-upload flow. Track total bytes per user in the '
        '<font name="FreeMono" size="9.5">users</font> table and reject uploads that would exceed the '
        'quota (e.g., 1 GB for free tier, 10 GB for paid tier). Validate MIME type against an allowlist '
        'before <font name="FreeMono" size="9.5">storage.store()</font>.',
        'Implement a <font name="FreeMono" size="9.5">requireWorkspaceAccess(ctx, workspaceId)</font> '
        'helper and apply it to every backend function that takes a workspace-scoped resource ID. '
        'Move the duplicate <font name="FreeMono" size="9.5">createChannel</font>/<font name="FreeMono" size="9.5">joinChannel</font> '
        'mutations out of <font name="FreeMono" size="9.5">messaging/channels.ts</font> (the canonical '
        'versions in <font name="FreeMono" size="9.5">channelMutations.ts</font> are correct).',
        'Add Stripe signature verification to <font name="FreeMono" size="9.5">handleStripeWebhook</font>. '
        'This was listed in Wave 1 but the implementation should land in Wave 2 alongside the broader '
        'billing-security pass.',
        'Convert the <font name="FreeMono" size="9.5">predictDisputeOutcome</font> action to require '
        'authentication and apply a per-user daily quota (e.g., 50 predictions/day for paid tier, 5 for '
        'free tier). Sanitize user-controlled evidence text before feeding it to the LangChain prompt '
        'template to mitigate prompt injection.',
        'Replace <font name="FreeMono" size="9.5">Math.random()</font> token generation in '
        '<font name="FreeMono" size="9.5">waitlistHelpers.ts</font>, '
        '<font name="FreeMono" size="9.5">proposals/crud.ts</font>, and '
        '<font name="FreeMono" size="9.5">clients/clientWorkspace.ts</font> with '
        '<font name="FreeMono" size="9.5">crypto.randomUUID()</font> or '
        '<font name="FreeMono" size="9.5">crypto.getRandomValues</font>.',
        'Tighten the Content Security Policy in <font name="FreeMono" size="9.5">index.html</font> to '
        'remove <font name="FreeMono" size="9.5">unsafe-inline</font> and <font name="FreeMono" size="9.5">unsafe-eval</font>, '
        'add <font name="FreeMono" size="9.5">frame-ancestors \'none\'</font>, '
        '<font name="FreeMono" size="9.5">base-uri \'self\'</font>, '
        '<font name="FreeMono" size="9.5">form-action \'self\'</font>, '
        '<font name="FreeMono" size="9.5">object-src \'none\'</font>, and '
        '<font name="FreeMono" size="9.5">worker-src \'self\'</font>. Set the CSP via HTTP header on '
        'the host (Convex/Vercel) rather than <font name="FreeMono" size="9.5"><meta></font>, '
        'because <font name="FreeMono" size="9.5">frame-ancestors</font> is ignored in meta CSP.',
        'Fix the postMessage origin bypass in <font name="FreeMono" size="9.5">main.tsx</font> '
        'RouteSyncer. Replace the <font name="FreeMono" size="9.5">"*"</font> target with a specific '
        'origin allowlist. Add <font name="FreeMono" size="9.5">event.origin</font> validation to the '
        'message listener.',
        'Vendor the PDF.js worker locally instead of loading it from cdnjs.cloudflare.com, and add an '
        '<font name="FreeMono" size="9.5">integrity</font> attribute if a CDN must be used.',
    ]
    for item in wave2:
        story.append(bullet(item))

    add_subsection('8.3 · Wave 3 — Defense-in-Depth (30 Days Post-Scale-Up)', story)
    wave3 = [
        'Implement MFA / TOTP via <font name="FreeMono" size="9.5">otplib</font> or WebAuthn passkeys. '
        'For a SaaS handling client work product, MFA on the workspace-owner account should be mandatory.',
        'Implement a password-reset flow via Convex Auth\'s <font name="FreeMono" size="9.5">reset</font> '
        'provider configuration. Use single-use tokens with a 15-minute expiry delivered by email.',
        'Add email verification to the Password sign-up flow. Currently a user can sign up with '
        'someone else\'s email without verification.',
        'Add per-IP rate limiting on <font name="FreeMono" size="9.5">emailOtp.sendVerificationRequest</font> '
        'and <font name="FreeMono" size="9.5">clientAuth.registerClient</font>. The existing per-email '
        'rate limit does not prevent an attacker from rotating emails to spam OTPs.',
        'Add account lockout after 10 failed sign-in attempts, with a 15-minute cooldown and email '
        'notification. Ensure lockout cannot be used for self-DoS (e.g., by allowing unlock via email).',
        'Replace the 30-day bearer extension token with short-lived (15-minute) signed JWTs with a '
        'refresh-token rotation scheme. Add a nonce cache to reject replayed requests within the TTL.',
        'Replace <font name="FreeMono" size="9.5">simpleUserIdHash</font> in '
        '<font name="FreeMono" size="9.5">audit.ts</font> with the existing (dead-code) HMAC-SHA256 '
        'helper in <font name="FreeMono" size="9.5">crypto.ts</font>. Use a server-only HMAC key.',
        'Add security-event logging: failed sign-ins, role changes, password resets, invitation '
        'acceptances, storage-quota violations, rate-limit violations. Ship to a SIEM (Sentry, '
        'Datadog, or similar).',
        'Switch the Convex Auth cookie from <font name="FreeMono" size="9.5">sameSite:"none"</font> to '
        '<font name="FreeMono" size="9.5">sameSite:"lax"</font> if cross-site embedding is not required. '
        'This eliminates the CSRF surface entirely.',
        'Add <font name="FreeMono" size="9.5">X-Content-Type-Options: nosniff</font>, '
        '<font name="FreeMono" size="9.5">X-Frame-Options: DENY</font>, '
        '<font name="FreeMono" size="9.5">Referrer-Policy: strict-origin-when-cross-origin</font>, and '
        '<font name="FreeMono" size="9.5">Permissions-Policy</font> headers via the host layer.',
        'Add a "clipboard auto-clear" wrapper for sensitive writes (extension tokens, share tokens). '
        'After <font name="FreeMono" size="9.5">navigator.clipboard.writeText</font>, schedule a '
        '<font name="FreeMono" size="9.5">writeText("")</font> after 30 seconds. Warn the user in the '
        'UI that the token will be cleared automatically.',
        'Run <font name="FreeMono" size="9.5">npm audit --audit-level=moderate</font> in CI and enforce '
        'zero high-severity vulnerabilities. Add Dependabot or Snyk for ongoing dependency monitoring.',
        'Add a Convex billing anomaly alert: notify the team if daily function-call count exceeds 2× the '
        '7-day rolling average. This catches cloud-bill abuse even if rate limits are bypassed.',
    ]
    for item in wave3:
        story.append(bullet(item))

    story.append(PageBreak())

    # ── Chapter 9: Defense-in-Depth Recommendations ──
    add_major_section('Chapter 9 · Defense-in-Depth Recommendations', story)
    story.append(para(
        'Beyond the per-finding remediations, AXIA should adopt several defense-in-depth practices that '
        'do not map to any single finding but raise the overall security posture.'))
    add_subsection('9.1 · Adopt a Security Champion Program', story)
    story.append(para(
        'Designate one engineer per team as the security champion. Their role is to review every PR for '
        'the OWASP Top 10 and API Top 10, attend monthly security training, and maintain the security '
        'backlog. This is the single highest-leverage investment a small engineering team can make in '
        'security. The champion does not need to be a security expert — they need to know when to ask '
        'for help, and they need a budget for outside audits.'))
    add_subsection('9.2 · Add Automated Security Scanning to CI', story)
    story.append(para(
        'Add the following to the CI pipeline: (1) <font name="FreeMono" size="9.5">npm audit</font> '
        'for dependency vulnerabilities; (2) <font name="FreeMono" size="9.5">eslint-plugin-security</font> '
        'for common Node.js security mistakes; (3) <font name="FreeMono" size="9.5">eslint-plugin-no-unsanitized-method</font> '
        'to flag <font name="FreeMono" size="9.5">dangerouslySetInnerHTML</font> and '
        '<font name="FreeMono" size="9.5">innerHTML</font> usage; (4) a custom ESLint rule that flags '
        'Convex <font name="FreeMono" size="9.5">mutation</font> / <font name="FreeMono" size="9.5">query</font> '
        'exports that do not call <font name="FreeMono" size="9.5">getAuthUserId</font> in their handler. '
        'This last rule would have caught every Wave-1 finding automatically.'))
    add_subsection('9.3 · Add a Pre-Deploy Security Checklist', story)
    story.append(para(
        'Before every production deploy, run through a checklist: (1) Are there any new '
        '<font name="FreeMono" size="9.5">export const</font> in <font name="FreeMono" size="9.5">src/convex/</font> '
        'that do not call <font name="FreeMono" size="9.5">getAuthUserId</font>? (2) Are there any new '
        '<font name="FreeMono" size="9.5">.collect()</font> calls? (3) Are there any new '
        '<font name="FreeMono" size="9.5">v.array()</font> validators without '
        '<font name="FreeMono" size="9.5">maxLength</font>? (4) Are there any new '
        '<font name="FreeMono" size="9.5">dangerouslySetInnerHTML</font> usages? (5) Are there any new '
        'env vars in <font name="FreeMono" size="9.5">.env</font> that look like secrets?'))
    add_subsection('9.4 · Conduct Regular Third-Party Audits', story)
    story.append(para(
        'This audit was conducted as a static code review. It did not include dynamic penetration '
        'testing, fuzzing, or social engineering. Before the production scale-up, commission a '
        'third-party penetration test from a reputable firm. Repeat annually thereafter, or whenever '
        'a major feature is shipped. The cost of a pentest ($15K-$50K) is small compared to the cost '
        'of a single breach at scale.'))
    add_subsection('9.5 · Incident Response Plan', story)
    story.append(para(
        'Document an incident response plan covering: (1) how to revoke all sessions in case of mass '
        'compromise (Convex Auth supports this via <font name="FreeMono" size="9.5">invalidateSession</font>); '
        '(2) how to rotate the Convex deployment URL in case of persistent abuse; (3) how to roll back '
        'a bad deploy (Convex supports deploys with a single command); (4) how to notify users in case '
        'of a breach (templates pre-written, email provider ready); (5) how to coordinate with law '
        'enforcement if PII is involved. The plan should be tested with a tabletop exercise at least '
        'once per quarter.'))

    story.append(PageBreak())

    # ── Chapter 10: Conclusion ──
    add_major_section('Chapter 10 · Conclusion', story)
    story.append(para(
        'AXIA has a solid cryptographic foundation — scrypt password hashing, httpOnly secure cookies, '
        'session rotation, single-use OTPs, and a custom React markdown renderer that avoids the most '
        'common XSS vector. The engineering team has already shipped several security fixes in the '
        'prior AUTH-FIX and TEAM-FIX rounds, including account-enumeration mitigation on sign-in and '
        'strict team-hierarchy permission rules.'))
    story.append(para(
        'However, the codebase currently contains several Critical-severity vulnerabilities that make '
        'it unsafe to scale to thousands of users in its present state. The most urgent — the deployed '
        '<font name="FreeMono" size="9.5">adminListAll.ts</font> file with its public '
        '<font name="FreeMono" size="9.5">resetPassword</font> mutation — constitutes a one-call full '
        'account-takeover of every user on the platform. This must be fixed before the next deploy, '
        'full stop. The second most urgent class — the complete absence of rate limiting combined '
        'with 427 unbounded <font name="FreeMono" size="9.5">.collect()</font> calls and unauthenticated '
        'cloud-bill-abuse vectors (the AI action, the storage uploads, the OTP resend) — represents '
        'an existential financial risk at production scale.'))
    story.append(para(
        'The remediation work is well-scoped: Wave 1 is approximately 2-3 engineering days, Wave 2 is '
        'approximately 2 engineering weeks, and Wave 3 is approximately 1 engineering month. None of '
        'the fixes require architectural changes — they are all incremental hardening on top of the '
        'existing Convex + React stack. The attack-vector coverage matrix in Chapter 4 shows that '
        'AXIA is well-defended against the majority of the 60+ vectors surveyed (SQL injection, JWT '
        'attacks, XXE, ZIP slip, request smuggling, cache poisoning, etc.); the gaps are concentrated '
        'in authorization, rate limiting, and CSP, all of which are addressable in the three waves '
        'above.'))
    story.append(para(
        'With the Wave 1 fixes shipped immediately and the Wave 2 fixes shipped before the scale-up, '
        'AXIA will be in a defensible security posture for thousands of users. Wave 3 brings it to '
        'industry best practice. The defense-in-depth recommendations in Chapter 9 (security champion, '
        'CI scanning, pre-deploy checklist, regular pentests, incident response plan) will keep it '
        'there as the team and codebase grow.'))

    # ── Build PDF ──
    print('Building PDF...')
    doc = TocDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=LEFT_M, rightMargin=RIGHT_M,
        topMargin=TOP_M, bottomMargin=BOTTOM_M,
        title='AXIA Security Audit Report',
        author='Z.ai Security Audit',
        creator='Z.ai',
        subject='Comprehensive security audit of AXIA SaaS application'
    )

    doc.multiBuild(story, onFirstPage=cover_page, onLaterPages=header_footer)
    print(f'PDF written to: {output_path}')

    # Report file size
    sz = os.path.getsize(output_path)
    print(f'Size: {sz / 1024:.1f} KB')

if __name__ == '__main__':
    main()
