#!/usr/bin/env python3
"""
Axia Data Flow Architecture & Monitoring Integration Report
Generated by Z.ai
"""

import os
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm, inch
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, Image, KeepTogether, HRFlowable
)
from reportlab.platypus.flowables import Flowable
from reportlab.graphics.shapes import Drawing, Rect, String, Line
from reportlab.graphics import renderPDF

# ── Colors ──
TEAL = colors.HexColor("#0D9488")
DARK = colors.HexColor("#1E293B")
LIGHT_TEAL = colors.HexColor("#F0FDFA")
LIGHT_GRAY = colors.HexColor("#F8FAFC")
BORDER = colors.HexColor("#E2E8F0")
TEXT = colors.HexColor("#1E293B")
MUTED = colors.HexColor("#64748B")
ACCENT = colors.HexColor("#0D9488")
WHITE = colors.white

OUTPUT = "/home/z/my-project/download/Axia_Data_Flow_Architecture.pdf"

# ── Styles ──
styles = getSampleStyleSheet()

styles.add(ParagraphStyle(
    "CoverTitle", parent=styles["Title"],
    fontSize=36, leading=42, textColor=WHITE,
    fontName="Helvetica-Bold", alignment=TA_LEFT,
    spaceAfter=12,
))

styles.add(ParagraphStyle(
    "CoverSubtitle", parent=styles["Normal"],
    fontSize=16, leading=22, textColor=colors.HexColor("#94A3B8"),
    fontName="Helvetica", alignment=TA_LEFT,
    spaceAfter=8,
))

styles.add(ParagraphStyle(
    "H1", parent=styles["Heading1"],
    fontSize=24, leading=30, textColor=TEAL,
    fontName="Helvetica-Bold", spaceAfter=12, spaceBefore=24,
))

styles.add(ParagraphStyle(
    "H2", parent=styles["Heading2"],
    fontSize=18, leading=24, textColor=DARK,
    fontName="Helvetica-Bold", spaceAfter=8, spaceBefore=16,
))

styles.add(ParagraphStyle(
    "H3", parent=styles["Heading3"],
    fontSize=14, leading=18, textColor=TEAL,
    fontName="Helvetica-Bold", spaceAfter=6, spaceBefore=12,
))

styles.add(ParagraphStyle(
    "Body", parent=styles["Normal"],
    fontSize=11, leading=16, textColor=TEXT,
    fontName="Helvetica", alignment=TA_JUSTIFY,
    spaceAfter=8,
))

styles.add(ParagraphStyle(
    "BodySmall", parent=styles["Normal"],
    fontSize=9, leading=13, textColor=TEXT,
    fontName="Helvetica", alignment=TA_LEFT,
    spaceAfter=4,
))

styles.add(ParagraphStyle(
    "CodeSnippet", parent=styles["Normal"],
    fontSize=9, leading=13, textColor=colors.HexColor("#334155"),
    fontName="Courier", backColor=LIGHT_GRAY,
    spaceAfter=6, spaceBefore=4,
    leftIndent=12, rightIndent=12,
    borderPadding=(6, 6, 6, 6),
))

styles.add(ParagraphStyle(
    "BulletItem", parent=styles["Normal"],
    fontSize=11, leading=16, textColor=TEXT,
    fontName="Helvetica", alignment=TA_LEFT,
    spaceAfter=4, leftIndent=24, bulletIndent=12,
))

styles.add(ParagraphStyle(
    "TableCell", parent=styles["Normal"],
    fontSize=8.5, leading=11, textColor=TEXT,
    fontName="Helvetica", alignment=TA_LEFT,
))

styles.add(ParagraphStyle(
    "TableHeader", parent=styles["Normal"],
    fontSize=9, leading=12, textColor=WHITE,
    fontName="Helvetica-Bold", alignment=TA_LEFT,
))


def make_table(headers, rows, col_widths=None):
    """Create a styled table."""
    header_paras = [Paragraph(h, styles["TableHeader"]) for h in headers]
    data = [header_paras]
    for row in rows:
        data.append([Paragraph(str(c), styles["TableCell"]) for c in row])
    
    t = Table(data, colWidths=col_widths, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), TEAL),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
        ("TOPPADDING", (0, 0), (-1, 0), 8),
        ("BACKGROUND", (0, 1), (-1, -1), WHITE),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT_GRAY]),
        ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 1), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 4),
    ]))
    return t


def bullet(text):
    return Paragraph(f"\u2022 {text}", styles["BulletItem"])


def body(text):
    return Paragraph(text, styles["Body"])


def h1(text):
    return Paragraph(text, styles["H1"])


def h2(text):
    return Paragraph(text, styles["H2"])


def h3(text):
    return Paragraph(text, styles["H3"])


def code(text):
    return Paragraph(text, styles["CodeSnippet"])


def hr():
    return HRFlowable(width="100%", thickness=1, color=BORDER, spaceAfter=8, spaceBefore=8)


# ── Build Document ──
doc = SimpleDocTemplate(
    OUTPUT,
    pagesize=A4,
    topMargin=25*mm,
    bottomMargin=20*mm,
    leftMargin=20*mm,
    rightMargin=20*mm,
    title="Axia Data Flow Architecture & Monitoring Integration",
    author="Z.ai",
    creator="Axia Engineering",
)

story = []

# ════════════════════════════════════════════════════════════════════════════════
# COVER PAGE
# ════════════════════════════════════════════════════════════════════════════════

class CoverBackground(Flowable):
    def __init__(self, width, height):
        Flowable.__init__(self)
        self.width = width
        self.height = height
    
    def draw(self):
        self.canv.setFillColor(colors.HexColor("#0A0F1C"))
        self.canv.rect(0, 0, self.width, self.height, fill=1, stroke=0)
        # Teal accent bar
        self.canv.setFillColor(TEAL)
        self.canv.rect(0, self.height - 8, self.width, 8, fill=1, stroke=0)
        # Decorative lines
        self.canv.setStrokeColor(colors.HexColor("#0D948833"))
        self.canv.setLineWidth(0.5)
        for y_offset in range(0, int(self.height), 40):
            self.canv.line(0, y_offset, self.width, y_offset)

page_w, page_h = A4
cover_bg = CoverBackground(page_w - 40*mm, page_h - 45*mm)

story.append(Spacer(1, 80))
story.append(Paragraph("AXIA", ParagraphStyle("CoverBrand", parent=styles["Normal"],
    fontSize=14, leading=18, textColor=TEAL, fontName="Helvetica-Bold",
    spaceAfter=24, letterSpacing=4)))
story.append(Paragraph("Data Flow Architecture<br/>&amp; Monitoring Integration", styles["CoverTitle"]))
story.append(Spacer(1, 16))
story.append(Paragraph("Complete System Architecture, Data Flow Map,<br/>and Observability Stack", styles["CoverSubtitle"]))
story.append(Spacer(1, 40))

meta_style = ParagraphStyle("CoverMeta", parent=styles["Normal"],
    fontSize=11, leading=16, textColor=colors.HexColor("#94A3B8"), fontName="Helvetica")
story.append(Paragraph("Version 1.0  |  June 2026", meta_style))
story.append(Paragraph("Axia Engineering Team", meta_style))
story.append(PageBreak())

# ════════════════════════════════════════════════════════════════════════════════
# SECTION 2: EXECUTIVE SUMMARY
# ════════════════════════════════════════════════════════════════════════════════

story.append(h1("Executive Summary"))
story.append(body(
    "This document provides a comprehensive analysis of the Axia platform's data flow architecture, "
    "identifies critical issues affecting page loading and reliability, and documents the monitoring "
    "infrastructure implemented to ensure observability across the entire application. The investigation "
    "revealed systemic problems with loading state management, error handling, and a complete absence "
    "of production monitoring capabilities."
))
story.append(Spacer(1, 8))

story.append(h2("Key Findings"))
story.append(bullet("<b>Projects Page Crash:</b> React hooks violation caused the page to crash every time it was opened. The <font face='Courier'>usePermissions</font> hook was called inside an IIFE within JSX, violating the Rules of Hooks."))
story.append(bullet("<b>Perpetual Loading States:</b> 12+ pages showed infinite loading spinners because <font face='Courier'>safe-convex-react</font> returned <font face='Courier'>undefined</font> for both loading AND error states, making them indistinguishable."))
story.append(bullet("<b>EvidenceExport Blank Page:</b> Three concurrent Convex queries with no timeout or error fallback meant the page showed a permanent skeleton when any query failed."))
story.append(bullet("<b>Dashboard Spinner:</b> Eight concurrent Convex queries with a single AND-gate loading check meant the page would spin forever if any one query failed."))
story.append(bullet("<b>No Monitoring:</b> Zero error tracking, zero analytics, zero observability. Production errors were invisible."))
story.append(bullet("<b>Dark Mode Broken:</b> <font face='Courier'>@theme inline</font> in Tailwind CSS 4 was baking light-mode hex values directly into utility classes, making dark mode CSS variable overrides completely ineffective."))
story.append(Spacer(1, 8))

story.append(h2("Fixes Implemented"))
fixes_data = [
    ["Fix", "Scope", "Status"],
    ["safe-convex-react error state", "Foundation", "Done"],
    ["useQueryTimeout hook (5-6s)", "All data pages", "Done"],
    ["PageLoader / QueryErrorState", "Reusable components", "Done"],
    ["Projects crash (hooks violation)", "Projects.tsx", "Done"],
    ["EvidenceExport timeout fallback", "EvidenceExport.tsx", "Done"],
    ["Dashboard 8-query timeout", "Dashboard.tsx", "Done"],
    ["9 pages: timeout + error fallback", "9 page files", "Done"],
    ["Sentry error tracking", "Production monitoring", "Done"],
    ["PostHog product analytics", "User behavior tracking", "Done"],
    ["Dark mode fix (@theme inline)", "index.css", "Done"],
]
story.append(make_table(fixes_data[0], fixes_data[1:], col_widths=[180, 130, 80]))
story.append(PageBreak())

# ════════════════════════════════════════════════════════════════════════════════
# SECTION 3: SYSTEM ARCHITECTURE OVERVIEW
# ════════════════════════════════════════════════════════════════════════════════

story.append(h1("System Architecture Overview"))
story.append(body(
    "Axia is built on a Vite + React 19 + TypeScript + Tailwind CSS 4 stack with Convex as the "
    "sole backend for real-time data, authentication, and server functions. The application follows "
    "a single-page application architecture with client-side routing via React Router v7. All data "
    "flows through Convex's real-time subscription model, where <font face='Courier'>useQuery</font> "
    "hooks establish persistent WebSocket connections that automatically update the UI when data changes."
))
story.append(Spacer(1, 6))

story.append(h2("Component Hierarchy"))
story.append(body(
    "The application is structured as a deeply nested component tree where each layer adds specific "
    "capabilities. The root starts with React's StrictMode, then layers on theming, instrumentation, "
    "Convex connectivity, authentication, routing, and workspace scoping. This hierarchical design "
    "ensures that every child component has access to the full set of contexts it needs."
))
story.append(Spacer(1, 4))
story.append(code(
    "StrictMode\n"
    "  +-- VlyToolbar\n"
    "  +-- ThemeProvider (dark/light toggle, localStorage persistence)\n"
    "       +-- InstrumentationProvider (Sentry + PostHog init)\n"
    "            +-- ConvexProvider (WebSocket real-time connection)\n"
    "                 +-- ConvexAuthProvider (sign-in/sign-up/sign-out)\n"
    "                      +-- BrowserRouter (client-side routing)\n"
    "                           +-- WorkspaceProvider (active workspace, permissions)\n"
    "                                +-- ProfileModal (global)\n"
    "                                +-- Routes\n"
    "                                     +-- Public Routes (Landing, Auth, OwnerDashboard)\n"
    "                                     +-- ProtectedRoute\n"
    "                                          +-- DashboardLayout\n"
    "                                               +-- CollapsibleSidebar\n"
    "                                               +-- Outlet (page content)"
))
story.append(Spacer(1, 8))

story.append(h2("Technology Stack"))
stack_data = [
    ["Layer", "Technology", "Purpose"],
    ["Frontend", "React 19 + TypeScript", "UI framework with type safety"],
    ["Build", "Vite 6 + SWC", "Fast HMR, optimized production builds"],
    ["Styling", "Tailwind CSS 4 + @theme", "Utility-first CSS with design tokens"],
    ["Routing", "React Router v7", "Client-side SPA routing with guards"],
    ["Backend", "Convex", "Real-time database, functions, auth"],
    ["Auth", "@convex-dev/auth", "Password, Google, GitHub, Email OTP"],
    ["State", "Convex useQuery/useMutation", "Real-time reactive data subscriptions"],
    ["Monitoring", "Sentry + PostHog", "Error tracking + product analytics"],
    ["Animation", "Framer Motion", "Page transitions and micro-interactions"],
]
story.append(make_table(stack_data[0], stack_data[1:], col_widths=[70, 140, 200]))
story.append(PageBreak())

# ════════════════════════════════════════════════════════════════════════════════
# SECTION 4: DATA FLOW ARCHITECTURE
# ════════════════════════════════════════════════════════════════════════════════

story.append(h1("Data Flow Architecture"))
story.append(body(
    "Data flows through the Axia application via six distinct patterns, each designed to handle "
    "different connectivity and authentication scenarios. Understanding these patterns is critical "
    "for diagnosing loading issues and planning new features. All data originates from Convex's "
    "real-time subscription model, with fallback mechanisms for offline, unauthenticated, and "
    "error scenarios."
))

story.append(h2("Pattern A: Direct Convex"))
story.append(body(
    "The most common pattern. A page component calls <font face='Courier'>useQuery(api.module.function, args)</font> "
    "which establishes a real-time WebSocket subscription. Convex automatically pushes updates to "
    "the UI whenever the underlying data changes. This pattern is used by the majority of data-fetching "
    "pages including Clients, Invoices, Pipeline, Proposals, Tags, Goals, and Reports. The subscription "
    "remains active as long as the component is mounted, and Convex handles reconnection automatically."
))

story.append(h2("Pattern B: Safe Convex with Skip"))
story.append(body(
    "For APIs that may not be deployed yet (e.g., messaging, teams), pages use the <font face='Courier'>"
    "hasApi</font> check pattern. If the API exists, the query runs normally; if not, the query is "
    "skipped by passing <font face='Courier'>\"skip\"</font> as the arguments. This prevents runtime "
    "crashes from missing functions while maintaining React hooks ordering. Used by Messages, "
    "TeamManagement, and the permissions system."
))

story.append(h2("Pattern C: Demo Mode Fallback"))
story.append(body(
    "Pages that need to work without authentication (e.g., for demo purposes) check "
    "<font face='Courier'>isAuthenticated</font> and fall back to static mock data when the user "
    "is not logged in. This ensures the UI always shows meaningful content. Used by Clients, "
    "TimeTracking, Messages, and ClientWorkspace."
))

story.append(h2("Pattern D: Workspace-Scoped Queries"))
story.append(body(
    "Almost all Convex queries accept an optional <font face='Courier'>workspaceId</font> parameter "
    "for multi-tenancy. The WorkspaceProvider context resolves the active workspace ID and sets "
    "<font face='Courier'>isConvexConnected</font> accordingly. Pages gate their queries on this "
    "flag: if the workspace is not connected, queries are skipped to prevent errors. This creates "
    "a cascading dependency where a failing workspace query blocks all downstream data."
))

story.append(h2("Pattern E: Client Token Access"))
story.append(body(
    "Client-facing pages (ClientWorkspace) use token-based access instead of user authentication. "
    "A URL token is validated via <font face='Courier'>validateWorkspaceToken</font>, and if valid, "
    "the client can view projects, proposals, invoices, and team members. Demo tokens bypass Convex "
    "entirely and use static mock data, allowing immediate preview without backend connectivity."
))

story.append(h2("Pattern F: Subscription Tier Gating"))
story.append(body(
    "Feature access is gated by subscription tier, stored in localStorage as "
    "<font face='Courier'>axia_subscription_tier</font>. The <font face='Courier'>useSubscriptionTier</font> "
    "hook reads this value and provides <font face='Courier'>hasTierAccess(requiredTier)</font> for "
    "checking if premium features should be shown. Tier changes are client-local only and do not "
    "sync with Convex, meaning the tier state is per-browser."
))

story.append(h2("Cross-Page Data Sharing"))
story.append(body(
    "Several Convex query functions serve multiple pages simultaneously. This sharing means that "
    "when one subscription is active, the data is cached and instantly available to other components "
    "on the same page. However, it also means that a failure in one shared query can cascade across "
    "multiple pages."
))

sharing_data = [
    ["Convex Function", "Pages Using It"],
    ["clients.crud.getClients", "Clients, EvidenceExport"],
    ["clients.crud.getClientsEnriched", "Dashboard, PaymentPatterns"],
    ["billing.crud.getInvoices", "Dashboard, Invoices, Subscription, PaymentPatterns"],
    ["billing.crud.getInvoiceStats", "Dashboard, Invoices, Subscription, PaymentPatterns"],
    ["pipeline.crud.getDeals", "Dashboard, Pipeline"],
    ["pipeline.crud.getPipelineStats", "Dashboard, Pipeline"],
    ["proposals.crud.getProposals", "Dashboard, Proposals"],
    ["proposals.crud.getProposalStats", "Dashboard, Proposals"],
    ["scope.crud.getScopeDefinitions", "Dashboard, EvidenceExport, Scope"],
    ["evidence.library.getEvidenceLibraryData", "EvidenceLibrary, EvidenceExport"],
    ["tags.crud.getTags", "Tags, TeamManagement"],
]
story.append(make_table(sharing_data[0], sharing_data[1:], col_widths=[220, 220]))
story.append(PageBreak())

# ════════════════════════════════════════════════════════════════════════════════
# SECTION 5: PAGE-BY-PAGE DATA DEPENDENCIES
# ════════════════════════════════════════════════════════════════════════════════

story.append(h1("Page-by-Page Data Dependencies"))
story.append(body(
    "The following tables provide a complete inventory of every page in the application, organized "
    "by their data dependency complexity and loading state handling quality. Pages are classified "
    "into three tiers: Safe (no Convex dependencies), Good (proper loading/error/empty states), "
    "and Fixed (previously problematic, now repaired with timeout fallbacks)."
))

story.append(h2("Pages Without Convex Dependencies (Safe)"))
safe_data = [
    ["Page", "Route", "Data Source"],
    ["Landing", "/", "useAuth only"],
    ["Auth", "/auth", "useAuth + ConvexAuth"],
    ["HelpCenter", "/help-center", "Static content"],
    ["NotFound", "*", "None"],
    ["OnboardingSource", "Not routed", "localStorage"],
    ["OnboardingUserInfo", "Not routed", "localStorage"],
    ["ApiSettings", "Not routed", "Local/mock"],
]
story.append(make_table(safe_data[0], safe_data[1:], col_widths=[120, 100, 140]))
story.append(Spacer(1, 10))

story.append(h2("Pages With Proper Loading Handling (Good)"))
good_data = [
    ["Page", "Convex Queries", "Timeout", "Empty State"],
    ["Clients", "getClients", "2s", "Yes"],
    ["Projects", "getMyProjects", "2s", "Yes"],
    ["PlatformIntegrations", "getPlatformConnectionStatus", "No", "Yes"],
    ["Messages", "listChannels, listMessages", "Mock fallback", "Yes"],
    ["TeamManagement", "getMembers, getWorkspaceStats", "No", "Yes"],
    ["TimeTracking", "getCurrentSession, getSessions", "No", "Yes"],
]
story.append(make_table(good_data[0], good_data[1:], col_widths=[100, 170, 60, 60]))
story.append(Spacer(1, 10))

story.append(h2("Fixed Pages (Previously Stuck Loading)"))
fixed_data = [
    ["Page", "Problem", "Fix Applied"],
    ["Dashboard", "8 queries, AND gate, no timeout", "6s timeout + placeholder cards"],
    ["EvidenceExport", "3 queries, no timeout/error", "6s timeout + error fallback UI"],
    ["PaymentPatterns", "3 queries, no timeout", "6s timeout + retry button"],
    ["Pipeline", "3 queries, no timeout", "6s timeout + retry button"],
    ["Proposals", "No loading state at all", "Added skeleton + 6s timeout"],
    ["Invoices", "Manual timeout pattern", "Replaced with useQueryTimeout"],
    ["Reports", "Manual timeout pattern", "Replaced with useQueryTimeout"],
    ["Scope", "3 loading checks, no timeout", "6s timeout on each section"],
    ["Subscription", "2 loading states, no timeout", "6s timeout on tier + billing"],
    ["Tags", "Manual timeout pattern", "Replaced with useQueryTimeout"],
    ["Goals", "Manual timeout pattern", "Replaced with useQueryTimeout"],
]
story.append(make_table(fixed_data[0], fixed_data[1:], col_widths=[100, 170, 160]))
story.append(PageBreak())

# ════════════════════════════════════════════════════════════════════════════════
# SECTION 6: AUTHENTICATION & AUTHORIZATION
# ════════════════════════════════════════════════════════════════════════════════

story.append(h1("Authentication & Authorization Flow"))
story.append(body(
    "Axia uses a multi-layered authentication and authorization system. The primary auth system "
    "is built on @convex-dev/auth, which supports four sign-in methods: password, Google OAuth, "
    "GitHub OAuth, and email OTP. All protected routes are wrapped in a ProtectedRoute component "
    "that checks authentication status and redirects unauthenticated users to the /auth page with "
    "a return URL parameter."
))

story.append(h2("Sign-In Methods"))
auth_data = [
    ["Method", "Flow", "Storage"],
    ["Password", "signIn(signUp: true) with FormData", "Convex session cookie"],
    ["Google OAuth", "signIn('google') redirect", "Convex session cookie"],
    ["GitHub OAuth", "signIn('github') redirect", "Convex session cookie"],
    ["Email OTP", "sendCode() then verifyCode()", "Convex session cookie"],
]
story.append(make_table(auth_data[0], auth_data[1:], col_widths=[90, 180, 130]))

story.append(h2("Authorization Layers"))
story.append(body(
    "Authorization operates at three levels. First, the <b>Workspace Level</b> determines what a user "
    "can do within a workspace based on their role (owner, manager, member). The "
    "<font face='Courier'>useWorkspacePermissions</font> hook provides boolean flags like "
    "<font face='Courier'>canDeleteRecords</font> and <font face='Courier'>canShareRecords</font>. "
    "Second, the <b>Record Level</b> uses the <font face='Courier'>usePermissions</font> hook to "
    "check access to specific records based on sharing entries, team membership, and workspace role. "
    "Third, the <b>Subscription Tier</b> gates premium features based on the user's plan level, "
    "stored in localStorage."
))

story.append(h2("Client Authentication (Parallel System)"))
story.append(body(
    "Client-facing pages use a separate authentication system. Instead of Convex auth, clients "
    "are identified by their email stored in localStorage as <font face='Courier'>axia_client_email</font>. "
    "The ClientWorkspace page uses token-based access where a URL token is validated via "
    "<font face='Courier'>validateWorkspaceToken</font>. Demo tokens (prefixed with 'demo-') bypass "
    "Convex entirely and show static mock data. This parallel system allows external clients to "
    "view their project data without creating a full user account."
))
story.append(PageBreak())

# ════════════════════════════════════════════════════════════════════════════════
# SECTION 7: CONVEX BACKEND & SCHEMA
# ════════════════════════════════════════════════════════════════════════════════

story.append(h1("Convex Backend & Schema"))
story.append(body(
    "The Convex backend serves as Axia's sole data layer, providing real-time subscriptions, "
    "mutations, and actions. The schema is organized into modular table groups that map to "
    "different feature domains. All queries are reactive: when underlying data changes, subscribed "
    "components automatically receive updates via WebSocket, requiring no manual refresh or polling."
))

story.append(h2("Schema Module Map"))
schema_data = [
    ["Module", "Key Tables", "Pages Served"],
    ["authTables", "authAccounts, authSessions", "Auth"],
    ["users", "users", "All protected pages"],
    ["workspaceTables", "workspaces, workspaceMembers, workspaceInvitations", "TeamManagement, usePermissions"],
    ["teamTables", "teams, teamMemberships", "TeamManagement"],
    ["projectTables", "clients, projects, clientCompanies", "Clients, Projects, ClientDashboard"],
    ["evidenceTables", "evidenceSessions, evidenceEvents, evidenceMetadata", "EvidenceLibrary, EvidenceExport"],
    ["pipelineTables", "pipelineStages, deals", "Pipeline, Dashboard"],
    ["proposalTables", "proposals, proposalTemplates, proposalFollowUps", "Proposals, ProposalBuilder"],
    ["billingTables", "invoices, invoiceWorkLinks, paymentReminders", "Invoices, InvoiceBuilder, PaymentPatterns"],
    ["scopeTables", "scopeDefinitions, scopeChangeOrders", "Scope, Dashboard"],
    ["messagingTables", "channels, channelMembers, messages, reactions", "Messages"],
    ["tagTables", "tags", "Tags, TeamManagement"],
    ["goalTables", "goals", "Goals"],
    ["featureTables", "disputeReports, platformConnections, waitlistEntries", "Reports, PlatformIntegrations"],
]
story.append(make_table(schema_data[0], schema_data[1:], col_widths=[100, 180, 140]))

story.append(h2("safe-convex-react Design"))
story.append(body(
    "The <font face='Courier'>safe-convex-react</font> module wraps all Convex hooks to prevent "
    "runtime errors from crashing the React tree. The design follows three key principles: (1) "
    "Errors return safe defaults instead of throwing, (2) Hooks are always called in the same "
    "order using Convex's 'skip' mechanism, and (3) The new <font face='Courier'>useQueryResult</font> "
    "API returns typed <font face='Courier'>QueryResult</font> objects that distinguish between "
    "loading, error, and success states. The <font face='Courier'>useQueryTimeout</font> hook "
    "provides a 5-6 second timeout that transitions pages from loading skeletons to error states, "
    "eliminating perpetual spinners."
))
story.append(PageBreak())

# ════════════════════════════════════════════════════════════════════════════════
# SECTION 8: LOADING STATE ARCHITECTURE
# ════════════════════════════════════════════════════════════════════════════════

story.append(h1("Loading State Architecture"))
story.append(body(
    "The loading state architecture was the single most impactful area of the audit. The original "
    "system had a fundamental design flaw: <font face='Courier'>safe-convex-react</font> returned "
    "<font face='Courier'>undefined</font> for both 'still loading' and 'query errored' states, "
    "making them indistinguishable. Pages that checked <font face='Courier'>data === undefined</font> "
    "to show loading spinners would spin forever on errors, because there was no way to detect "
    "that a query had permanently failed."
))

story.append(h2("The Problem: Indistinguishable States"))
story.append(code(
    "// BEFORE: Both loading and error return undefined\n"
    "const data = useQuery(api.clients.getClients, {});\n"
    "// data === undefined  →  Still loading? OR query failed? No way to tell!\n"
    "if (data === undefined) return <Spinner />;  // Spins FOREVER on error"
))
story.append(Spacer(1, 6))

story.append(h2("The Solution: useQueryTimeout + useQueryResult"))
story.append(code(
    "// AFTER: Timeout breaks the infinite loading loop\n"
    "const data = useQuery(api.clients.getClients, {});\n"
    "const isLoading = data === undefined;\n"
    "const timedOut = useQueryTimeout(isLoading, 6000);\n"
    "\n"
    "if (isLoading && !timedOut) return <Skeleton />;\n"
    "if (isLoading && timedOut) return <ErrorState onRetry={reload} />;\n"
    "// Data loaded successfully\n"
    "return <Content data={data} />;"
))
story.append(Spacer(1, 6))

story.append(h2("The useQueryTimeout Hook"))
story.append(body(
    "The <font face='Courier'>useQueryTimeout</font> hook accepts a boolean <font face='Courier'>"
    "isLoading</font> flag and a timeout duration (default 5000ms). It returns <font face='Courier'>"
    "true</font> once the timeout expires while still loading, giving pages a clear signal to "
    "transition from the loading skeleton to an error or retry state. The hook automatically resets "
    "when loading completes, so it works correctly with Convex's reconnection behavior."
))

story.append(h2("Component Library"))
story.append(body(
    "Three reusable components were created in <font face='Courier'>QueryState.tsx</font>: "
    "<b>PageLoader</b> combines loading skeleton, timeout error, and empty state into a single "
    "wrapper. <b>QueryErrorState</b> shows an alert icon, error message, and retry button. "
    "<b>EmptyState</b> shows an inbox icon, message, and optional action button. These components "
    "ensure a consistent user experience across all pages."
))
story.append(PageBreak())

# ════════════════════════════════════════════════════════════════════════════════
# SECTION 9: SENTRY INTEGRATION
# ════════════════════════════════════════════════════════════════════════════════

story.append(h1("Sentry Error Tracking"))
story.append(body(
    "Sentry provides real-time error tracking, performance monitoring, and session replay for "
    "production debugging. The integration is designed to be zero-configuration in development "
    "(Sentry silently skips initialization if no DSN is provided) and fully featured in production."
))

story.append(h2("Configuration"))
sentry_config = [
    ["Setting", "Development", "Production"],
    ["Traces Sample Rate", "1.0 (100%)", "0.2 (20%)"],
    ["Replays Session Rate", "0 (disabled)", "0.1 (10%)"],
    ["Replays On Error Rate", "1.0 (100%)", "1.0 (100%)"],
    ["Source Maps", "Generated, not uploaded", "Generated + uploaded to Sentry"],
    ["Error Filtering", "Skip ResizeObserver, network, Convex auth", "Same + browser extension noise"],
]
story.append(make_table(sentry_config[0], sentry_config[1:], col_widths=[140, 130, 170]))

story.append(h2("Integration Points"))
story.append(bullet("<b>InstrumentationProvider:</b> Initializes Sentry on app mount, captures unhandled errors and promise rejections, reports to both Sentry and the legacy Vly error system."))
story.append(bullet("<b>safe-convex-react:</b> Reports every Convex query error to Sentry via <font face='Courier'>reportQueryError()</font>, including the query name, error message, and arguments."))
story.append(bullet("<b>ConvexErrorBoundary:</b> The top-level React error boundary catches rendering crashes and reports them to Sentry before showing the error banner."))
story.append(bullet("<b>ProtectedRoute:</b> Sets the Sentry user identity (ID, email, name, tier) when a user authenticates, and clears it on sign-out."))
story.append(bullet("<b>Vite Plugin:</b> Uploads source maps to Sentry during production builds for stack trace deobfuscation."))

story.append(h2("Environment Variables"))
story.append(code(
    "VITE_SENTRY_DSN=          # Sentry project DSN (required for production)\n"
    "VITE_SENTRY_ORG=          # Sentry organization slug\n"
    "VITE_SENTRY_PROJECT=      # Sentry project name (default: 'axia')\n"
    "SENTRY_AUTH_TOKEN=        # Auth token for source map upload (CI only)\n"
    "VITE_GIT_SHA=             # Git commit SHA for release tracking"
))
story.append(PageBreak())

# ════════════════════════════════════════════════════════════════════════════════
# SECTION 10: POSTHOG INTEGRATION
# ════════════════════════════════════════════════════════════════════════════════

story.append(h1("PostHog Product Analytics"))
story.append(body(
    "PostHog provides product analytics, feature flags, and user behavior tracking. Like Sentry, "
    "it gracefully degrades in development when no API key is configured, logging events to the "
    "console instead. In production, it captures page views, user actions, and funnel data."
))

story.append(h2("Event Catalog"))
events_data = [
    ["Event", "Trigger", "Properties"],
    ["auth_sign_in", "User signs in", "method (password/google/github/otp)"],
    ["auth_sign_up", "User creates account", "method"],
    ["auth_sign_out", "User signs out", "session_duration"],
    ["page_view", "Route change", "path, search"],
    ["sidebar_toggle", "Sidebar expand/collapse", "is_expanded"],
    ["theme_toggle", "Dark/light switch", "from, to"],
    ["client_created", "New client added", "source (manual/import)"],
    ["invoice_created", "New invoice created", "amount, client_id"],
    ["invoice_sent", "Invoice sent to client", "invoice_id, format"],
    ["proposal_created", "New proposal created", "deal_id, value"],
    ["deal_created", "New deal in pipeline", "stage, value"],
    ["deal_moved", "Deal moved between stages", "from_stage, to_stage"],
    ["evidence_export", "Evidence exported", "format, item_count"],
    ["upgrade_clicked", "Upgrade CTA clicked", "current_tier, target_tier"],
    ["convex_query_error", "Convex query fails", "queryName, error"],
    ["page_load_timeout", "Page exceeds 6s loading", "pageName, errorMessage"],
]
story.append(make_table(events_data[0], events_data[1:], col_widths=[110, 130, 170]))

story.append(h2("Feature Flags"))
story.append(body(
    "PostHog feature flags are accessible via the <font face='Courier'>isFeatureEnabled()</font> "
    "and <font face='Courier'>getFeatureFlagVariant()</font> functions in monitoring.ts. These "
    "allow gradual feature rollouts and A/B testing without code deployments. Flags fall back to "
    "default values when PostHog is not initialized."
))

story.append(h2("Environment Variables"))
story.append(code(
    "VITE_POSTHOG_KEY=         # PostHog project API key\n"
    "VITE_POSTHOG_HOST=        # PostHog host (default: https://us.i.posthog.com)\n"
    "VITE_GIT_SHA=             # Git SHA for release tracking"
))
story.append(PageBreak())

# ════════════════════════════════════════════════════════════════════════════════
# SECTION 11: ISSUES FOUND & FIXES
# ════════════════════════════════════════════════════════════════════════════════

story.append(h1("Issues Found & Fixes Applied"))
story.append(body(
    "This section documents every issue discovered during the architecture audit and the specific "
    "fix applied to each one. Issues are ordered by severity and user impact."
))

issues_data = [
    ["#", "Issue", "Root Cause", "Fix"],
    ["1", "Projects page crash", "usePermissions called in IIFE (hooks violation)", "Moved hook to top level, removed IIFE"],
    ["2", "EvidenceExport blank", "No timeout/error state on 3 queries", "Added 6s timeout + error fallback UI"],
    ["3", "Dashboard perpetual spinner", "8-query AND gate, no timeout", "Added 6s timeout + placeholder cards"],
    ["4", "safe-convex-react erases errors", "Both loading and error return undefined", "Added useQueryResult typed API + useQueryTimeout"],
    ["5", "9 pages stuck loading forever", "No timeout on useQuery results", "Added useQueryTimeout(5000-6000) to all"],
    ["6", "Zero monitoring/observability", "No error tracking or analytics", "Implemented Sentry + PostHog integration"],
    ["7", "Dark mode broken", "@theme inline bakes light-mode values", "Changed to @theme (CSS variable references)"],
    ["8", "Proposals hooks violation", "usePermissions in JSX callback", "Removed hook call, used workspace-level permission"],
]
story.append(make_table(issues_data[0], issues_data[1:], col_widths=[25, 110, 150, 170]))

story.append(h2("Detailed Fix: Projects Page Crash"))
story.append(body(
    "The Projects page crashed because <font face='Courier'>usePermissions</font> was called inside "
    "an IIFE within JSX. This violated React's Rules of Hooks in two ways: (1) the hook was inside "
    "a conditional (<font face='Courier'>selectedProjectId &&</font>), so it was skipped on the "
    "first render, and (2) it was inside a nested function, not at the top level of the component. "
    "When the auto-select useEffect set <font face='Courier'>selectedProjectId</font>, the hook "
    "suddenly appeared on the next render, adding 5 internal hooks (useWorkspaceContext + 2x "
    "useQuery + 2x useMemo) and changing the hook count. React detected this mismatch and crashed. "
    "The fix moved <font face='Courier'>usePermissions</font> to the top level, where it always "
    "runs in the same order. When the selected project is null, the hook gracefully returns "
    "NO_ACCESS with all boolean flags set to false."
))
story.append(PageBreak())

# ════════════════════════════════════════════════════════════════════════════════
# SECTION 12: ENVIRONMENT VARIABLES & DEPLOYMENT
# ════════════════════════════════════════════════════════════════════════════════

story.append(h1("Environment Variables & Deployment"))

story.append(h2("Required Environment Variables"))
env_data = [
    ["Variable", "Required", "Description"],
    ["VITE_CONVEX_URL", "Yes", "Convex deployment URL (falls back to hardcoded)"],
    ["VITE_SENTRY_DSN", "Production", "Sentry project DSN for error tracking"],
    ["VITE_SENTRY_ORG", "CI", "Sentry organization slug for source maps"],
    ["VITE_SENTRY_PROJECT", "CI", "Sentry project name (default: axia)"],
    ["SENTRY_AUTH_TOKEN", "CI", "Sentry auth token for source map upload"],
    ["VITE_POSTHOG_KEY", "Production", "PostHog project API key for analytics"],
    ["VITE_POSTHOG_HOST", "Optional", "PostHog host URL (default: us.i.posthog.com)"],
    ["VITE_GIT_SHA", "Recommended", "Git SHA for release tracking in Sentry/PostHog"],
    ["VITE_VLY_APP_ID", "Optional", "Vly editor integration ID"],
]
story.append(make_table(env_data[0], env_data[1:], col_widths=[140, 70, 240]))

story.append(h2("Build & Deploy"))
story.append(code(
    "# Development (no monitoring keys needed)\n"
    "npx vite build\n"
    "\n"
    "# Production build with source maps\n"
    "VITE_GIT_SHA=$(git rev-parse HEAD) \\\n"
    "SENTRY_AUTH_TOKEN=your-token \\\n"
    "VITE_SENTRY_DSN=https://xxx@sentry.io/xxx \\\n"
    "VITE_POSTHOG_KEY=phc_xxx \\\n"
    "npx vite build\n"
    "\n"
    "# Preview locally\n"
    "cd dist && python3 -m http.server 3000 --bind 0.0.0.0"
))
story.append(Spacer(1, 8))

story.append(h2("Sentry Source Map Upload"))
story.append(body(
    "The <font face='Courier'>@sentry/vite-plugin</font> is configured in vite.config.ts to "
    "automatically upload source maps to Sentry during production builds. This requires the "
    "<font face='Courier'>SENTRY_AUTH_TOKEN</font> environment variable to be set in CI. The "
    "plugin is disabled in development and when no auth token is provided, so it does not "
    "interfere with local development. After upload, source map files are deleted from the "
    "dist directory to prevent them from being served publicly."
))

story.append(h2("PostHog Feature Flags"))
story.append(body(
    "Feature flags can be configured in the PostHog dashboard and accessed via the "
    "<font face='Courier'>isFeatureEnabled()</font> function. Flags are evaluated server-side "
    "and cached locally. When PostHog is not configured, flags return their default values. "
    "This allows safe use of feature flags in code without worrying about the analytics service "
    "being unavailable."
))

# ── Build ──
doc.build(story)
print(f"PDF generated: {OUTPUT}")
print(f"Size: {os.path.getsize(OUTPUT) / 1024:.1f} KB")
