import { useState, useCallback, useEffect, useRef } from "react";
import { useSearchParams } from "react-router";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogDescription } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";
import { Skeleton } from "@/components/ui/skeleton";
import { toast } from "sonner";
import { useQuery, useMutation, useQueryTimeout, useConvexConnectionState } from "@/lib/safe-convex-react";
import { api } from "@/convex/_generated/api";
import { useWorkspaceContext } from "@/hooks/use-workspace"; // ponytail: workspace scoping for scope queries/mutations
import {
  Shield,
  Plus,
  AlertTriangle,
  CheckCircle2,
  Clock,
  FileText,
  TrendingUp,
  Copy,
  ChevronDown,
  ChevronUp,
  Edit3,
  Trash2,
  XCircle,
  Zap,
  BarChart3,
  GitBranch,
  DollarSign,
  Loader2,
} from "lucide-react";
import { TruthLayerBadge } from "@/components/truth-layer/TruthLayerBadge";
import { PageLayout } from "@/components/design-system/PageLayout";

// ─── Types ──────────────────────────────────────────────────────────────────

interface Deliverable {
  id: string;
  name: string;
  description: string;
  estimatedHours?: number;
  status?: "pending" | "in_progress" | "completed" | "revised";
}

interface ScopeDefinition {
  _id: string;
  title: string;
  description: string;
  projectId?: string;
  projectName?: string;
  deliverables: Deliverable[];
  totalEstimatedHours?: number;
  revisionLimit: number;
  revisionCount: number;
  status: "active" | "completed" | "disputed";
  clientApprovedAt?: number;
  approvalToken?: string;
  createdAt: number;
  updatedAt: number;
}

interface ScopeChangeOrder {
  _id: string;
  scopeId: string;
  scopeTitle?: string;
  title: string;
  description: string;
  changeType: "addition" | "modification" | "removal" | "revision";
  impact: {
    hoursAdded: number;
    costImpact: number;
    deadlineImpact?: number;
  };
  reason: string;
  status: "pending" | "approved" | "rejected" | "auto_generated";
  autoGenerated?: boolean;
  originalLimit?: number;
  newLimit?: number;
  clientApprovalToken?: string;
  createdAt: number;
  clientApprovedAt?: number;
}

// ─── Helper Functions ───────────────────────────────────────────────────────

function formatDate(ts: number): string {
  return new Date(ts).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

function timeAgo(ts: number): string {
  const diff = Date.now() - ts;
  const minutes = Math.floor(diff / 60000);
  const hours = Math.floor(minutes / 60);
  const days = Math.floor(hours / 24);
  if (days > 0) return `${days}d ago`;
  if (hours > 0) return `${hours}h ago`;
  return `${minutes}m ago`;
}

function getChangeTypeIcon(type: string) {
  switch (type) {
    case "addition": return <Plus className="w-3.5 h-3.5 text-blue-500" />;
    case "modification": return <Edit3 className="w-3.5 h-3.5 text-amber-500" />;
    case "removal": return <Trash2 className="w-3.5 h-3.5 text-red-500" />;
    case "revision": return <GitBranch className="w-3.5 h-3.5 text-purple-500" />;
    default: return <FileText className="w-3.5 h-3.5" />;
  }
}

function getChangeTypeLabel(type: string) {
  return type.charAt(0).toUpperCase() + type.slice(1);
}

function getStatusBadge(status: string) {
  switch (status) {
    case "approved":
    case "formalized":
      return <Badge className="bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400 border-0 text-xs"><CheckCircle2 className="w-3 h-3 mr-1" />{status === "formalized" ? "Formalized" : "Approved"}</Badge>;
    case "pending":
      return <Badge className="bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-400 border-0 text-xs"><Clock className="w-3 h-3 mr-1" />Pending</Badge>;
    case "rejected":
      return <Badge className="bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400 border-0 text-xs"><XCircle className="w-3 h-3 mr-1" />Rejected</Badge>;
    case "auto_generated":
      return <Badge className="bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-400 border-0 text-xs"><Zap className="w-3 h-3 mr-1" />Auto-Detected</Badge>;
    case "active":
      return <Badge className="bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400 border-0 text-xs">Active</Badge>;
    case "completed":
      return <Badge className="bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400 border-0 text-xs">Completed</Badge>;
    case "disputed":
      return <Badge className="bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400 border-0 text-xs">Disputed</Badge>;
    case "draft":
      return <Badge className="bg-slate-100 text-slate-800 dark:bg-slate-900/30 dark:text-slate-400 border-0 text-xs">Draft</Badge>;
    default:
      return <Badge variant="secondary">{status}</Badge>;
  }
}

function getDeliverableStatusIcon(status?: string) {
  switch (status) {
    case "completed": return <CheckCircle2 className="w-4 h-4 text-green-500" />;
    case "in_progress": return <Clock className="w-4 h-4 text-blue-500" />;
    case "revised": return <Edit3 className="w-4 h-4 text-purple-500" />;
    case "pending": return <Clock className="w-4 h-4 text-muted-foreground" />;
    default: return <Clock className="w-4 h-4 text-muted-foreground" />;
  }
}

// ─── Scope Creep Detection ──────────────────────────────────────────────────

function calculateScopeHealth(scope: ScopeDefinition, changeOrders: ScopeChangeOrder[]) {
  const scopeChanges = changeOrders.filter(co => co.scopeId === scope._id);
  const pendingChanges = scopeChanges.filter(co => co.status === "pending" || co.status === "auto_generated");
  const revisionUsage = scope.revisionLimit > 0 ? (scope.revisionCount / scope.revisionLimit) * 100 : 0;
  const totalHoursAdded = scopeChanges.reduce((sum, co) => sum + co.impact.hoursAdded, 0);
  const totalCostImpact = scopeChanges.reduce((sum, co) => sum + co.impact.costImpact, 0);
  const hoursOverrun = scope.totalEstimatedHours ? (totalHoursAdded / scope.totalEstimatedHours) * 100 : 0;

  let riskLevel: "low" | "medium" | "high" = "low";
  if (revisionUsage >= 100 || hoursOverrun > 30 || pendingChanges.length >= 3) riskLevel = "high";
  else if (revisionUsage >= 66 || hoursOverrun > 15 || pendingChanges.length >= 2) riskLevel = "medium";

  const completedDeliverables = scope.deliverables.filter(d => d.status === "completed").length;
  const progressPercent = scope.deliverables.length > 0 ? (completedDeliverables / scope.deliverables.length) * 100 : 0;

  return {
    riskLevel,
    revisionUsage,
    totalHoursAdded,
    totalCostImpact,
    hoursOverrun,
    pendingChanges: pendingChanges.length,
    completedDeliverables,
    totalDeliverables: scope.deliverables.length,
    progressPercent,
  };
}

// ─── Sub-Components ─────────────────────────────────────────────────────────

function ScopeHealthBar({ health }: { health: ReturnType<typeof calculateScopeHealth> }) {
  const barColor = health.riskLevel === "high" ? "bg-red-500" : health.riskLevel === "medium" ? "bg-amber-500" : "bg-green-500";
  return (
    <div className="space-y-2">
      <div className="flex items-center justify-between text-xs">
        <span className="text-muted-foreground">Scope Health</span>
        <span className={`font-semibold ${health.riskLevel === "high" ? "text-red-600 dark:text-red-400" : health.riskLevel === "medium" ? "text-amber-600 dark:text-amber-400" : "text-green-600 dark:text-green-400"}`}>
          {health.riskLevel === "high" ? "High Risk" : health.riskLevel === "medium" ? "Moderate Risk" : "Healthy"}
        </span>
      </div>
      <div className="h-2 bg-muted rounded-full overflow-hidden">
        <div className={`h-full rounded-full transition-all ${barColor}`} style={{ width: `${Math.max(5, 100 - health.hoursOverrun - health.revisionUsage * 0.3)}%` }} />
      </div>
    </div>
  );
}

function ScopeCard({
  scope,
  changeOrders,
  isSelected,
  onSelect,
  onDelete,
  deleting,
}: {
  scope: ScopeDefinition;
  changeOrders: ScopeChangeOrder[];
  isSelected: boolean;
  onSelect: () => void;
  onDelete: () => void;
  deleting: boolean;
}) {
  const health = calculateScopeHealth(scope, changeOrders);
  const [expanded, setExpanded] = useState(isSelected);

  return (
    <Card className={`p-0 overflow-hidden transition-all border ${isSelected ? "border-primary ring-1 ring-primary/20" : "border-border hover:border-primary/30"}`}>
      {/* Header */}
      <div
        className="p-5 cursor-pointer"
        onClick={() => { onSelect(); setExpanded(!expanded); }}
      >
        <div className="flex items-start justify-between">
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 mb-1">
              <h3 className="font-bold text-foreground truncate">{scope.title}</h3>
              {getStatusBadge(scope.status)}
              <TruthLayerBadge
                score={scope.clientApprovedAt ? 85 : scope.approvalToken ? 50 : 20}
                size="sm"
                showScore={true}
                details={[
                  { label: "Client approved", verified: !!scope.clientApprovedAt },
                  { label: "Approval token generated", verified: !!scope.approvalToken },
                  { label: "Deliverables defined", verified: scope.deliverables.length > 0 },
                  { label: "Scope is active", verified: scope.status === "active" },
                ]}
              />
            </div>
            <p className="text-sm text-muted-foreground line-clamp-2">{scope.description}</p>
            {scope.projectName && (
              <p className="text-xs text-muted-foreground mt-1.5 flex items-center gap-1">
                <BriefcaseIcon className="w-3 h-3" /> {scope.projectName}
              </p>
            )}
          </div>
          <div className="flex items-center gap-2 flex-shrink-0 ml-4">
            <Button
              variant="ghost"
              size="sm"
              className="h-7 w-7 p-0 text-muted-foreground hover:text-red-600"
              onClick={(e) => {
                e.stopPropagation();
                onDelete();
              }}
              disabled={deleting}
            >
              {deleting ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Trash2 className="w-3.5 h-3.5" />}
            </Button>
            {expanded ? <ChevronUp className="w-5 h-5 text-muted-foreground" /> : <ChevronDown className="w-5 h-5 text-muted-foreground" />}
          </div>
        </div>

        {/* Quick Stats */}
        <div className="grid grid-cols-4 gap-3 mt-4">
          <div className="text-center">
            <p className="text-lg font-bold text-foreground">{scope.deliverables.length}</p>
            <p className="text-[10px] text-muted-foreground uppercase tracking-wider">Deliverables</p>
          </div>
          <div className="text-center">
            <p className="text-lg font-bold text-foreground">{scope.revisionCount}/{scope.revisionLimit}</p>
            <p className="text-[10px] text-muted-foreground uppercase tracking-wider">Revisions</p>
          </div>
          <div className="text-center">
            <p className="text-lg font-bold text-foreground">{health.totalHoursAdded}h</p>
            <p className="text-[10px] text-muted-foreground uppercase tracking-wider">Hours Added</p>
          </div>
          <div className="text-center">
            <p className={`text-lg font-bold ${health.riskLevel === "high" ? "text-red-600 dark:text-red-400" : health.riskLevel === "medium" ? "text-amber-600 dark:text-amber-400" : "text-green-600 dark:text-green-400"}`}>
              {health.riskLevel === "high" ? "High" : health.riskLevel === "medium" ? "Med" : "Low"}
            </p>
            <p className="text-[10px] text-muted-foreground uppercase tracking-wider">Risk</p>
          </div>
        </div>

        <div className="mt-3">
          <ScopeHealthBar health={health} />
        </div>
      </div>

      {/* Expanded Content */}
      {expanded && (
        <div className="border-t border-border px-5 pb-5 pt-4 space-y-5">
          {/* Deliverables */}
          <div>
            <h4 className="text-sm font-semibold text-foreground mb-3 flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-primary" />
              Deliverables ({health.completedDeliverables}/{health.totalDeliverables})
            </h4>
            {scope.deliverables.length === 0 ? (
              <p className="text-xs text-muted-foreground italic">No deliverables defined yet</p>
            ) : (
              <div className="space-y-2">
                {scope.deliverables.map((d) => (
                  <div key={d.id} className="flex items-start gap-3 p-2.5 rounded-lg bg-muted/50">
                    <div className="mt-0.5">{getDeliverableStatusIcon(d.status)}</div>
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium text-foreground">{d.name}</p>
                      <p className="text-xs text-muted-foreground">{d.description}</p>
                    </div>
                    {d.estimatedHours && (
                      <span className="text-xs text-muted-foreground whitespace-nowrap">{d.estimatedHours}h</span>
                    )}
                  </div>
                ))}
              </div>
            )}
            <div className="mt-3">
              <Progress value={health.progressPercent} className="h-1.5" />
              <p className="text-xs text-muted-foreground mt-1">{Math.round(health.progressPercent)}% complete</p>
            </div>
          </div>

          {/* Revision Tracking */}
          <div>
            <h4 className="text-sm font-semibold text-foreground mb-2 flex items-center gap-2">
              <GitBranch className="w-4 h-4 text-primary" />
              Revision Tracking
            </h4>
            <div className="p-3 rounded-lg bg-muted/50 space-y-2">
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">Revisions Used</span>
                <span className="font-medium">{scope.revisionCount} of {scope.revisionLimit}</span>
              </div>
              <Progress value={health.revisionUsage} className="h-1.5" />
              {health.revisionUsage >= 100 && (
                <div className="flex items-center gap-1.5 text-xs text-red-600 dark:text-red-400">
                  <AlertTriangle className="w-3 h-3" />
                  Revision limit exceeded — new changes auto-detected as scope creep
                </div>
              )}
              {health.revisionUsage >= 66 && health.revisionUsage < 100 && (
                <div className="flex items-center gap-1.5 text-xs text-amber-600 dark:text-amber-400">
                  <AlertTriangle className="w-3 h-3" />
                  Approaching revision limit — formalize remaining changes carefully
                </div>
              )}
            </div>
          </div>

          {/* Client Approval */}
          <div>
            <h4 className="text-sm font-semibold text-foreground mb-2 flex items-center gap-2">
              <Shield className="w-4 h-4 text-primary" />
              Client Approval
            </h4>
            <div className="p-3 rounded-lg bg-muted/50">
              {scope.clientApprovedAt ? (
                <div className="flex items-center gap-2 text-sm">
                  <CheckCircle2 className="w-4 h-4 text-green-500" />
                  <span className="text-green-700 dark:text-green-400 font-medium">Approved by client</span>
                  <span className="text-muted-foreground">on {formatDate(scope.clientApprovedAt)}</span>
                </div>
              ) : (
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2 text-sm">
                    <Clock className="w-4 h-4 text-amber-500" />
                    <span className="text-amber-700 dark:text-amber-400 font-medium">Awaiting client approval</span>
                  </div>
                  {scope.approvalToken && (
                    <Button
                      variant="outline"
                      size="sm"
                      className="text-xs h-7"
                      onClick={(e) => {
                        e.stopPropagation();
                        const url = `${window.location.origin}/scope/approve/${scope.approvalToken}`;
                        navigator.clipboard.writeText(url);
                        toast.success("Approval link copied to clipboard!");
                      }}
                    >
                      <Copy className="w-3 h-3 mr-1" />
                      Copy Approval Link
                    </Button>
                  )}
                </div>
              )}
            </div>
          </div>

          {/* Impact Summary */}
          <div>
            <h4 className="text-sm font-semibold text-foreground mb-2 flex items-center gap-2">
              <BarChart3 className="w-4 h-4 text-primary" />
              Scope Impact Summary
            </h4>
            <div className="grid grid-cols-3 gap-3">
              <div className="p-3 rounded-lg bg-muted/50 text-center">
                <p className="text-lg font-bold text-foreground">+{health.totalHoursAdded}h</p>
                <p className="text-[10px] text-muted-foreground uppercase">Hours Added</p>
              </div>
              <div className="p-3 rounded-lg bg-muted/50 text-center">
                <p className="text-lg font-bold text-foreground">${health.totalCostImpact.toLocaleString()}</p>
                <p className="text-[10px] text-muted-foreground uppercase">Cost Impact</p>
              </div>
              <div className="p-3 rounded-lg bg-muted/50 text-center">
                <p className="text-lg font-bold text-foreground">{health.pendingChanges}</p>
                <p className="text-[10px] text-muted-foreground uppercase">Pending Changes</p>
              </div>
            </div>
          </div>
        </div>
      )}
    </Card>
  );
}

function BriefcaseIcon({ className }: { className?: string }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <rect x="2" y="7" width="20" height="14" rx="2" ry="2" />
      <path d="M16 7V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v2" />
    </svg>
  );
}

// ─── ScopeCard with its own change orders query ─────────────────────────────

function ScopeCardContainer({
  scope,
  isSelected,
  onSelect,
  onDelete,
  deleting,
  onMetricsReady,
}: {
  scope: ScopeDefinition;
  isSelected: boolean;
  onSelect: () => void;
  onDelete: () => void;
  deleting: boolean;
  onMetricsReady: (scopeId: string, metrics: { pendingChanges: number; costAtRisk: number; hoursAtRisk: number }) => void;
}) {
  const changeOrders = useQuery(api.scope.crud.getChangeOrders, { scopeId: scope._id as any });

  const prevMetricsRef = useRef<string>("");

  useEffect(() => {
    if (changeOrders && Array.isArray(changeOrders)) {
      const pending = (changeOrders as ScopeChangeOrder[]).filter(co => co.status === "pending" || co.status === "auto_generated");
      const costAtRisk = pending.reduce((sum: number, co: ScopeChangeOrder) => sum + co.impact.costImpact, 0);
      const hoursAtRisk = pending.reduce((sum: number, co: ScopeChangeOrder) => sum + co.impact.hoursAdded, 0);
      const key = `${pending.length}-${costAtRisk}-${hoursAtRisk}`;
      if (key !== prevMetricsRef.current) {
        prevMetricsRef.current = key;
        onMetricsReady(scope._id, { pendingChanges: pending.length, costAtRisk, hoursAtRisk });
      }
    }
  }, [changeOrders, scope._id, onMetricsReady]);

  return (
    <ScopeCard
      scope={scope}
      changeOrders={(changeOrders as ScopeChangeOrder[]) ?? []}
      isSelected={isSelected}
      onSelect={onSelect}
      onDelete={onDelete}
      deleting={deleting}
    />
  );
}

// ─── Loading Skeletons ──────────────────────────────────────────────────────

function SummaryCardSkeleton() {
  return (
    <Card className="p-4 bg-card rounded-xl border border-border">
      <div className="flex items-center gap-3">
        <Skeleton className="w-8 h-8 rounded-lg" />
        <div>
          <Skeleton className="h-7 w-10 mb-1" />
          <Skeleton className="h-3 w-20" />
        </div>
      </div>
    </Card>
  );
}

function ScopeCardSkeleton() {
  return (
    <Card className="p-0 overflow-hidden border border-border">
      <div className="p-5">
        <div className="flex items-start justify-between">
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 mb-1">
              <Skeleton className="h-5 w-48" />
              <Skeleton className="h-4 w-14 rounded-full" />
            </div>
            <Skeleton className="h-4 w-full mt-2" />
            <Skeleton className="h-3 w-32 mt-2" />
          </div>
          <Skeleton className="w-5 h-5 ml-4" />
        </div>
        <div className="grid grid-cols-4 gap-3 mt-4">
          {[0, 1, 2, 3].map(i => (
            <div key={i} className="text-center">
              <Skeleton className="h-6 w-8 mx-auto mb-1" />
              <Skeleton className="h-2 w-14 mx-auto" />
            </div>
          ))}
        </div>
        <Skeleton className="h-2 w-full rounded-full mt-3" />
      </div>
    </Card>
  );
}

function ChangeOrderSkeleton() {
  return (
    <Card className="p-0 overflow-hidden border border-border">
      <div className="p-4 space-y-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Skeleton className="w-3.5 h-3.5" />
            <Skeleton className="h-4 w-48" />
          </div>
          <Skeleton className="h-3 w-12" />
        </div>
        <Skeleton className="h-3 w-full" />
        <div className="grid grid-cols-3 gap-3">
          {[0, 1, 2].map(i => (
            <Skeleton key={i} className="h-14 rounded-lg" />
          ))}
        </div>
      </div>
    </Card>
  );
}

// ─── Main Scope Page ────────────────────────────────────────────────────────

export default function Scope() {
  const [searchParams] = useSearchParams();
  const proposalIdFromUrl = searchParams.get("proposalId");

  // ponytail: extract active workspace id so scope definitions are scoped per-workspace (prevents cross-workspace data leak)
  const { activeWorkspaceId, isConvexConnected } = useWorkspaceContext();
  const workspaceId = isConvexConnected ? activeWorkspaceId : undefined;

  const [selectedScopeId, setSelectedScopeId] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState("definitions");

  // Dialog states
  const [showCreateScope, setShowCreateScope] = useState(!!proposalIdFromUrl);
  const [showCreateChangeOrder, setShowCreateChangeOrder] = useState(false);
  const [showFormalizeDialog, setShowFormalizeDialog] = useState(false);

  // Create scope form
  const [newScopeTitle, setNewScopeTitle] = useState(proposalIdFromUrl ? "Scope for Proposal" : "");
  const [newScopeDescription, setNewScopeDescription] = useState(proposalIdFromUrl ? "Scope definition from signed proposal" : "");
  const [newScopeRevisionLimit, setNewScopeRevisionLimit] = useState("3");
  const [newScopeEstimatedHours, setNewScopeEstimatedHours] = useState("");

  // Create change order form
  const [coTitle, setCoTitle] = useState("");
  const [coDescription, setCoDescription] = useState("");
  const [coChangeType, setCoChangeType] = useState<"addition" | "modification" | "removal" | "revision">("addition");
  const [coHoursAdded, setCoHoursAdded] = useState("");
  const [coCostImpact, setCoCostImpact] = useState("");
  const [coDeadlineImpact, setCoDeadlineImpact] = useState("");
  const [coReason, setCoReason] = useState("");

  // Formalize form
  const [formChangeDesc, setFormChangeDesc] = useState("");
  const [formOriginalScope, setFormOriginalScope] = useState("");
  const [formNewScope, setFormNewScope] = useState("");
  const [formTimeImpact, setFormTimeImpact] = useState("");
  const [formBudgetImpact, setFormBudgetImpact] = useState("");
  const [formDeliverableImpact, setFormDeliverableImpact] = useState("");
  const [formClientAck, setFormClientAck] = useState("");

  // ─── Convex Queries ──────────────────────────────────────────────────────
  // ponytail: pass workspaceId to scope the by_workspace index (falls back to by_user when undefined)
  const scopes = useQuery(api.scope.crud.getScopeDefinitions, { workspaceId: workspaceId as any }) as ScopeDefinition[] | undefined;
  const selectedScopeChangeOrders = useQuery(
    selectedScopeId ? api.scope.crud.getChangeOrders : "skip",
    selectedScopeId ? { scopeId: selectedScopeId as any } : "skip"
  ) as ScopeChangeOrder[] | undefined;

  // Fetch proposal data if coming from proposal page
  const proposalData = useQuery(
    proposalIdFromUrl ? api.proposals.crud.getProposal : "skip",
    proposalIdFromUrl ? { proposalId: proposalIdFromUrl as any } : "skip"
  ) as any | undefined;

  // ─── Convex Mutations ────────────────────────────────────────────────────
  const createScopeMutation = useMutation(api.scope.crud.createScopeDefinition);
  const recordRevisionMutation = useMutation(api.scope.crud.recordRevision);
  const approveChangeOrderMutation = useMutation(api.scope.crud.approveChangeOrder);
  const deleteScopeMutation = useMutation(api.scope.crud.deleteScopeDefinition);

  // ─── Aggregated Metrics ──────────────────────────────────────────────────
  const [metricsMap, setMetricsMap] = useState<Record<string, { pendingChanges: number; costAtRisk: number; hoursAtRisk: number }>>({});

  const handleMetricsReady = useCallback((scopeId: string, metrics: { pendingChanges: number; costAtRisk: number; hoursAtRisk: number }) => {
    setMetricsMap(prev => {
      const prevMetrics = prev[scopeId];
      if (prevMetrics &&
        prevMetrics.pendingChanges === metrics.pendingChanges &&
        prevMetrics.costAtRisk === metrics.costAtRisk &&
        prevMetrics.hoursAtRisk === metrics.hoursAtRisk) {
        return prev;
      }
      return { ...prev, [scopeId]: metrics };
    });
  }, []);

  // Auto-select first scope when data loads
  useEffect(() => {
    if (scopes && scopes.length > 0 && !selectedScopeId) {
      setSelectedScopeId(scopes[0]._id);
    }
  }, [scopes, selectedScopeId]);

  // Pre-populate scope form from proposal data when navigating from Proposals page
  useEffect(() => {
    if (proposalIdFromUrl && proposalData && showCreateScope) {
      if (proposalData.title && newScopeTitle === "Scope for Proposal") {
        setNewScopeTitle(`Scope: ${proposalData.title}`);
      }
      if (proposalData.sections) {
        // Extract text sections to build a richer description
        const textSections = proposalData.sections
          .filter((s: any) => s.type === "text" || s.type === "heading")
          .map((s: any) => s.content)
          .filter(Boolean)
          .slice(0, 3)
          .join("; ");
        if (textSections && newScopeDescription === "Scope definition from signed proposal") {
          setNewScopeDescription(textSections);
        }
      }
      if (proposalData.totalValue && !newScopeEstimatedHours) {
        // Estimate hours from total value assuming a default rate
        const estimatedHours = Math.round(proposalData.totalValue / 75);
        setNewScopeEstimatedHours(String(estimatedHours > 0 ? estimatedHours : 40));
      }
    }
  }, [proposalIdFromUrl, proposalData, showCreateScope]);

  // ─── Computed Values ─────────────────────────────────────────────────────
  const selectedScope = scopes?.find(s => s._id === selectedScopeId) ?? null;

  const totalScopes = scopes?.length ?? 0;
  const activeScopes = scopes?.filter(s => s.status === "active").length ?? 0;
  const totalPendingChanges = Object.values(metricsMap).reduce((sum, m) => sum + m.pendingChanges, 0);
  const totalCostAtRisk = Object.values(metricsMap).reduce((sum, m) => sum + m.costAtRisk, 0);
  const totalHoursAtRisk = Object.values(metricsMap).reduce((sum, m) => sum + m.hoursAtRisk, 0);
  const totalUnformalized = (selectedScopeChangeOrders ?? []).filter(co => co.status === "pending" || co.status === "auto_generated").length;

  // ─── Mutation Handlers ──────────────────────────────────────────────────
  const handleCreateScope = async () => {
    if (!newScopeTitle || !newScopeDescription) {
      toast.error("Please fill in all required fields");
      return;
    }
    try {
      await createScopeMutation({
        workspaceId: workspaceId as any, // ponytail: stamp the new scope definition with the active workspace
        title: newScopeTitle,
        description: newScopeDescription,
        revisionLimit: parseInt(newScopeRevisionLimit) || 3,
        totalEstimatedHours: newScopeEstimatedHours ? parseInt(newScopeEstimatedHours) : undefined,
        deliverables: [],
        proposalId: proposalIdFromUrl || undefined,
      } as any);
      toast.success("Scope definition created successfully!");
      setShowCreateScope(false);
      setNewScopeTitle("");
      setNewScopeDescription("");
      setNewScopeRevisionLimit("3");
      setNewScopeEstimatedHours("");
    } catch (err: any) {
      toast.error(err?.message || "Failed to create scope definition");
    }
  };

  const handleCreateChangeOrder = async () => {
    if (!selectedScopeId || !coTitle || !coDescription || !coHoursAdded || !coCostImpact || !coReason) {
      toast.error("Please fill in all required fields");
      return;
    }
    try {
      const result = await recordRevisionMutation({
        scopeId: selectedScopeId as any,
        title: coTitle,
        description: coDescription,
        changeType: coChangeType,
        hoursAdded: parseFloat(coHoursAdded) || 0,
        costImpact: parseFloat(coCostImpact) || 0,
        deadlineImpact: coDeadlineImpact ? parseFloat(coDeadlineImpact) : undefined,
        reason: coReason,
      } as any);
      const autoGen = (result as any)?.autoGenerated;
      if (autoGen) {
        toast.warning("Revision limit exceeded — change order auto-detected as scope creep");
      } else {
        toast.success("Change order recorded successfully!");
      }
      setShowCreateChangeOrder(false);
      setCoTitle("");
      setCoDescription("");
      setCoChangeType("addition");
      setCoHoursAdded("");
      setCoCostImpact("");
      setCoDeadlineImpact("");
      setCoReason("");
    } catch (err: any) {
      toast.error(err?.message || "Failed to record change order");
    }
  };

  const handleApproveChangeOrder = async (changeOrderId: string) => {
    try {
      await approveChangeOrderMutation({ changeOrderId: changeOrderId as any });
      toast.success("Change order approved!");
    } catch (err: any) {
      toast.error(err?.message || "Failed to approve change order");
    }
  };

  const handleDeleteScope = async (scopeId: string) => {
    try {
      await deleteScopeMutation({ scopeId: scopeId as any });
      toast.success("Scope definition deleted");
      if (selectedScopeId === scopeId) {
        setSelectedScopeId(scopes?.[0]?._id ?? null);
      }
    } catch (err: any) {
      toast.error(err?.message || "Failed to delete scope definition");
    }
  };

  const handleFormalize = () => {
    if (!formChangeDesc || !formOriginalScope || !formNewScope) {
      toast.error("Please fill in all required fields");
      return;
    }
    toast.info("Formalization will be available in a future update");
    setShowFormalizeDialog(false);
    setFormChangeDesc("");
    setFormOriginalScope("");
    setFormNewScope("");
    setFormTimeImpact("");
    setFormBudgetImpact("");
    setFormDeliverableImpact("");
    setFormClientAck("");
  };

  // ─── Loading State ──────────────────────────────────────────────────────
  const { isDisconnected } = useConvexConnectionState();
  const isLoading = scopes === undefined;
  const timedOut = useQueryTimeout(isLoading, 3000);
  const showLoading = isLoading && !timedOut && !isDisconnected;

  return (
    <div className="w-full min-h-screen bg-background">
      <PageLayout spaced>
        {/* Page Header — ponytail: responsive, stacks on mobile */}
        <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
          <div>
            <h1 className="text-3xl font-bold text-foreground tracking-tight flex items-center gap-3">
              <Shield className="w-8 h-8 text-primary shrink-0" />
              Scope Protection
            </h1>
            <p className="text-muted-foreground mt-1">
              Define project scope, track changes, formalize scope creep, and protect your income
            </p>
          </div>
          <div className="flex gap-2 flex-wrap">
            <Button
              onClick={() => setShowFormalizeDialog(true)}
              variant="outline"
              size="sm"
            >
              <FileText className="w-4 h-4 mr-2" />
              Formalize Change
            </Button>
            <Button
              onClick={() => setShowCreateScope(true)}
              size="sm"
              className="bg-primary hover:bg-primary/90"
            >
              <Plus className="w-4 h-4 mr-2" />
              New Scope
            </Button>
          </div>
        </div>

        {/* Summary Cards */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {showLoading ? (
            <>
              <SummaryCardSkeleton />
              <SummaryCardSkeleton />
              <SummaryCardSkeleton />
              <SummaryCardSkeleton />
            </>
          ) : (
            <>
              <Card className="p-4 bg-card rounded-xl border border-border">
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-lg bg-blue-100 dark:bg-blue-900/30">
                    <Shield className="w-4 h-4 text-blue-600 dark:text-blue-400" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-foreground">{totalScopes}</p>
                    <p className="text-xs text-muted-foreground">Active Scopes</p>
                  </div>
                </div>
              </Card>
              <Card className="p-4 bg-card rounded-xl border border-border">
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-lg bg-amber-100 dark:bg-amber-900/30">
                    <AlertTriangle className="w-4 h-4 text-amber-600 dark:text-amber-400" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-foreground">{totalPendingChanges}</p>
                    <p className="text-xs text-muted-foreground">Pending Changes</p>
                  </div>
                </div>
              </Card>
              <Card className="p-4 bg-card rounded-xl border border-border">
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-lg bg-red-100 dark:bg-red-900/30">
                    <DollarSign className="w-4 h-4 text-red-600 dark:text-red-400" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-foreground">${totalCostAtRisk.toLocaleString()}</p>
                    <p className="text-xs text-muted-foreground">Value at Risk</p>
                  </div>
                </div>
              </Card>
              <Card className="p-4 bg-card rounded-xl border border-border">
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-lg bg-purple-100 dark:bg-purple-900/30">
                    <FileText className="w-4 h-4 text-purple-600 dark:text-purple-400" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-foreground">{totalUnformalized}</p>
                    <p className="text-xs text-muted-foreground">Unformalized</p>
                  </div>
                </div>
              </Card>
            </>
          )}
        </div>

        {/* Scope Creep Alert */}
        {!isLoading && (totalPendingChanges > 0 || totalUnformalized > 0) && (
          <div className="p-4 bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-800 rounded-xl">
            <div className="flex items-start gap-3">
              <AlertTriangle className="w-5 h-5 text-amber-600 dark:text-amber-400 mt-0.5 flex-shrink-0" />
              <div className="flex-1">
                <p className="font-bold text-sm text-amber-800 dark:text-amber-200">Scope Creep Warning</p>
                <p className="text-xs text-amber-700 dark:text-amber-300 mt-1">
                  You have {totalPendingChanges} pending change{totalPendingChanges !== 1 ? "s" : ""} and {totalUnformalized} unformalized scope change{totalUnformalized !== 1 ? "s" : ""}.
                  Unformalized scope changes put <strong>${totalCostAtRisk.toLocaleString()}</strong> at risk.
                  Formalize changes to create legally-referencable records and protect your income.
                </p>
                <Button
                  onClick={() => setShowFormalizeDialog(true)}
                  size="sm"
                  className="mt-2 bg-amber-600 hover:bg-amber-700 text-white h-7 text-xs"
                >
                  <FileText className="w-3 h-3 mr-1" />
                  Formalize Now
                </Button>
              </div>
            </div>
          </div>
        )}

        {/* Tabs */}
        <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-6">
          <TabsList className="bg-muted/50">
            <TabsTrigger value="definitions" className="text-xs">
              <Shield className="w-3.5 h-3.5 mr-1.5" />
              Scope Definitions
            </TabsTrigger>
            <TabsTrigger value="changes" className="text-xs">
              <GitBranch className="w-3.5 h-3.5 mr-1.5" />
              Change Orders
              {totalPendingChanges > 0 && (
                <Badge className="ml-1.5 bg-amber-500 text-white text-[10px] h-4 min-w-4 px-1">{totalPendingChanges}</Badge>
              )}
            </TabsTrigger>
            <TabsTrigger value="formalizations" className="text-xs">
              <FileText className="w-3.5 h-3.5 mr-1.5" />
              Formalizations
              {totalUnformalized > 0 && (
                <Badge className="ml-1.5 bg-purple-500 text-white text-[10px] h-4 min-w-4 px-1">{totalUnformalized}</Badge>
              )}
            </TabsTrigger>
          </TabsList>

          {/* ─── Scope Definitions Tab ────────────────────────────────── */}
          <TabsContent value="definitions" className="space-y-4">
            {showLoading ? (
              <div className="space-y-4">
                <ScopeCardSkeleton />
                <ScopeCardSkeleton />
              </div>
            ) : !scopes || scopes.length === 0 ? (
              <Card className="p-8 bg-card rounded-xl border border-border text-center">
                <Shield className="w-12 h-12 text-muted-foreground/30 mx-auto mb-4" />
                <h3 className="text-lg font-semibold text-foreground mb-2">No Scope Definitions Yet</h3>
                <p className="text-sm text-muted-foreground mb-4">
                  Create your first scope definition to start tracking deliverables, revisions, and scope changes.
                </p>
                <Button onClick={() => setShowCreateScope(true)} className="bg-primary hover:bg-primary/90">
                  <Plus className="w-4 h-4 mr-2" />
                  Create Scope Definition
                </Button>
              </Card>
            ) : (
              <div className="space-y-4">
                {scopes.map((scope) => (
                  <ScopeCardContainer
                    key={scope._id}
                    scope={scope}
                    isSelected={selectedScopeId === scope._id}
                    onSelect={() => setSelectedScopeId(scope._id)}
                    onDelete={() => handleDeleteScope(scope._id)}
                    deleting={false}
                    onMetricsReady={handleMetricsReady}
                  />
                ))}
              </div>
            )}
          </TabsContent>

          {/* ─── Change Orders Tab ────────────────────────────────────── */}
          <TabsContent value="changes" className="space-y-4">
            {showLoading ? (
              <div className="space-y-3">
                <ChangeOrderSkeleton />
                <ChangeOrderSkeleton />
              </div>
            ) : (
              <>
                {scopes && scopes.length > 0 && (
                  <div className="flex items-center gap-2 mb-2">
                    <span className="text-sm text-muted-foreground">Showing changes for:</span>
                    <Select
                      value={selectedScopeId || ""}
                      onValueChange={(v) => setSelectedScopeId(v)}
                    >
                      <SelectTrigger className="w-[280px] h-8 text-xs">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        {scopes.map((s) => (
                          <SelectItem key={s._id} value={s._id}>{s.title}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <Button
                      variant="outline"
                      size="sm"
                      className="h-8 text-xs ml-auto"
                      onClick={() => setShowCreateChangeOrder(true)}
                      disabled={!selectedScopeId}
                    >
                      <Plus className="w-3 h-3 mr-1" />
                      Record Change
                    </Button>
                  </div>
                )}

                {!selectedScopeId ? (
                  <Card className="p-6 bg-card rounded-xl border border-border text-center">
                    <GitBranch className="w-10 h-10 text-muted-foreground/30 mx-auto mb-3" />
                    <h3 className="text-sm font-semibold text-foreground mb-1">Select a Scope</h3>
                    <p className="text-xs text-muted-foreground">
                      Select a scope definition to view its change orders.
                    </p>
                  </Card>
                ) : selectedScopeChangeOrders === undefined ? (
                  <div className="space-y-3">
                    <ChangeOrderSkeleton />
                    <ChangeOrderSkeleton />
                  </div>
                ) : selectedScopeChangeOrders.length === 0 ? (
                  <Card className="p-6 bg-card rounded-xl border border-border text-center">
                    <GitBranch className="w-10 h-10 text-muted-foreground/30 mx-auto mb-3" />
                    <h3 className="text-sm font-semibold text-foreground mb-1">No Change Orders</h3>
                    <p className="text-xs text-muted-foreground">
                      No scope changes have been recorded for this project yet.
                    </p>
                  </Card>
                ) : (
                  <div className="space-y-3">
                    {selectedScopeChangeOrders.map((co) => (
                      <Card key={co._id} className="p-0 overflow-hidden border border-border">
                        <div className="p-4">
                          <div className="flex items-start justify-between mb-2">
                            <div className="flex items-center gap-2">
                              {getChangeTypeIcon(co.changeType)}
                              <h4 className="font-semibold text-sm text-foreground">{co.title}</h4>
                              {getStatusBadge(co.status)}
                            </div>
                            <span className="text-xs text-muted-foreground">{timeAgo(co.createdAt)}</span>
                          </div>
                          <p className="text-xs text-muted-foreground mb-3">{co.description}</p>

                          {/* Impact Grid */}
                          <div className="grid grid-cols-3 gap-3 mb-3">
                            <div className="p-2.5 rounded-lg bg-muted/50">
                              <div className="flex items-center gap-1 text-xs text-muted-foreground mb-0.5">
                                <Clock className="w-3 h-3" /> Time
                              </div>
                              <p className="text-sm font-bold text-foreground">+{co.impact.hoursAdded}h</p>
                            </div>
                            <div className="p-2.5 rounded-lg bg-muted/50">
                              <div className="flex items-center gap-1 text-xs text-muted-foreground mb-0.5">
                                <DollarSign className="w-3 h-3" /> Cost
                              </div>
                              <p className="text-sm font-bold text-foreground">+${co.impact.costImpact.toLocaleString()}</p>
                            </div>
                            {co.impact.deadlineImpact && (
                              <div className="p-2.5 rounded-lg bg-muted/50">
                                <div className="flex items-center gap-1 text-xs text-muted-foreground mb-0.5">
                                  <TrendingUp className="w-3 h-3" /> Deadline
                                </div>
                                <p className="text-sm font-bold text-foreground">+{co.impact.deadlineImpact} days</p>
                              </div>
                            )}
                          </div>

                          {/* Reason */}
                          <div className="p-2.5 rounded-lg bg-muted/30 text-xs">
                            <span className="font-medium text-muted-foreground">Reason: </span>
                            <span className="text-foreground">{co.reason}</span>
                          </div>

                          {/* Auto-generated warning */}
                          {co.autoGenerated && (
                            <div className="mt-2 p-2.5 rounded-lg bg-red-50 dark:bg-red-950/20 border border-red-200 dark:border-red-800 flex items-start gap-2">
                              <Zap className="w-3.5 h-3.5 text-red-600 dark:text-red-400 mt-0.5 flex-shrink-0" />
                              <div className="text-xs text-red-700 dark:text-red-300">
                                <p className="font-semibold">Auto-Detected Scope Creep</p>
                                <p>This change was automatically detected because it exceeds the revision limit ({co.originalLimit}). The limit has been increased to {co.newLimit}.</p>
                              </div>
                            </div>
                          )}

                          {/* Actions */}
                          {co.status === "pending" && (
                            <div className="mt-3 flex gap-2">
                              <Button size="sm" className="h-7 text-xs bg-green-600 hover:bg-green-700 text-white" onClick={() => handleApproveChangeOrder(co._id)}>
                                <CheckCircle2 className="w-3 h-3 mr-1" />
                                Approve
                              </Button>
                              <Button size="sm" variant="outline" className="h-7 text-xs" onClick={() => setShowFormalizeDialog(true)}>
                                <FileText className="w-3 h-3 mr-1" />
                                Formalize
                              </Button>
                              <Button size="sm" variant="outline" className="h-7 text-xs text-red-600 hover:text-red-700" onClick={() => toast.info("Change order rejected")}>
                                <XCircle className="w-3 h-3 mr-1" />
                                Reject
                              </Button>
                            </div>
                          )}
                          {co.status === "auto_generated" && (
                            <div className="mt-3 flex gap-2">
                              <Button size="sm" className="h-7 text-xs bg-green-600 hover:bg-green-700 text-white" onClick={() => handleApproveChangeOrder(co._id)}>
                                <CheckCircle2 className="w-3 h-3 mr-1" />
                                Approve
                              </Button>
                              <Button size="sm" className="h-7 text-xs bg-purple-600 hover:bg-purple-700 text-white" onClick={() => setShowFormalizeDialog(true)}>
                                <FileText className="w-3 h-3 mr-1" />
                                Formalize This Change
                              </Button>
                            </div>
                          )}

                          {/* Copy approval link for approved COs */}
                          {co.status === "approved" && co.clientApprovedAt && (
                            <div className="mt-2 flex items-center gap-2 text-xs text-green-600 dark:text-green-400">
                              <CheckCircle2 className="w-3 h-3" />
                              Client approved on {formatDate(co.clientApprovedAt)}
                            </div>
                          )}
                        </div>
                      </Card>
                    ))}
                  </div>
                )}
              </>
            )}
          </TabsContent>

          {/* ─── Formalizations Tab ───────────────────────────────────── */}
          <TabsContent value="formalizations" className="space-y-4">
            <div className="flex items-center justify-between mb-2">
              <p className="text-sm text-muted-foreground">
                Formalized scope changes create a legal record that protects your income in case of disputes.
              </p>
              <Button
                variant="outline"
                size="sm"
                className="h-8 text-xs"
                onClick={() => setShowFormalizeDialog(true)}
              >
                <Plus className="w-3 h-3 mr-1" />
                New Formalization
              </Button>
            </div>

            <Card className="p-6 bg-card rounded-xl border border-border text-center">
              <FileText className="w-10 h-10 text-muted-foreground/30 mx-auto mb-3" />
              <h3 className="text-sm font-semibold text-foreground mb-1">No Formalizations</h3>
              <p className="text-xs text-muted-foreground">
                Formalize scope changes to create dispute-proof records. Use the "Formalize Change" button above to get started.
              </p>
            </Card>
          </TabsContent>
        </Tabs>
      </PageLayout>

      {/* ─── Create Scope Definition Dialog ──────────────────────────── */}
      <Dialog open={showCreateScope} onOpenChange={setShowCreateScope}>
        <DialogContent className="sm:max-w-[600px] max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 min-w-0">
              <Shield className="w-5 h-5 text-primary shrink-0" />
              <span className="truncate">Create Scope Definition</span>
            </DialogTitle>
            <DialogDescription>
              Define the scope of work for a project. This creates a baseline for tracking scope changes and protecting against scope creep.
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4 py-4">
            <div className="p-3 bg-indigo-50 dark:bg-indigo-950/20 border border-indigo-200 dark:border-indigo-800 rounded-lg flex items-start gap-2">
              <Shield className="w-4 h-4 text-indigo-600 dark:text-indigo-400 mt-0.5" />
              <div className="text-xs text-indigo-800 dark:text-indigo-200 min-w-0 break-words">
                <p className="font-bold mb-1">Why define scope?</p>
                <p>Scope definitions create a documented baseline. When clients request changes beyond this baseline, they're formally tracked as change orders with time, cost, and deadline impacts — protecting your income from scope creep.</p>
              </div>
            </div>

            <div className="grid gap-2">
              <Label htmlFor="scopeTitle">Title <span className="text-red-500">*</span></Label>
              <Input id="scopeTitle" placeholder="e.g., E-Commerce Website Redesign" value={newScopeTitle} onChange={(e) => setNewScopeTitle(e.target.value)} />
            </div>

            <div className="grid gap-2">
              <Label htmlFor="scopeDescription">Description <span className="text-red-500">*</span></Label>
              <Textarea id="scopeDescription" placeholder="Describe the full scope of work..." value={newScopeDescription} onChange={(e) => setNewScopeDescription(e.target.value)} rows={3} />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="grid gap-2">
                <Label htmlFor="revisionLimit">Revision Limit</Label>
                <Input id="revisionLimit" type="number" placeholder="3" value={newScopeRevisionLimit} onChange={(e) => setNewScopeRevisionLimit(e.target.value)} />
                <p className="text-xs text-muted-foreground">Max revisions before auto-detecting scope creep</p>
              </div>
              <div className="grid gap-2">
                <Label htmlFor="estimatedHours">Estimated Hours</Label>
                <Input id="estimatedHours" type="number" placeholder="120" value={newScopeEstimatedHours} onChange={(e) => setNewScopeEstimatedHours(e.target.value)} />
              </div>
            </div>

            <div className="grid gap-2">
              <Label>Deliverables</Label>
              <p className="text-xs text-muted-foreground">Add deliverables after creating the scope definition</p>
            </div>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setShowCreateScope(false)}>Cancel</Button>
            <Button onClick={handleCreateScope} className="bg-primary hover:bg-primary/90">
              <Shield className="w-4 h-4 mr-2" />
              Create Scope
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ─── Create Change Order Dialog ──────────────────────────────── */}
      <Dialog open={showCreateChangeOrder} onOpenChange={setShowCreateChangeOrder}>
        <DialogContent className="sm:max-w-[600px] max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 min-w-0">
              <GitBranch className="w-5 h-5 text-primary shrink-0" />
              <span className="truncate">Record Scope Change</span>
            </DialogTitle>
            <DialogDescription>
              Document a scope change to track its impact and ensure proper client approval. This creates a formal record for dispute protection.
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4 py-4">
            <div className="grid gap-2">
              <Label htmlFor="coTitle">Change Title <span className="text-red-500">*</span></Label>
              <Input id="coTitle" placeholder="e.g., Add Product Review System" value={coTitle} onChange={(e) => setCoTitle(e.target.value)} />
            </div>

            <div className="grid gap-2">
              <Label htmlFor="coDescription">Description <span className="text-red-500">*</span></Label>
              <Textarea id="coDescription" placeholder="Describe what changed..." value={coDescription} onChange={(e) => setCoDescription(e.target.value)} rows={3} />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="grid gap-2">
                <Label>Change Type</Label>
                <Select value={coChangeType} onValueChange={(v: any) => setCoChangeType(v)}>
                  <SelectTrigger className="w-full"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="addition">Addition</SelectItem>
                    <SelectItem value="modification">Modification</SelectItem>
                    <SelectItem value="removal">Removal</SelectItem>
                    <SelectItem value="revision">Revision</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="grid gap-2">
                <Label htmlFor="coReason">Reason <span className="text-red-500">*</span></Label>
                <Input id="coReason" placeholder="Why this change was requested" value={coReason} onChange={(e) => setCoReason(e.target.value)} />
              </div>
            </div>

            <Separator />

            <div>
              <h4 className="text-sm font-semibold mb-3 flex items-center gap-2">
                <DollarSign className="w-4 h-4" />
                Impact Assessment
              </h4>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <div className="grid gap-2">
                  <Label htmlFor="coHoursAdded">Hours Added <span className="text-red-500">*</span></Label>
                  <Input id="coHoursAdded" type="number" placeholder="16" value={coHoursAdded} onChange={(e) => setCoHoursAdded(e.target.value)} />
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="coCostImpact">Cost Impact ($) <span className="text-red-500">*</span></Label>
                  <Input id="coCostImpact" type="number" placeholder="1360" value={coCostImpact} onChange={(e) => setCoCostImpact(e.target.value)} />
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="coDeadlineImpact">Deadline Impact (days)</Label>
                  <Input id="coDeadlineImpact" type="number" placeholder="5" value={coDeadlineImpact} onChange={(e) => setCoDeadlineImpact(e.target.value)} />
                </div>
              </div>
            </div>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setShowCreateChangeOrder(false)}>Cancel</Button>
            <Button onClick={handleCreateChangeOrder} className="bg-primary hover:bg-primary/90">
              <GitBranch className="w-4 h-4 mr-2" />
              Record Change
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ─── Formalize Scope Change Dialog ───────────────────────────── */}
      <Dialog open={showFormalizeDialog} onOpenChange={setShowFormalizeDialog}>
        <DialogContent className="sm:max-w-[600px] max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 min-w-0">
              <FileText className="w-5 h-5 text-primary shrink-0" />
              <span className="truncate">Formalize Scope Change</span>
            </DialogTitle>
            <DialogDescription>
              Document scope changes to protect your work and maintain clear client expectations. This creates a formal record that can be referenced in case of disputes.
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4 py-4">
            <div className="p-3 bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-800 rounded-lg flex items-start gap-2">
              <AlertTriangle className="w-4 h-4 text-amber-600 dark:text-amber-400 mt-0.5" />
              <div className="text-xs text-amber-800 dark:text-amber-200 min-w-0 break-words">
                <p className="font-bold mb-1">Why formalize scope changes?</p>
                <p>Unformalized scope creep is the #1 cause of payment disputes. Documenting changes protects your income and maintains professional boundaries.</p>
              </div>
            </div>

            <div className="grid gap-2">
              <Label htmlFor="formChangeDesc">Change Description <span className="text-red-500">*</span></Label>
              <Textarea id="formChangeDesc" placeholder="Describe what changed in the project scope..." value={formChangeDesc} onChange={(e) => setFormChangeDesc(e.target.value)} rows={3} />
            </div>

            <div className="grid gap-2">
              <Label htmlFor="formOriginalScope">Original Scope <span className="text-red-500">*</span></Label>
              <Textarea id="formOriginalScope" placeholder="What was originally agreed upon..." value={formOriginalScope} onChange={(e) => setFormOriginalScope(e.target.value)} rows={2} />
            </div>

            <div className="grid gap-2">
              <Label htmlFor="formNewScope">New Scope <span className="text-red-500">*</span></Label>
              <Textarea id="formNewScope" placeholder="What is now expected..." value={formNewScope} onChange={(e) => setFormNewScope(e.target.value)} rows={2} />
            </div>

            <div className="border rounded-lg p-4 space-y-3 bg-slate-50 dark:bg-slate-900/50">
              <h4 className="font-bold text-sm flex items-center gap-2">
                <DollarSign className="w-4 h-4" />
                Impact Assessment
              </h4>
              <div className="grid gap-2">
                <Label htmlFor="formTimeImpact" className="flex items-center gap-1">
                  <Clock className="w-3 h-3" /> Time Impact
                </Label>
                <Input id="formTimeImpact" placeholder="e.g., +10 hours, 2 extra weeks" value={formTimeImpact} onChange={(e) => setFormTimeImpact(e.target.value)} />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="formBudgetImpact">Budget Impact</Label>
                <Input id="formBudgetImpact" placeholder="e.g., +$500, 20% increase" value={formBudgetImpact} onChange={(e) => setFormBudgetImpact(e.target.value)} />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="formDeliverableImpact">Deliverable Impact</Label>
                <Input id="formDeliverableImpact" placeholder="e.g., 3 additional features, revised timeline" value={formDeliverableImpact} onChange={(e) => setFormDeliverableImpact(e.target.value)} />
              </div>
            </div>

            <div className="grid gap-2">
              <Label htmlFor="formClientAck">Client Acknowledgment (Optional)</Label>
              <Textarea id="formClientAck" placeholder="Paste client's email, message, or approval here..." value={formClientAck} onChange={(e) => setFormClientAck(e.target.value)} rows={3} />
              <p className="text-xs text-muted-foreground">Including client acknowledgment strengthens your protection score</p>
            </div>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setShowFormalizeDialog(false)}>Cancel</Button>
            <Button onClick={handleFormalize} className="bg-indigo-600 hover:bg-indigo-700">
              <CheckCircle2 className="w-4 h-4 mr-2" />
              Formalize Change
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
